/data/Software/DAQ/CDAQ/Plugins/Source/xmlParser.cpp File Reference
xmlParser.cpp File Reference
#include "xmlParser.h"
#include <memory.h>
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
Classes
struct ALLXMLClearTag
struct XMLCharacterEntity
struct XML
struct NextToken
Macros
#define _CRT_SECURE_NO_DEPRECATE
#define INDENTCHAR _X('\t')
#define XML_isSPACECHAR(ch) ((ch==_X('\n'))||(ch==_X(' '))||(ch== _X('\t'))||(ch==_X('\r')))
#define MEMORYINCREASE 50
#define LENSTR(lpsz) (lpsz ? xstrlen(lpsz) : 0)
#define BASE64DECODE_READ_NEXT_CHAR(c)
Typedefs
typedef enum XMLTokenTypeTag XMLTokenType
typedef struct XML XML
typedef enum Attrib Attrib
typedef enum Status Status
Enumerations
enum XMLTokenTypeTag {
eTokenText = 0, eTokenQuotedText, eTokenTagStart, eTokenTagEnd,
eTokenCloseTag, eTokenEquals, eTokenDeclaration, eTokenShortHandClose,
eTokenClear, eTokenError, eTokenText = 0, eTokenQuotedText,
eTokenTagStart, eTokenTagEnd, eTokenCloseTag, eTokenEquals,
eTokenDeclaration, eTokenShortHandClose, eTokenClear, eTokenError,
eTokenText = 0, eTokenQuotedText, eTokenTagStart, eTokenTagEnd,
eTokenCloseTag, eTokenEquals, eTokenDeclaration, eTokenShortHandClose,
eTokenClear, eTokenError, eTokenText = 0, eTokenQuotedText,
eTokenTagStart, eTokenTagEnd, eTokenCloseTag, eTokenEquals,
eTokenDeclaration, eTokenShortHandClose, eTokenClear, eTokenError
}
enum Attrib {
eAttribName = 0, eAttribEquals, eAttribValue, eAttribName = 0,
eAttribEquals, eAttribValue, eAttribName = 0, eAttribEquals,
eAttribValue, eAttribName = 0, eAttribEquals, eAttribValue
}
enum Status {
eInsideTag = 0, eOutsideTag, eInsideTag = 0, eOutsideTag,
eInsideTag = 0, eOutsideTag, eInsideTag = 0, eOutsideTag
}
Functions
void freeXMLString (XMLSTR t)
int mmin (const int t1, const int t2)
char myIsTextWideChar (const void *b, int len)
char * myWideCharToMultiByte (const wchar_t *s)
static FILE * xfopen (XMLCSTR filename, XMLCSTR mode)
static int xstrlen (XMLCSTR c)
static int xstrnicmp (XMLCSTR c1, XMLCSTR c2, int l)
static int xstrncmp (XMLCSTR c1, XMLCSTR c2, int l)
static int xstricmp (XMLCSTR c1, XMLCSTR c2)
static XMLSTR xstrstr (XMLCSTR c1, XMLCSTR c2)
static XMLSTR xstrcpy (XMLSTR c1, XMLCSTR c2)
static int _strnicmp (const char *c1, const char *c2, int l)
XMLSTR stringDup (XMLCSTR lpszData, int cbData)
XMLSTR toXMLStringUnSafe (XMLSTR dest, XMLCSTR source)
int lengthXMLString (XMLCSTR source)
XMLSTR fromXMLString (XMLCSTR s, int lo, XML *pXML)
char myTagCompare (XMLCSTR cclose, XMLCSTR copen)
static XMLCHAR getNextChar (XML *pXML)
static NextToken GetNextToken (XML *pXML, int *pcbToken, enum XMLTokenTypeTag *pType)
static void myFree (void *p)
static void * myRealloc (void *p, int newsize, int memInc, int sizeofElem)
static void CountLinesAndColumns (XMLCSTR lpXML, int nUpto, XMLResults *pResults)
static void charmemset (XMLSTR dest, XMLCHAR c, int l)
Variables
static XMLNode::XMLCharEncoding characterEncoding =XMLNode::encoding_UTF8
static char guessWideCharChars =1
static char dropWhiteSpace =1
static ALLXMLClearTag XMLClearTags []
static XMLCharacterEntity XMLEntities []
static const char XML_utf8ByteTable [256]
static const char XML_asciiByteTable [256]
static const char XML_sjisByteTable [256]
static const char * XML_ByteTable =(const char *)XML_utf8ByteTable
static const char base64Fillchar = _X('=')
XMLCSTR base64EncodeTable =_X("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
const unsigned char base64DecodeTable []
Macro Definition Documentation
#define _CRT_SECURE_NO_DEPRECATE
XML.c - implementation file for basic XML parser written in ANSI C++ for portability. It works by using recursion and a node tree for breaking down the elements of an XML document.
Version
V2.33
Author
Frank Vanden Berghen
NOTE:
If you add "#define STRICT_PARSING", on the first line of this file the parser will see the following XML-stream: some textother text as an error. Otherwise, this tring will be equivalent to: some textother text
NOTE:
If you add "#define APPROXIMATE_PARSING" on the first line of this file the parser will see the following XML-stream: <data name="n1"> <data name="n2"> <data name="n3"> as equivalent to the following XML-stream: <data name="n1"> <data name="n2"> <data name="n3"> This can be useful for badly-formed XML-streams but prevent the use of the following XML-stream (problem is: tags at contiguous levels have the same names): <data name="n1"> <data name="n2"> <data name="n3"> </data> </data>
NOTE:
If you add "#define _XMLPARSER_NO_MESSAGEBOX_" on the first line of this file the "openFileHelper" function will always display error messages inside the console instead of inside a message-box-window. Message-box-windows are available on windows 9x/NT/2000/XP/Vista only.
Copyright (c) 2002, Frank Vanden Berghen All rights reserved. See the file "AFPL-license.txt" about the licensing terms
#define BASE64DECODE_READ_NEXT_CHAR (c)
Value:
do { c=base64DecodeTable[(unsigned char)data[i++]]; }while (c==97);   \
        if(c==98){ if(xe)*xe=eXMLErrorBase64DecodeIllegalCharacter; return 0; }
Referenced by XMLParserBase64Tool::decode().
#define INDENTCHAR _X('\t')
Referenced by charmemset().
#define LENSTR (lpsz) (lpsz ? xstrlen(lpsz) : 0)
Referenced by charmemset().
#define MEMORYINCREASE 50
Referenced by myRealloc().
#define XML_isSPACECHAR (ch) ((ch==_X('\n'))||(ch==_X(' '))||(ch== _X('\t'))||(ch==_X('\r')))
Referenced by GetNextToken(), XMLNode::guessCharEncoding(), myRealloc(), and myTagCompare().
Typedef Documentation
typedef enum Attrib Attrib
typedef enum Status Status
typedef struct XML XML
typedef enum XMLTokenTypeTag XMLTokenType
Enumeration Type Documentation
enum Attrib
Enumerator
eAttribName
eAttribEquals
eAttribValue
eAttribName
eAttribEquals
eAttribValue
eAttribName
eAttribEquals
eAttribValue
eAttribName
eAttribEquals
eAttribValue
enum Status
Enumerator
eInsideTag
eOutsideTag
eInsideTag
eOutsideTag
eInsideTag
eOutsideTag
eInsideTag
eOutsideTag
enum XMLTokenTypeTag
Enumerator
eTokenText
eTokenQuotedText
eTokenTagStart
eTokenTagEnd
eTokenCloseTag
eTokenEquals
eTokenDeclaration
eTokenShortHandClose
eTokenClear
eTokenError
eTokenText
eTokenQuotedText
eTokenTagStart
eTokenTagEnd
eTokenCloseTag
eTokenEquals
eTokenDeclaration
eTokenShortHandClose
eTokenClear
eTokenError
eTokenText
eTokenQuotedText
eTokenTagStart
eTokenTagEnd
eTokenCloseTag
eTokenEquals
eTokenDeclaration
eTokenShortHandClose
eTokenClear
eTokenError
eTokenText
eTokenQuotedText
eTokenTagStart
eTokenTagEnd
eTokenCloseTag
eTokenEquals
eTokenDeclaration
eTokenShortHandClose
eTokenClear
eTokenError
Function Documentation
static int _strnicmp (const char * c1, const char * c2, int l) inline static
Referenced by XMLNode::guessCharEncoding(), and myIsTextWideChar().
static void charmemset (XMLSTR dest, XMLCHAR c, int l) inline static
References _X, eNodeChild, eNodeClear, eNodeText, INDENTCHAR, lengthXMLString(), LENSTR, XMLClear::lpszCloseTag, XMLAttribute::lpszName, XMLClear::lpszOpenTag, XMLClear::lpszValue, XMLAttribute::lpszValue, toXMLStringUnSafe(), XMLCHAR, XMLCSTR, XMLSTR, and xstrcpy().
static void CountLinesAndColumns (XMLCSTR lpXML, int nUpto, XMLResults * pResults) static
References _X, eXMLErrorNone, getNextChar(), XML::lpXML, XMLResults::nColumn, XML::nIndex, XMLResults::nLine, NULL, TRUE, and XMLCHAR.
Referenced by XMLNode::parseString().
void freeXMLString (XMLSTR t)
XMLSTR fromXMLString (XMLCSTR s, int lo, XML * pXML)
References _X, XMLCharacterEntity::c, XML::error, eXMLErrorUnknownCharacterEntity, XMLCharacterEntity::l, NULL, XMLCharacterEntity::s, XML_ByteTable, XMLCHAR, XMLCSTR, XMLEntities, XMLSTR, and xstrnicmp().
Referenced by myRealloc().
static XMLCHAR getNextChar (XML * pXML) inline static
References XML::lpXML, XML::nIndex, XML_ByteTable, and XMLCHAR.
Referenced by CountLinesAndColumns(), and GetNextToken().
static NextToken GetNextToken (XML * pXML, int * pcbToken, enum XMLTokenTypeTag * pType) static
References _X, eTokenClear, eTokenCloseTag, eTokenDeclaration, eTokenEquals, eTokenError, eTokenQuotedText, eTokenShortHandClose, eTokenTagEnd, eTokenTagStart, eTokenText, FALSE, getNextChar(), ALLXMLClearTag::lpszOpen, XML::lpXML, XML::nIndex, NULL, ALLXMLClearTag::openTagLen, NextToken::pClr, NextToken::pStr, TRUE, XML_isSPACECHAR, XMLCHAR, XMLClearTags, and xstrncmp().
Referenced by myRealloc().
int lengthXMLString (XMLCSTR source)
References XMLCharacterEntity::c, XMLCharacterEntity::l, XMLCharacterEntity::s, XML_ByteTable, XMLCHAR, and XMLEntities.
Referenced by charmemset(), lengthXMLString(), and ToXMLStringTool::toXML().
int mmin (const int t1, const int t2) inline
Referenced by charmemset(), XMLNode::guessCharEncoding(), and myIsTextWideChar().
static void myFree (void * p) inline static
Referenced by XMLNode::deleteNodeContent(), and myRealloc().
char myIsTextWideChar (const void * b, int len)
References _strnicmp(), characterEncoding, XMLNode::encoding_UTF8, FALSE, mmin(), myWideCharToMultiByte(), NULL, TRUE, xfopen(), XMLCHAR, XMLCSTR, XMLSTR, xstrcpy(), xstricmp(), xstrlen(), xstrncmp(), xstrnicmp(), and xstrstr().
Referenced by charmemset(), CountLinesAndColumns(), XMLNode::getError(), XMLNode::guessCharEncoding(), myIsTextWideChar(), and XMLNode::parseFile().
static void* myRealloc (void * p, int newsize, int memInc, int sizeofElem) inline static
References _X, XML::cbEndTag, XML::cbNewElement, dropWhiteSpace, eAttribEquals, eAttribName, eAttribValue, eInsideTag, XMLNode::emptyXMLAttribute, XMLNode::emptyXMLClear, XMLNode::emptyXMLNode, eNodeChild, eNodeClear, eNodeText, eOutsideTag, XML::error, eTokenClear, eTokenCloseTag, eTokenDeclaration, eTokenEquals, eTokenError, eTokenQuotedText, eTokenShortHandClose, eTokenTagEnd, eTokenTagStart, eTokenText, eXMLErrorMissingEndTag, eXMLErrorMissingEndTagName, eXMLErrorMissingTagName, eXMLErrorUnexpectedToken, eXMLErrorUnmatchedEndClearTag, eXMLErrorUnmatchedEndTag, FALSE, fromXMLString(), GetNextToken(), XMLNode::isDeclaration(), XMLNode::isEmpty(), XML::lpEndTag, XML::lpNewElement, ALLXMLClearTag::lpszClose, XMLClear::lpszCloseTag, XMLAttribute::lpszName, ALLXMLClearTag::lpszOpen, XMLClear::lpszOpenTag, XML::lpszText, XMLClear::lpszValue, XMLAttribute::lpszValue, XML::lpXML, MEMORYINCREASE, myFree(), myTagCompare(), XML::nFirst, XML::nIndex, XML::nIndexMissigEndTag, NULL, NextToken::pClr, NextToken::pStr, stringDup(), TRUE, XML_ByteTable, XML_isSPACECHAR, XMLCSTR, XMLNode::XMLNode(), XMLSTR, xstrlen(), and xstrstr().
char myTagCompare (XMLCSTR cclose, XMLCSTR copen)
References _X, XML_isSPACECHAR, XMLCHAR, xstrlen(), and xstrnicmp().
Referenced by myRealloc().
char* myWideCharToMultiByte (const wchar_t * s)
References _X, NULL, xfopen(), XMLCSTR, XMLSTR, xstrcpy(), xstricmp(), xstrlen(), xstrncmp(), xstrnicmp(), and xstrstr().
Referenced by CountLinesAndColumns(), myIsTextWideChar(), myWideCharToMultiByte(), and XMLNode::parseFile().
XMLSTR stringDup (XMLCSTR lpszData, int cbData)
Referenced by XMLNode::addAttribute(), XMLNode::addChild(), XMLNode::addClear(), XMLNode::addText(), charmemset(), XMLNode::createXMLTopNode(), XMLNode::deepCopy(), GetNextToken(), myRealloc(), XMLNode::updateAttribute(), XMLNode::updateAttribute_WOSD(), XMLNode::updateClear(), XMLNode::updateName(), and XMLNode::updateText().
XMLSTR toXMLStringUnSafe (XMLSTR dest, XMLCSTR source)
References XMLCharacterEntity::c, XMLCharacterEntity::l, XMLCharacterEntity::s, XML_ByteTable, XMLCHAR, XMLEntities, XMLSTR, and xstrcpy().
Referenced by charmemset(), lengthXMLString(), and ToXMLStringTool::toXML().
static FILE* xfopen (XMLCSTR filename, XMLCSTR mode) inline static
Referenced by myIsTextWideChar(), myWideCharToMultiByte(), XMLNode::openFileHelper(), XMLNode::parseFile(), and XMLNode::writeToFile().
static XMLSTR xstrcpy (XMLSTR c1, XMLCSTR c2) inline static
References XMLSTR.
Referenced by charmemset(), myIsTextWideChar(), myWideCharToMultiByte(), and toXMLStringUnSafe().
static int xstricmp (XMLCSTR c1, XMLCSTR c2) inline static
Referenced by XMLNode::getAttribute(), XMLNode::getChildNode(), XMLNode::getChildNodeWithAttribute(), XMLNode::isAttributeSet(), myIsTextWideChar(), myWideCharToMultiByte(), XMLNode::nChildNode(), and XMLNode::parseString().
static int xstrlen (XMLCSTR c) inline static
Referenced by myIsTextWideChar(), myRealloc(), myTagCompare(), myWideCharToMultiByte(), XMLNode::parseString(), and stringDup().
static int xstrncmp (XMLCSTR c1, XMLCSTR c2, int l) inline static
Referenced by GetNextToken(), myIsTextWideChar(), and myWideCharToMultiByte().
static int xstrnicmp (XMLCSTR c1, XMLCSTR c2, int l) inline static
Referenced by fromXMLString(), myIsTextWideChar(), myTagCompare(), and myWideCharToMultiByte().
static XMLSTR xstrstr (XMLCSTR c1, XMLCSTR c2) inline static
References XMLSTR.
Referenced by myIsTextWideChar(), myRealloc(), and myWideCharToMultiByte().
Variable Documentation
const unsigned char base64DecodeTable[]
Initial value:
= {
    99,98,98,98,98,98,98,98,98,97,  97,98,98,97,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
    98,98,97,98,98,98,98,98,98,98,  98,98,98,62,98,98,98,63,52,53,  54,55,56,57,58,59,60,61,98,98,
    98,96,98,98,98, 0, 1, 2, 3, 4,   5, 6, 7, 8, 9,10,11,12,13,14,  15,16,17,18,19,20,21,22,23,24,
    25,98,98,98,98,98,98,26,27,28,  29,30,31,32,33,34,35,36,37,38,  39,40,41,42,43,44,45,46,47,48,
    49,50,51,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
    98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
    98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
    98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98,98,98,98,98,
    98,98,98,98,98,98,98,98,98,98,  98,98,98,98,98,98
}
Referenced by XMLParserBase64Tool::decodeSize().
XMLCSTR base64EncodeTable =_X("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
Referenced by XMLParserBase64Tool::encode().
const char base64Fillchar = _X('=') static
Referenced by XMLParserBase64Tool::decodeSize(), and XMLParserBase64Tool::encode().
XMLNode::XMLCharEncoding characterEncoding =XMLNode::encoding_UTF8 static
Referenced by myIsTextWideChar(), XMLNode::setGlobalOptions(), and XMLNode::writeToFile().
char dropWhiteSpace =1 static
Referenced by XMLNode::createXMLString(), myRealloc(), XMLNode::openFileHelper(), and XMLNode::setGlobalOptions().
char guessWideCharChars =1 static
Referenced by XMLNode::guessCharEncoding(), XMLNode::openFileHelper(), XMLNode::parseFile(), and XMLNode::setGlobalOptions().
const char XML_asciiByteTable[256] static
Initial value:
=
{
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
}
Referenced by XMLNode::setGlobalOptions().
const char* XML_ByteTable =(const char *)XML_utf8ByteTable static
Referenced by fromXMLString(), getNextChar(), lengthXMLString(), myRealloc(), XMLNode::setGlobalOptions(), and toXMLStringUnSafe().
const char XML_sjisByteTable[256] static
Initial value:
=
{
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
}
Referenced by XMLNode::setGlobalOptions().
const char XML_utf8ByteTable[256] static
Initial value:
=
{
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
    3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
    4,4,4,4,4,1,1,1,1,1,1,1,1,1,1,1
}
Referenced by XMLNode::guessCharEncoding(), and XMLNode::setGlobalOptions().
ALLXMLClearTag XMLClearTags[] static
Initial value:
=
{
    {    _X("<![CDATA["),9,  _X("]]>")      },
    {    _X("<!DOCTYPE"),9,  _X(">")        },
    {    _X("<PRE>")    ,5,  _X("</PRE>")   },
    {    _X("<Script>") ,8,  _X("</Script>")},
    {    _X("<!--")     ,4,  _X("-->")      },
    {    NULL           ,0,  NULL           }
}
Referenced by GetNextToken().
XMLCharacterEntity XMLEntities[] static
Initial value:
=
{
    { _X("&amp;" ), 5, _X('&' )},
    { _X("&lt;"  ), 4, _X('<' )},
    { _X("&gt;"  ), 4, _X('>' )},
    { _X("&quot;"), 6, _X('\"')},
    { _X("&apos;"), 6, _X('\'')},
    { NULL        , 0, '\0'    }
}
Referenced by fromXMLString(), lengthXMLString(), and toXMLStringUnSafe().