/data/Software/DAQ/XDAQ/Core/Include/adc.h File Reference
adc.h File Reference
Functions
int adc_writereg (crate &crt, digitizer &adc, int i, u_int32_t addr, u_int32_t data)
int adc_readreg (crate &crt, digitizer &adc, int i, u_int32_t addr, u_int32_t &data)
int adc_init (crate &crt, digitizer &adc, int &EnableInt, int &EnableOLIrq, int &EnableBerr, int &EvAlign)
int adc_enable (crate &crt, digitizer &adc)
int adc_disable (crate &crt, digitizer &adc)
int adc_mblt (crate &crt, digitizer &adc, int i, u_int32_t *buff)
int adc_getbaseline (crate &crt, digitizer &adc)
int adc_analyzebaseline (crate &crt, digitizer &adc)
int adc_closecrates (crate &crt)
Function Documentation
int adc_analyzebaseline (crate & crt, digitizer & adc)
Referenced by main().
int adc_closecrates (crate & crt)
Referenced by main().
int adc_disable (crate & crt, digitizer & adc)
int adc_enable (crate & crt, digitizer & adc)
Referenced by main().
int adc_getbaseline (crate & crt, digitizer & adc)
Referenced by main().
int adc_init (crate & crt, digitizer & adc, int & EnableInt, int & EnableOLIrq, int & EnableBerr, int & EvAlign)
Referenced by main().
int adc_mblt (crate & crt, digitizer & adc, int i, u_int32_t * buff)
Referenced by main().
int adc_readreg (crate & crt, digitizer & adc, int i, u_int32_t addr, u_int32_t & data)
Referenced by ADCManager::GetBuffer().
int adc_writereg (crate & crt, digitizer & adc, int i, u_int32_t addr, u_int32_t data)
Referenced by control_configbaseline(), control_configfile(), ADCManager::GetBuffer(), and xml_readsettings().