/data/Software/DAQ/PDAQ/Core/Source/DRS.cpp File Reference
DRS.cpp File Reference
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <assert.h>
#include <algorithm>
#include <sys/stat.h>
#include <fcntl.h>
#include "strlcpy.h"
#include "DRS.h"
#include <iostream>
#include <unistd.h>
#include <sys/time.h>
#include <sys/ioctl.h>
#include <mxml.h>
Macros
#define NEW_TIMING_CALIBRATION
#define VCALIB_METHOD_V4 1
#define TCALIB_METHOD_V4 1
#define VCALIB_METHOD 2
#define TCALIB_METHOD 2
#define USB_TIMEOUT 1000
#define N_REG 8
#define MAX_N_BYTES 128*1024
#define F1(x) ((int) (84.0/24 * (x)))
#define F2(x) ((int) (92.0/8 * (x)))
Functions
void Sleep (useconds_t x)
int drs_kbhit ()
static int getch ()
unsigned int millitime ()
Variables
const int REQUIRED_FIRMWARE_VERSION_DRS2 = 5268
const int REQUIRED_FIRMWARE_VERSION_DRS3 = 6981
const int REQUIRED_FIRMWARE_VERSION_DRS4 = 15147
static unsigned short swf [kNumberOfChipsMax][kNumberOfChannelsMax][kNumberOfBins]
static float center [kNumberOfChipsMax][kNumberOfChannelsMax][kNumberOfBins]
int idx [4][10]
static unsigned short wft [kNumberOfChipsMax *kNumberOfChannelsMax *kNumberOfChipsMax][1024]
static unsigned short wf1 [kNumberOfChipsMax *kNumberOfChannelsMax *kNumberOfChipsMax][1024]
static unsigned short wf2 [kNumberOfChipsMax *kNumberOfChannelsMax *kNumberOfChipsMax][1024]
static unsigned short wf3 [kNumberOfChipsMax *kNumberOfChannelsMax *kNumberOfChipsMax][1024]
Macro Definition Documentation
#define F1 (x) ((int) (84.0/24 * (x)))
Referenced by DRSBoard::CalibrateVolt().
#define F2 (x) ((int) (92.0/8 * (x)))
#define MAX_N_BYTES 128*1024
Referenced by DRSBoard::RAMTest().
#define N_REG 8
Referenced by DRSBoard::RegisterTest().
#define NEW_TIMING_CALIBRATION
#define TCALIB_METHOD 2
Referenced by DRSBoard::CalibrateTiming(), and DRSBoard::ReadCalibration().
#define TCALIB_METHOD_V4 1
Referenced by DRSBoard::CalibrateTiming(), and DRSBoard::ReadCalibration().
#define USB_TIMEOUT 1000
Referenced by DRS::DRS(), DRSBoard::Read(), and DRSBoard::Write().
#define VCALIB_METHOD 2
Referenced by DRSBoard::CalibrateVolt(), and DRSBoard::ReadCalibration().
#define VCALIB_METHOD_V4 1
Referenced by DRSBoard::CalibrateVolt(), and DRSBoard::ReadCalibration().
Function Documentation
int drs_kbhit ()
Referenced by DRSBoard::MonitorFrequency(), and DRSBoard::RAMTest().
static int getch () inline static
Referenced by main(), DRSBoard::RAMTest(), and ScalerManager::ReadMultipleCycles().
unsigned int millitime ()
References NULL.
Referenced by ResponseCalibration::OffsetCalibrationV3().
void Sleep (useconds_t x) inline
Referenced by DRSBoard::CalibrateVolt(), DRSBoard::ChipTest(), DRS::DRS(), DRSBoard::InitFPGA(), DRSBoard::InteractSpeed(), DRSBoard::MeasureSpeed(), DRSBoard::MonitorFrequency(), ResponseCalibration::OffsetCalibrationV4(), DRSBoard::ReadEEPROM(), ResponseCalibration::RecordCalibrationPointsV4(), DRSBoard::RegulateFrequency(), DRSBoard::SetBoardSerialNumber(), DRSBoard::SetFrequency(), DRSBoard::SetVoltageOffset(), DRSBoard::TestDAC(), and DRSBoard::WriteEEPROM().
Variable Documentation
float center[kNumberOfChipsMax][kNumberOfChannelsMax][kNumberOfBins] static
Referenced by DRSBoard::AverageWaveforms(), DRSBoard::IsMultiBuffer(), and DRSBoard::SetInputRange().
int idx[4][10]
Initial value:
= {
   {  0,  2,  4,  6,  8, 18, 20, 22, 24, 26 },
   {  1,  3,  5,  7, 39, 19, 21, 23, 25, 39 },
   {  9, 11, 13, 15, 17, 27, 29, 31, 33, 35 },
   { 10, 12, 14, 16, 39, 28, 30, 32, 34, 39 },
}
Referenced by DRSBoard::CalibrateVolt(), mxml_add_special_node_at(), mxml_add_tree_at(), mxml_find_nodes1(), and mxml_subnode().
const int REQUIRED_FIRMWARE_VERSION_DRS2 = 5268
Referenced by DRSBoard::ReadSerialNumber().
const int REQUIRED_FIRMWARE_VERSION_DRS3 = 6981
Referenced by DRSBoard::ReadSerialNumber().
const int REQUIRED_FIRMWARE_VERSION_DRS4 = 15147
Referenced by DRSBoard::ReadSerialNumber().
unsigned short swf[kNumberOfChipsMax][kNumberOfChannelsMax][kNumberOfBins] static
Referenced by DRSBoard::AverageWaveforms(), and DRSBoard::RobustAverageWaveforms().
unsigned short wf1[kNumberOfChipsMax *kNumberOfChannelsMax *kNumberOfChipsMax][1024] static
Referenced by DRSBoard::CalibrateVolt(), StorageManager::GetEventsPerFile(), DRSBoard::GetWave(), and main().
unsigned short wf2[kNumberOfChipsMax *kNumberOfChannelsMax *kNumberOfChipsMax][1024] static
Referenced by DRSBoard::CalibrateVolt(), StorageManager::GetEventsPerFile(), DRSBoard::GetWave(), and main().
unsigned short wf3[kNumberOfChipsMax *kNumberOfChannelsMax *kNumberOfChipsMax][1024] static
Referenced by DRSBoard::CalibrateVolt(), StorageManager::GetEventsPerFile(), and main().
unsigned short wft[kNumberOfChipsMax *kNumberOfChannelsMax *kNumberOfChipsMax][1024] static
Referenced by DRSBoard::CalibrateVolt().