/data/Software/DAQ/XDAQ/GUI/Include/adc.h File Reference
adc.h File Reference
Functions
int adc_writereg (crate &crt, digitizer &adc, int i, u_int32_t addr, u_int32_t data)
int adc_readreg (crate &crt, digitizer &adc, int i, u_int32_t addr, u_int32_t &data)
int adc_init (crate &crt, digitizer &adc, int &EnableInt, int &EnableOLIrq, int &EnableBerr, int &EvAlign)
int adc_enable (crate &crt, digitizer &adc)
int adc_disable (crate &crt, digitizer &adc)
int adc_mblt (crate &crt, digitizer &adc, int i, u_int32_t *buff)
int adc_getbaseline (crate &crt, digitizer &adc)
int adc_analyzebaseline (crate &crt, digitizer &adc)
int adc_closecrates (crate &crt)
Function Documentation
int adc_analyzebaseline (crate & crt, digitizer & adc)
References adc_disable(), adc_enable(), adc_mblt(), adc_writereg(), digitizer::BufferSize, col(), control_getadc(), control_gettimestring(), errormsg(), NULL, digitizer::NumberOfADCs, digitizer::pmtmax, and SoftwareTrigger.
int adc_closecrates (crate & crt)
References errormsg(), crate::handle, and crate::NumberOfCrates.
int adc_disable (crate & crt, digitizer & adc)
References AcquisitionControlReg, adc_readreg(), adc_writereg(), and digitizer::NumberOfADCs.
Referenced by adc_analyzebaseline(), and adc_getbaseline().
int adc_enable (crate & crt, digitizer & adc)
References AcquisitionControlReg, adc_readreg(), adc_writereg(), and digitizer::NumberOfADCs.
Referenced by adc_analyzebaseline(), and adc_getbaseline().
int adc_getbaseline (crate & crt, digitizer & adc)
References adc_disable(), adc_enable(), adc_mblt(), adc_readreg(), adc_writereg(), digitizer::baseline, digitizer::BufferSize, col(), control_gettimestring(), DACRegister, errormsg(), digitizer::Id, KMAG, NULL, digitizer::NumberOfADCs, RESET, and SoftwareTrigger.
int adc_init (crate & crt, digitizer & adc, int & EnableInt, int & EnableOLIrq, int & EnableBerr, int & EvAlign)
References adc_readreg(), BlockOrganizationReg, BltEvNumReg, digitizer::BoardInfo, BoardInfoReg, ChannelConfigReg, ChannelFWRevision, digitizer::Crate, digitizer::ExpectedEvSize, FrontPanelIOData, digitizer::Id, MonitorModeReg, MotherBoardFWRevision, digitizer::NbSamplesEvt, digitizer::NumberOfADCs, PostTriggerReg, VMEControlReg, and digitizer::ZLE.
int adc_mblt (crate & crt, digitizer & adc, int i, u_int32_t * buff)
References digitizer::Address, digitizer::BltSize, digitizer::BufferSize, col(), digitizer::Crate, errormsg(), and crate::handle.
Referenced by adc_analyzebaseline(), and adc_getbaseline().
int adc_readreg (crate & crt, digitizer & adc, int i, u_int32_t addr, u_int32_t & data)
References digitizer::Address, digitizer::Crate, errormsg(), and crate::handle.
Referenced by adc_disable(), adc_enable(), adc_getbaseline(), and adc_init().
int adc_writereg (crate & crt, digitizer & adc, int i, u_int32_t addr, u_int32_t data)
References digitizer::Address, digitizer::Crate, errormsg(), and crate::handle.
Referenced by adc_analyzebaseline(), adc_disable(), adc_enable(), and adc_getbaseline().