/data/Software/DAQ/XDAQ/GUI/Include/control.h File Reference
control.h File Reference
#include <TFile.h>
#include <TTree.h>
#include <TBranch.h>
#include <TROOT.h>
Functions
int32_t get_time ()
void col (char *str)
int control_printtitle (char *SwRelease)
int control_scopehelp ()
int errormsg (int flag, char *s)
int control_log (FILE *file, int mode, char *s)
int control_gettimestring (char *timestr, char format)
int control_openlog (FILE **logfile, char *FileName, char *SwRelease)
int control_printlog (FILE *logfile, int time, char *text)
int control_cnts2log (FILE *logfile, scaler &s)
int control_cmdline (int argc, char *argv[], char *envp[], int &time, u_int32_t &NoE, var_graphics &graphics, int &baseline, digitizer &adc, char *OutFileName, char *XmlFileName)
int control_configfile (char *ConfigFileName, crate &crt, digitizer &adc, scaler &s, multipurposemodule &mp, int &WriteToFile)
int control_configbaseline (crate &crt, digitizer &adc)
int control_openfile (FILE **ofile, char *FileName, int &Filecounter, int WriteToFile, digitizer &adc, FILE *logfile)
int control_openrawrootfile (TFile **orootfile, TTree **t1, char *FileName, int &Filecounter, int WriteToFile, digitizer &adc, FILE *logfile, int *wf0, int *wf1, int *wf2, int *wf3, int *wf4, int *wf5, int *wf6, int *wf7)
int control_scfile (int time, float average, int stopped)
int control_calcrate (timeandtrigger &t, scaler &s, int FileEvtCounter)
int control_writedata (digitizer &adc, int i, FILE *ofile, int WriteToFile, int blt_bytes, u_int32_t *buff, int lowthres, int highthres)
int control_writerootrawdata (digitizer &adc, int i, TFile *orootfile, TTree *t1, int WriteToFile, int blt_bytes, u_int32_t *buff, int *wf0, int *wf1, int *wf2, int *wf3, int *wf4, int *wf5, int *wf6, int *wf7)
int control_generatefilename (char *OutFileName, char *path)
int control_calctime (timeandtrigger &t, int32_t ms, char *text)
int control_setdefault (digitizer &adc, scaler &s, timeandtrigger &t, crate &crt, multipurposemodule &mp, var_graphics &g)
int control_getadc (digitizer &adc, int pmt, int &module, int &channel)
Function Documentation
void col (char * str)
References NULL.
Referenced by control_scopehelp().
int control_calcrate (timeandtrigger & t, scaler & s, int FileEvtCounter)
int control_calctime (timeandtrigger & t, int32_t ms, char * text)
References KCYN, timeandtrigger::MeasSeconds, and RESET.
int control_cmdline (int argc, char * argv[], char * envp[], int & time, u_int32_t & NoE, var_graphics & graphics, int & baseline, digitizer & adc, char * OutFileName, char * XmlFileName)
References digitizer::BoardInfo, var_graphics::channel, control_gettimestring(), control_scopehelp(), errormsg(), jul, KRED, var_graphics::module, var_graphics::on, OutPutFolder, var_graphics::pmtNb, RESET, and sand.
int control_cnts2log (FILE * logfile, scaler & s)
References scaler::cnt, control_gettimestring(), control_printlog(), scaler::deadcnt, scaler::deadtime, scaler::lifecnt, scaler::lifetime, scaler::old, scaler::stop, scaler::totalcnt, and scaler::totaltime.
int control_configbaseline (crate & crt, digitizer & adc)
References adc_writereg(), BlockOrganizationReg, ChannelConfigReg, and digitizer::NumberOfADCs.
int control_configfile (char * ConfigFileName, crate & crt, digitizer & adc, scaler & s, multipurposemodule & mp, int & WriteToFile)
References ADC_MAX, adc_writereg(), digitizer::Address, digitizer::BltSize, digitizer::BoardInfo, digitizer::Crate, CRATE_MAX, errormsg(), crate::handle, digitizer::Id, digitizer::mask, NULL, digitizer::NumberOfADCs, crate::NumberOfCrates, digitizer::pmt, digitizer::pmtmax, power(), and digitizer::TriggerLatency.
int control_generatefilename (char * OutFileName, char * path)
int control_getadc (digitizer & adc, int pmt, int & module, int & channel)
References ADC_MAX, and digitizer::pmt.
int control_gettimestring (char * timestr, char format)
References NULL, and sand.
Referenced by control_cmdline(), control_cnts2log(), control_generatefilename(), control_openlog(), control_printlog(), and control_scfile().
int control_log (FILE * file, int mode, char * s)
References control_printlog().
Referenced by errormsg().
int control_openfile (FILE ** ofile, char * FileName, int & Filecounter, int WriteToFile, digitizer & adc, FILE * logfile)
References control_printlog(), errormsg(), digitizer::NbSamplesEvt, NULL, digitizer::NumberOfADCs, and digitizer::ZLE.
int control_openlog (FILE ** logfile, char * FileName, char * SwRelease)
References control_gettimestring(), errormsg(), and NULL.
int control_openrawrootfile (TFile ** orootfile, TTree ** t1, char * FileName, int & Filecounter, int WriteToFile, digitizer & adc, FILE * logfile, int * wf0, int * wf1, int * wf2, int * wf3, int * wf4, int * wf5, int * wf6, int * wf7)
int control_printlog (FILE * logfile, int time, char * text)
References control_gettimestring().
Referenced by control_cnts2log(), control_log(), control_openfile(), and control_openrawrootfile().
int control_printtitle (char * SwRelease)
References KGRN, and RESET.
int control_scfile (int time, float average, int stopped)
References control_gettimestring(), errormsg(), NULL, and SC_FILENAME.
Referenced by control_calcrate().
int control_scopehelp ()
References col(), KYEL, and RESET.
Referenced by control_cmdline().
int control_setdefault (digitizer & adc, scaler & s, timeandtrigger & t, crate & crt, multipurposemodule & mp, var_graphics & g)
References ADC_MAX, digitizer::baseline, digitizer::BltSize, digitizer::busy, scaler::deadcnt, scaler::deadtime, timeandtrigger::DisplayTime, multipurposemodule::HEVeto, scaler::lifecnt, scaler::lifetime, digitizer::mask, digitizer::NumberOfADCs, crate::NumberOfCrates, digitizer::pmt, digitizer::pmtmax, scaler::scalertime, scaler::totalcnt, scaler::totaltime, digitizer::TriggerLatency, var_graphics::x_autorange, var_graphics::x_display, var_graphics::x_high, var_graphics::x_low, var_graphics::y_display, var_graphics::y_high, and var_graphics::y_low.
int control_writedata (digitizer & adc, int i, FILE * ofile, int WriteToFile, int blt_bytes, u_int32_t * buff, int lowthres, int highthres)
int control_writerootrawdata (digitizer & adc, int i, TFile * orootfile, TTree * t1, int WriteToFile, int blt_bytes, u_int32_t * buff, int * wf0, int * wf1, int * wf2, int * wf3, int * wf4, int * wf5, int * wf6, int * wf7)
int errormsg (int flag, char * s)
References control_log(), KRED, and RESET.
Referenced by control_calcrate(), control_cmdline(), control_configfile(), control_generatefilename(), control_openfile(), control_openlog(), control_openrawrootfile(), and control_scfile().
int32_t get_time ()
Referenced by control_calcrate().