/data/Software/DAQ/CDAQ/Application/MultiDAQ.cpp File Reference
MultiDAQ.cpp File Reference
#include <iostream>
#include <unistd.h>
#include <fstream>
#include <sstream>
#include <cmath>
#include <map>
#include <math.h>
#include <vector>
#include <sys/time.h>
#include <string>
#include <Riostream.h>
#include "keyb.h"
#include <signal.h>
#include <global.h>
#include <VMEManager.h>
#include <ADCManager1730.h>
#include <ADCManager1724.h>
#include <ADCManager1720.h>
#include "ADCManager.h"
#include <ScopeManager.h>
#include <StorageManager.h>
#include <SlowcontrolManager.h>
#include <TH1D.h>
#include <TApplication.h>
#include <TCanvas.h>
#include <TStyle.h>
#include <TFile.h>
#include <TLatex.h>
#include "TTree.h"
#include "TROOT.h"
Functions
void sigproc (int sig)
int main (int argc, char *argv[], char *envp[])
Function Documentation
int main (int argc, char * argv[], char * envp[])
References SlowcontrolManager::AddBytes(), ADCManager::ApplySoftwareTrigger(), ADCManager::CalculateBaseLine(), ADCManager::CheckEventBuffer(), ADCManager::Checkkeyboard(), ADCManager::Disable(), ADCManager::Enable(), StorageManager::FillContainer(), SlowcontrolManager::GetADCInformation(), SlowcontrolManager::GetADCType(), SlowcontrolManager::GetAddress(), SlowcontrolManager::GetBaselineCalculation(), ADCManager::GetBuffer(), getch(), SlowcontrolManager::GetChannelNumber(), VMEManager::GetCrateHandle(), ADCManager::GetEventLength(), StorageManager::GetEventsPerFile(), SlowcontrolManager::GetFolderName(), SlowcontrolManager::GetGraphicsActive(), StorageManager::GetNumberEvents(), SlowcontrolManager::GetNumberEvents(), ADCManager::GetSoftwareRate(), ADCManager::GetTransferedBytes(), ADCManager::GetTreshold(), ADCManager::GetTriggerType(), SlowcontrolManager::GetXMLFile(), ScopeManager::graph_checkkey(), VMEManager::Init(), ScopeManager::Init(), SlowcontrolManager::Init(), StorageManager::Init(), ADCManager::Init(), StorageManager::NewFile(), SlowcontrolManager::ProcessInput(), ADCManager::ReadBaseLine(), StorageManager::SaveContainer(), ADCManager::SetADCAddress(), ADCManager::SetBaselineFile(), ScopeManager::SetBuffer(), StorageManager::SetBuffer(), ScopeManager::SetChannelNumber(), ScopeManager::SetChannelTresh(), ADCManager::SetCrateHandle(), ScopeManager::SetEventLength(), StorageManager::SetEventLength(), StorageManager::SetFolderName(), VMEManager::SetPCILink(), ADCManager::SetRegisterFile(), ScopeManager::SetXMLFile(), StorageManager::SetXMLFile(), ADCManager::SetXMLFile(), ScopeManager::ShowEvent(), SlowcontrolManager::ShowStatus(), sigproc(), SlowcontrolManager::StartAquistion(), and SlowcontrolManager::StopAquistion().
void sigproc (int sig)
References KRED, and RESET.
Referenced by main().