/data/Software/DAQ/PDAQ/Core/Source/xml.cpp File Reference
xml.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <sys/stat.h>
#include <unistd.h>
#include <iostream>
#include <sys/time.h>
#include "DRS.h"
#include "xmlParser.h"
#include "DAQContainer.h"
Macros
#define KNRM "\x1B[0m"
#define KRED "\x1B[31m"
#define KGRN "\x1B[32m"
#define KYEL "\x1B[33m"
#define KBLU "\x1B[34m"
#define KMAG "\x1B[35m"
#define KCYN "\x1B[36m"
#define KWHT "\x1B[37m"
#define RESET "\033[0m"
Functions
int xml_error (char *node)
int xml_readsettings (char filename[100], DRSBoard *b, DAQContainer *c)
Macro Definition Documentation
#define KBLU "\x1B[34m"
#define KCYN "\x1B[36m"
#define KGRN "\x1B[32m"
#define KMAG "\x1B[35m"
#define KNRM "\x1B[0m"
#define KRED "\x1B[31m"
Referenced by xml_error().
#define KWHT "\x1B[37m"
#define KYEL "\x1B[33m"
Referenced by xml_readsettings().
#define RESET "\033[0m"
Referenced by xml_error(), and xml_readsettings().
Function Documentation
int xml_error (char * node)
References KRED, and RESET.
Referenced by xml_readsettings().
int xml_readsettings (char filename[100], DRSBoard * b, DAQContainer * c)
References DRSBoard::EnableTcal(), DRSBoard::EnableTrigger(), XMLNode::getAttribute(), DRSBoard::GetBoardType(), XMLNode::getChildNode(), XMLNode::getText(), KYEL, NULL, XMLNode::openFileHelper(), DAQContainer::SetChannel0(), DAQContainer::SetChannel1(), DAQContainer::SetChannel2(), DAQContainer::SetChannel3(), DRSBoard::SetFrequency(), DAQContainer::SetGraphicModeType(), DAQContainer::SetGraphicYHigh(), DAQContainer::SetGraphicYLow(), DRSBoard::SetIndividualTriggerLevel(), DRSBoard::SetInputRange(), DAQContainer::SetNumberOfEvents(), DAQContainer::SetNumberPerFile(), DAQContainer::SetOutputDir(), DAQContainer::SetSaveType(), DRSBoard::SetTranspMode(), DRSBoard::SetTriggerDelayNs(), DRSBoard::SetTriggerLevel(), DRSBoard::SetTriggerPolarity(), DAQContainer::SetTriggerRate(), DRSBoard::SetTriggerSource(), DAQContainer::SetTriggerType(), and xml_error().
Referenced by main().