/data/Software/DAQ/PDAQ/Core/Include/xml.h File Reference
xml.h File Reference
#include "DAQContainer.h"
Functions
int xml_readsettings (char filename[100], DRSBoard *b, DAQContainer *c)
Function Documentation
int xml_readsettings (char filename[100], DRSBoard * b, DAQContainer * c)
References DRSBoard::EnableTcal(), DRSBoard::EnableTrigger(), XMLNode::getAttribute(), DRSBoard::GetBoardType(), XMLNode::getChildNode(), XMLNode::getText(), KYEL, NULL, XMLNode::openFileHelper(), DAQContainer::SetChannel0(), DAQContainer::SetChannel1(), DAQContainer::SetChannel2(), DAQContainer::SetChannel3(), DRSBoard::SetFrequency(), DAQContainer::SetGraphicModeType(), DAQContainer::SetGraphicYHigh(), DAQContainer::SetGraphicYLow(), DRSBoard::SetIndividualTriggerLevel(), DRSBoard::SetInputRange(), DAQContainer::SetNumberOfEvents(), DAQContainer::SetNumberPerFile(), DAQContainer::SetOutputDir(), DAQContainer::SetSaveType(), DRSBoard::SetTranspMode(), DRSBoard::SetTriggerDelayNs(), DRSBoard::SetTriggerLevel(), DRSBoard::SetTriggerPolarity(), DAQContainer::SetTriggerRate(), DRSBoard::SetTriggerSource(), DAQContainer::SetTriggerType(), and xml_error().
Referenced by main().