/data/Software/DAQ/Scaler/Core/Source/xml.cpp File Reference
xml.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <sys/stat.h>
#include <unistd.h>
#include <iostream>
#include <sys/time.h>
#include "xmlParser.h"
#include "VMEManager.h"
#include "DiscriminatorManager.h"
#include "ScalerManager.h"
#include "global.h"
Functions
int xml_error (char *node)
int xml_readsettings (char filename[100], VMEManager *VME, DiscriminatorManager *disc, ScalerManager *scaler)
Function Documentation
int xml_error (char * node)
References KRED, and RESET.
int xml_readsettings (char filename[100], VMEManager * VME, DiscriminatorManager * disc, ScalerManager * scaler)
References DiscriminatorManager::FillThresholds(), XMLNode::getAttribute(), XMLNode::getChildNode(), XMLNode::getText(), KYEL, XMLNode::openFileHelper(), RESET, ScalerManager::SetActive(), ScalerManager::SetCycles(), ScalerManager::SetDiscAddress(), DiscriminatorManager::SetDiscAddress(), ScalerManager::SetPath(), VMEManager::SetPCILink(), ScalerManager::SetRate(), ScalerManager::SetScalerActive(), DiscriminatorManager::SetTreshold(), and xml_error().