/data/Software/DAQ/XDAQ/Core/Include/xml.h File Reference
xml.h File Reference
Functions
int xml_readsettings (char filename[100], crate &crt, digitizer &adc, scaler &s, multipurposemodule &mp, timeandtrigger &t, var_graphics &graphics, u_int32_t &NoE, int &EventsPerFile, char *path, int &WriteToFile)
int xml_setdiscr (char filename[100])
int xml_storefile (char *filename, char *OutFileName)
Function Documentation
int xml_readsettings (char filename[100], crate & crt, digitizer & adc, scaler & s, multipurposemodule & mp, timeandtrigger & t, var_graphics & graphics, u_int32_t & NoE, int & EventsPerFile, char * path, int & WriteToFile)
References adc_writereg(), AnalogMonitorSettings, digitizer::baseline, BlockOrganizationReg, digitizer::busy, digitizer::channel, ChannelConfigReg, control_getadc(), CustomWindow, timeandtrigger::DisplayTime, errormsg(), digitizer::EventLength, FrontPanelIOData, XMLNode::getAttribute(), XMLNode::getChildNode(), XMLNode::getText(), KYEL, LookBackForward, MonitorModeReg, digitizer::NbChannels, XMLNode::nChildNode(), NULL, digitizer::NumberOfADCs, XMLNode::openFileHelper(), PostTriggerReg, RESET, S1Threshold, digitizer::sample_size, digitizer::sampling_freq, SingleZLEThresh, digitizer::trig, digitizer::TriggerLatency, digitizer::trigmask, digitizer::voltage_range, var_graphics::x_autorange, var_graphics::x_display, var_graphics::x_high, var_graphics::x_low, xml_error(), var_graphics::y_display, var_graphics::y_high, var_graphics::y_low, and ZLEThreshold.
int xml_setdiscr (char filename[100])
int xml_storefile (char * filename, char * OutFileName)
Referenced by main().