/data/Software/DAQ/XDAQ/Core/Source/xml.cpp File Reference
xml.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <sys/stat.h>
#include <unistd.h>
#include <sys/time.h>
#include "global.h"
#include "adc.h"
#include "control.h"
#include "xmlParser.h"
Macros
#define KNRM "\x1B[0m"
#define KRED "\x1B[31m"
#define KGRN "\x1B[32m"
#define KYEL "\x1B[33m"
#define KBLU "\x1B[34m"
#define KMAG "\x1B[35m"
#define KCYN "\x1B[36m"
#define KWHT "\x1B[37m"
#define RESET "\033[0m"
Functions
int xml_error (char *node)
int xml_readsettings (char filename[100], crate &crt, digitizer &adc, scaler &s, multipurposemodule &mp, timeandtrigger &t, var_graphics &graphics, u_int32_t &NoE, int &EventsPerFile, char *path, int &WriteToFile)
int xml_storefile (char *filename, char *OutFileName)
Macro Definition Documentation
#define KBLU "\x1B[34m"
#define KCYN "\x1B[36m"
#define KGRN "\x1B[32m"
#define KMAG "\x1B[35m"
#define KNRM "\x1B[0m"
#define KRED "\x1B[31m"
#define KWHT "\x1B[37m"
#define KYEL "\x1B[33m"
Referenced by xml_readsettings().
#define RESET "\033[0m"
Referenced by xml_readsettings().
Function Documentation
int xml_error (char * node)
References errormsg().
int xml_readsettings (char filename[100], crate & crt, digitizer & adc, scaler & s, multipurposemodule & mp, timeandtrigger & t, var_graphics & graphics, u_int32_t & NoE, int & EventsPerFile, char * path, int & WriteToFile)
References adc_writereg(), AnalogMonitorSettings, digitizer::baseline, BlockOrganizationReg, digitizer::busy, digitizer::channel, ChannelConfigReg, control_getadc(), CustomWindow, timeandtrigger::DisplayTime, errormsg(), digitizer::EventLength, FrontPanelIOData, XMLNode::getAttribute(), XMLNode::getChildNode(), XMLNode::getText(), KYEL, LookBackForward, MonitorModeReg, digitizer::NbChannels, XMLNode::nChildNode(), NULL, digitizer::NumberOfADCs, XMLNode::openFileHelper(), PostTriggerReg, RESET, S1Threshold, digitizer::sample_size, digitizer::sampling_freq, SingleZLEThresh, digitizer::trig, digitizer::TriggerLatency, digitizer::trigmask, digitizer::voltage_range, var_graphics::x_autorange, var_graphics::x_display, var_graphics::x_high, var_graphics::x_low, xml_error(), var_graphics::y_display, var_graphics::y_high, var_graphics::y_low, and ZLEThreshold.
int xml_storefile (char * filename, char * OutFileName)
References errormsg().
Referenced by main().