/data/Software/DAQ/XDAQ/Core/Source/adc.cpp File Reference
adc.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <sys/stat.h>
#include <unistd.h>
#include <iostream>
#include "global.h"
#include "CAENVMElib.h"
#include "control.h"
#include <TH1D.h>
#include <TApplication.h>
#include <TCanvas.h>
#include <TStyle.h>
#include <TFile.h>
#include <TLatex.h>
Macros
#define KNRM "\x1B[0m"
#define KRED "\x1B[31m"
#define KGRN "\x1B[32m"
#define KYEL "\x1B[33m"
#define KBLU "\x1B[34m"
#define KMAG "\x1B[35m"
#define KCYN "\x1B[36m"
#define KWHT "\x1B[37m"
#define RESET "\033[0m"
Functions
int adc_writereg (crate &crt, digitizer &adc, int i, u_int32_t addr, u_int32_t data)
int adc_readreg (crate &crt, digitizer &adc, int i, u_int32_t addr, u_int32_t &data)
int adc_init (crate &crt, digitizer &adc, int &EnableInt, int &EnableOLIrq, int &EnableBerr, int &EvAlign)
int adc_enable (crate &crt, digitizer &adc)
int adc_disable (crate &crt, digitizer &adc)
int adc_mblt (crate &crt, digitizer &adc, int i, u_int32_t *buff)
int adc_getbaseline (crate &crt, digitizer &adc)
int adc_analyzebaseline (crate &crt, digitizer &adc)
int adc_closecrates (crate &crt)
Macro Definition Documentation
#define KBLU "\x1B[34m"
#define KCYN "\x1B[36m"
#define KGRN "\x1B[32m"
#define KMAG "\x1B[35m"
Referenced by adc_getbaseline().
#define KNRM "\x1B[0m"
#define KRED "\x1B[31m"
#define KWHT "\x1B[37m"
#define KYEL "\x1B[33m"
#define RESET "\033[0m"
Referenced by adc_getbaseline().
Function Documentation
int adc_analyzebaseline (crate & crt, digitizer & adc)
References adc_disable(), adc_enable(), adc_mblt(), adc_writereg(), digitizer::BufferSize, col(), control_getadc(), control_gettimestring(), errormsg(), NULL, digitizer::NumberOfADCs, digitizer::pmtmax, and SoftwareTrigger.
Referenced by main().
int adc_closecrates (crate & crt)
References errormsg(), crate::handle, and crate::NumberOfCrates.
Referenced by main().
int adc_disable (crate & crt, digitizer & adc)
References AcquisitionControlReg, adc_readreg(), adc_writereg(), and digitizer::NumberOfADCs.
Referenced by adc_analyzebaseline(), and adc_getbaseline().
int adc_enable (crate & crt, digitizer & adc)
References AcquisitionControlReg, adc_readreg(), adc_writereg(), and digitizer::NumberOfADCs.
Referenced by adc_analyzebaseline(), adc_getbaseline(), and main().
int adc_getbaseline (crate & crt, digitizer & adc)
References adc_disable(), adc_enable(), adc_mblt(), adc_readreg(), adc_writereg(), digitizer::baseline, digitizer::BufferSize, col(), control_gettimestring(), DACRegister, errormsg(), digitizer::Id, KMAG, NULL, digitizer::NumberOfADCs, RESET, and SoftwareTrigger.
Referenced by main().
int adc_init (crate & crt, digitizer & adc, int & EnableInt, int & EnableOLIrq, int & EnableBerr, int & EvAlign)
References adc_readreg(), BlockOrganizationReg, BltEvNumReg, digitizer::BoardInfo, BoardInfoReg, ChannelConfigReg, ChannelFWRevision, digitizer::Crate, digitizer::ExpectedEvSize, FrontPanelIOData, digitizer::Id, MonitorModeReg, MotherBoardFWRevision, digitizer::NbSamplesEvt, digitizer::NumberOfADCs, PostTriggerReg, VMEControlReg, and digitizer::ZLE.
Referenced by main().
int adc_mblt (crate & crt, digitizer & adc, int i, u_int32_t * buff)
References digitizer::Address, digitizer::BltSize, digitizer::BufferSize, col(), digitizer::Crate, errormsg(), and crate::handle.
Referenced by adc_analyzebaseline(), adc_getbaseline(), and main().
int adc_readreg (crate & crt, digitizer & adc, int i, u_int32_t addr, u_int32_t & data)
References digitizer::Address, digitizer::Crate, errormsg(), and crate::handle.
Referenced by adc_disable(), adc_enable(), adc_getbaseline(), adc_init(), and ADCManager::GetBuffer().
int adc_writereg (crate & crt, digitizer & adc, int i, u_int32_t addr, u_int32_t data)
References digitizer::Address, digitizer::Crate, errormsg(), and crate::handle.
Referenced by adc_analyzebaseline(), adc_disable(), adc_enable(), adc_getbaseline(), control_configbaseline(), control_configfile(), ADCManager::GetBuffer(), and xml_readsettings().