Averager Class Reference
Averager Class Reference
#include <averager.h>
Public Member Functions
Averager (int nx, int ny, int nz, int dim)
~Averager ()
void Add (int x, int y, int z, float value)
void Reset ()
double Average (int x, int y, int z)
double Median (int x, int y, int z)
double RobustAverage (double range, int x, int y, int z)
int SaveNormalizedDistribution (const char *filename, int x, float range)
Constructor & Destructor Documentation
Averager::Averager (int nx, int ny, int nz, int dim)
Averager::~Averager ()
References NULL.
Member Function Documentation
void Averager::Add (int x, int y, int z, float value)
Referenced by DRSBoard::AnalyzeSlope(), and DRSBoard::RobustAverageWaveforms().
double Averager::Average (int x, int y, int z)
double Averager::Median (int x, int y, int z)
References compar().
Referenced by DRSBoard::AnalyzeSlope(), RobustAverage(), and SaveNormalizedDistribution().
void Averager::Reset ()
References compar().
double Averager::RobustAverage (double range, int x, int y, int z)
References Median().
Referenced by DRSBoard::AnalyzeSlope(), and DRSBoard::RobustAverageWaveforms().
int Averager::SaveNormalizedDistribution (const char * filename, int x, float range)
References Median().
Referenced by DRSBoard::RobustAverageWaveforms().
The documentation for this class was generated from the following files:
/data/Software/DAQ/PDAQ/Core/Include/averager.h
/data/Software/DAQ/PDAQ/Core/Source/averager.cpp