ADCManager1724 Class Reference
ADCManager1724 Class Reference
#include <ADCManager1724.h>
Public Member Functions
ADCManager1724 ()
virtual ~ADCManager1724 ()
int Init ()
Public Member Functions inherited from Common
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
int error (char *node)
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
Common ()
string GetTime ()
int GetUnixTime ()
string GetDayYear ()
string GetDay ()
Public Member Functions inherited from ADCManager
ADCManager ()
virtual ~ADCManager ()
void SetCrateHandle (int handle)
void SetADCAddress (string address)
void SetRegisterFile (string file)
void SetBaselineFile (string file="DACBaseline.ini")
void SetXMLFile (char *file)
int GetCrateHandle ()
int GetTransferedBytes ()
int GetEventLength ()
int GetTriggerType ()
double GetSoftwareRate ()
int * GetTreshold ()
u_int32_t * GetBuffer ()
int ReadBaseLine ()
int CalculateBaseLine ()
int ApplySoftwareTrigger ()
int CheckEventBuffer ()
int Enable ()
int Disable ()
int Checkkeyboard (char c)
Additional Inherited Members
Protected Member Functions inherited from ADCManager
int adc_readreg (u_int32_t addr, u_int32_t &data)
int adc_writereg (u_int32_t addr, u_int32_t data)
int adc_readblt ()
int RegisterWriting (string configfilename)
u_int32_t StringToHex (const string &str)
string IntToString (const int num)
Protected Attributes inherited from Common
string Message
Protected Attributes inherited from ADCManager
u_int32_t * buffer
u_int32_t m_ADCaddr
u_int32_t m_addr
u_int32_t m_hex
u_int32_t m_ExpectedEvSize
int m_length
int m_CrateHandle
int m_MemorySize
int m_BufferSize
int m_EnableVMEIrq
int m_Align64
int m_EnableBerr
int m_EnableOLIrq
int m_EnableInt
int m_EvAlign
CAEN_BYTE IrqMask
CAEN_BYTE IrqCheckMask
string m_RegisterFileName
string m_BaselineFileName
char * m_XmlFileName
int blt_bytes
int pnt
int Size
int cnt
int wavecnt
int CurrentChannel
int nb
int ret
double m_mean
double m_diff
double m_std
double m_correction
u_int32_t m_DACLevel [8]
u_int32_t m_DACTarget [8]
int m_Frequency
int m_Baseline
int m_iteration
int m_resDAC
int m_resADC
int m_Voltage
int m_nbCh
int m_triggertyp
int m_nbchs
int * channelTresh
int m_SoftwareRate
int m_module
u_int32_t m_posttrigger
Constructor & Destructor Documentation
ADCManager1724::ADCManager1724 ()
References ADCManager::m_ADCaddr, ADCManager::m_Align64, ADCManager::m_Baseline, ADCManager::m_CrateHandle, ADCManager::m_DACTarget, ADCManager::m_EnableBerr, ADCManager::m_EnableInt, ADCManager::m_EnableOLIrq, ADCManager::m_EnableVMEIrq, ADCManager::m_EvAlign, ADCManager::m_Frequency, ADCManager::m_nbCh, ADCManager::m_resDAC, ADCManager::m_SoftwareRate, ADCManager::m_triggertyp, and ADCManager::m_Voltage.
ADCManager1724::~ADCManager1724 () virtual
Member Function Documentation
int ADCManager1724::Init () virtual
Reimplemented from ADCManager.
References ADCManager::adc_readreg(), ADCManager::adc_writereg(), BlockOrganizationReg, ADCManager::buffer, ChannelEnableMaskReg, ADCManager::channelTresh, CORRECTION, CustomWindowReg, Common::error(), FirmwareRegN, FrontPanelIODataReg, FrontPanelTriggerOutReg, XMLNode::getChildNode(), XMLNode::getText(), KGRN, KRED, KYEL, ADCManager::m_Align64, ADCManager::m_Baseline, ADCManager::m_BufferSize, ADCManager::m_DACTarget, ADCManager::m_EnableBerr, ADCManager::m_EnableInt, ADCManager::m_EnableOLIrq, ADCManager::m_EnableVMEIrq, ADCManager::m_EvAlign, ADCManager::m_ExpectedEvSize, ADCManager::m_Frequency, ADCManager::m_hex, ADCManager::m_iteration, ADCManager::m_length, ADCManager::m_MemorySize, ADCManager::m_nbCh, ADCManager::m_posttrigger, ADCManager::m_RegisterFileName, ADCManager::m_resADC, ADCManager::m_resDAC, ADCManager::m_SoftwareRate, ADCManager::m_triggertyp, ADCManager::m_Voltage, ADCManager::m_XmlFileName, MonitorModeReg, MotherBoardFWRevision, NULL, XMLNode::openFileHelper(), PostTriggerReg, ADCManager::RegisterWriting(), RESET, SoftwareResetReg, StatusRegN, TresholdRegN, and TriggerSourceMaskReg.
The documentation for this class was generated from the following files:
/data/Software/DAQ/CDAQ/Core/Include/ADCManager1724.h
/data/Software/DAQ/CDAQ/Core/Source/ADCManager1724.cpp