SlowcontrolManager Class Reference
SlowcontrolManager Class Reference
#include <SlowcontrolManager.h>
Public Member Functions
SlowcontrolManager ()
virtual ~SlowcontrolManager ()
int Init ()
int ProcessInput (int argc, char *argv[], char *envp[])
int xml_storefile ()
char * GetXMLFile ()
int GetBaselineCalculation ()
int GetGraphicsActive ()
int GetChannelNumber ()
int GetNumberEvents ()
char * GetFolderName ()
int GetADCInformation ()
string GetAddress ()
int GetADCType ()
int StartAquistion ()
int StopAquistion ()
int ShowStatus (int status=1)
void AddBytes (int bytes)
Public Member Functions inherited from Common
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
int error (char *node)
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
Common ()
string GetTime ()
int GetUnixTime ()
string GetDayYear ()
string GetDay ()
Additional Inherited Members
Protected Attributes inherited from Common
string Message
Constructor & Destructor Documentation
SlowcontrolManager::SlowcontrolManager ()
References Common::gettimestring(), KGRN, and RESET.
SlowcontrolManager::~SlowcontrolManager () virtual
Member Function Documentation
void SlowcontrolManager::AddBytes (int bytes) inline
Referenced by main().
int SlowcontrolManager::GetADCInformation () inline
Referenced by main().
int SlowcontrolManager::GetADCType () inline
Referenced by main().
string SlowcontrolManager::GetAddress () inline
Referenced by main().
int SlowcontrolManager::GetBaselineCalculation () inline
Referenced by main().
int SlowcontrolManager::GetChannelNumber () inline
Referenced by main().
char* SlowcontrolManager::GetFolderName () inline
Referenced by main().
int SlowcontrolManager::GetGraphicsActive () inline
Referenced by main().
int SlowcontrolManager::GetNumberEvents () inline
Referenced by main().
char* SlowcontrolManager::GetXMLFile () inline
Referenced by main().
int SlowcontrolManager::Init ()
Referenced by main().
int SlowcontrolManager::ProcessInput (int argc, char * argv[], char * envp[])
References Common::gettimestring(), KRED, and RESET.
Referenced by main().
int SlowcontrolManager::ShowStatus (int status = 1)
References Common::error(), XMLNode::getAttribute(), XMLNode::getChildNode(), XMLNode::getText(), KCYN, KGRN, KYEL, NULL, XMLNode::openFileHelper(), and RESET.
Referenced by main().
int SlowcontrolManager::StartAquistion ()
References KYEL, NULL, and RESET.
Referenced by main().
int SlowcontrolManager::StopAquistion ()
References KGRN, NULL, and RESET.
Referenced by main().
int SlowcontrolManager::xml_storefile ()
The documentation for this class was generated from the following files:
/data/Software/DAQ/CDAQ/Core/Include/SlowcontrolManager.h
/data/Software/DAQ/CDAQ/Core/Source/SlowcontrolManager.cpp