ScopeManager Class Reference
ScopeManager Class Reference
#include <ScopeManager.h>
Public Member Functions
ScopeManager ()
virtual ~ScopeManager ()
int Init ()
void SetBuffer (u_int32_t *adcBuffer)
void SetEventLength (int length)
void SetXMLFile (char *file)
void SetChannelTresh (int *channel)
int ShowEvent ()
int graph_checkkey (char c)
void SetChannelNumber (int channeL)
Public Member Functions inherited from Common
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
int error (char *node)
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
Common ()
string GetTime ()
int GetUnixTime ()
string GetDayYear ()
string GetDay ()
Additional Inherited Members
Protected Attributes inherited from Common
string Message
Constructor & Destructor Documentation
ScopeManager::ScopeManager ()
ScopeManager::~ScopeManager () virtual
Member Function Documentation
int ScopeManager::graph_checkkey (char c)
Referenced by main().
int ScopeManager::Init ()
Referenced by main().
void ScopeManager::SetBuffer (u_int32_t * adcBuffer) inline
Referenced by main().
void ScopeManager::SetChannelNumber (int channeL) inline
References graph_edit().
Referenced by main().
void ScopeManager::SetChannelTresh (int * channel) inline
References graph_checkkey().
Referenced by main().
void ScopeManager::SetEventLength (int length) inline
Referenced by main().
void ScopeManager::SetXMLFile (char * file) inline
Referenced by main().
int ScopeManager::ShowEvent ()
References Common::error(), XMLNode::getChildNode(), XMLNode::getText(), and XMLNode::openFileHelper().
Referenced by main().
The documentation for this class was generated from the following files:
/data/Software/DAQ/CDAQ/Core/Include/ScopeManager.h
/data/Software/DAQ/CDAQ/Core/Source/ScopeManager.cpp