DRSBoard Class Reference
DRSBoard Class Reference
#include <DRS.h>
Classes
class TimeData
Public Member Functions
~DRSBoard ()
int SetBoardSerialNumber (unsigned short serialNumber)
int GetBoardSerialNumber () const
int HasMultiBuffer () const
int GetFirmwareVersion () const
int GetRequiredFirmwareVersion () const
int GetDRSType () const
int GetBoardType () const
int GetNumberOfChips () const
int GetNumberOfChannels () const
int GetChannelDepth () const
int GetChannelCascading () const
int GetNumberOfReadoutChannels () const
int GetWaveformBufferSize () const
int GetNumberOfInputs () const
int GetNumberOfCalibInputs () const
int GetClockChannel () const
int GetTriggerChannel () const
int GetClockInput () const
int GetTriggerInput () const
int Channel2Input (int channel) const
int Channel2ReadoutChannel (int channel) const
int Input2Channel (int input, int ind=0) const
int Input2ReadoutChannel (int input, int ind=0) const
int ReadoutChannel2Channel (int readout) const
int ReadoutChannel2Input (int readout) const
bool IsCalibChannel (int ch) const
bool IsCalibInput (int input) const
int GetSlotNumber () const
int InitFPGA (void)
int Write (int type, unsigned int addr, void *data, int size)
int Read (int type, void *data, unsigned int addr, int size)
int GetTransport () const
void RegisterTest (void)
int RAMTest (int flag)
int ChipTest ()
unsigned int GetCtrlReg (void)
unsigned short GetConfigReg (void)
unsigned int GetStatusReg (void)
void SetLED (int state)
int SetChannelConfig (int firstChannel, int lastChannel, int nConfigChannels)
void SetADCClkPhase (int phase, bool invert)
void SetWarmup (unsigned int ticks)
void SetCooldown (unsigned int ticks)
int GetReadoutChannelConfig ()
void SetNumberOfChannels (int nChannels)
int EnableTrigger (int flag1, int flag2)
int GetTriggerEnable (int i)
int SetDelayedTrigger (int flag)
int SetTriggerDelayPercent (int delay)
int SetTriggerDelayNs (int delay)
int GetTriggerDelay ()
double GetTriggerDelayNs ()
int SetSyncDelay (int ticks)
int SetTriggerLevel (double value)
int SetIndividualTriggerLevel (int channel, double voltage)
int SetTriggerPolarity (bool negative)
int SetTriggerSource (int source)
int GetTriggerSource ()
int SetDelayedStart (int flag)
int SetTranspMode (int flag)
int SetStandbyMode (int flag)
int SetDecimation (int flag)
int GetDecimation ()
int IsBusy (void)
int IsEventAvailable (void)
int IsPLLLocked (void)
int IsLMKLocked (void)
int IsNewFreq (unsigned char chipIndex)
int SetDAC (unsigned char channel, double value)
int ReadDAC (unsigned char channel, double *value)
int GetRegulationDAC (double *value)
int StartDomino ()
int StartClearCycle ()
int FinishClearCycle ()
int Reinit ()
int Init ()
void SetDebug (int debug)
int Debug ()
int SetDominoMode (unsigned char mode)
int SetDominoActive (unsigned char mode)
int SetReadoutMode (unsigned char mode)
int SoftTrigger (void)
int ReadFrequency (unsigned char chipIndex, double *f)
int SetFrequency (double freq, bool wait)
double VoltToFreq (double volt)
double FreqToVolt (double freq)
double GetNominalFrequency () const
double GetTrueFrequency ()
int RegulateFrequency (double freq)
int SetExternalClockFrequency (double frequencyMHz)
double GetExternalClockFrequency ()
int SetMultiBuffer (int flag)
int IsMultiBuffer ()
void ResetMultiBuffer (void)
int GetMultiBufferRP (void)
int SetMultiBufferRP (unsigned short rp)
int GetMultiBufferWP (void)
void IncrementMultiBufferRP (void)
void SetVoltageOffset (double offset1, double offset2)
int SetInputRange (double center)
double GetInputRange (void)
double GetCalibratedInputRange (void)
double GetCalibratedTemperature (void)
double GetCalibratedFrequency (void)
int TransferWaves (int numberOfChannels=kNumberOfChipsMax *kNumberOfChannelsMax)
int TransferWaves (unsigned char *p, int numberOfChannels=kNumberOfChipsMax *kNumberOfChannelsMax)
int TransferWaves (int firstChannel, int lastChannel)
int TransferWaves (unsigned char *p, int firstChannel, int lastChannel)
int DecodeWave (unsigned char *waveforms, unsigned int chipIndex, unsigned char channel, unsigned short *waveform)
int DecodeWave (unsigned int chipIndex, unsigned char channel, unsigned short *waveform)
int GetWave (unsigned char *waveforms, unsigned int chipIndex, unsigned char channel, short *waveform, bool responseCalib=false, int triggerCell=-1, int wsr=-1, bool adjustToClock=false, float threshold=0, bool offsetCalib=true)
int GetWave (unsigned char *waveforms, unsigned int chipIndex, unsigned char channel, float *waveform, bool responseCalib=false, int triggerCell=-1, int wsr=-1, bool adjustToClock=false, float threshold=0, bool offsetCalib=true)
int GetWave (unsigned int chipIndex, unsigned char channel, short *waveform, bool responseCalib=false, int triggerCell=-1, int wsr=-1, bool adjustToClock=false, float threshold=0, bool offsetCalib=true)
int GetWave (unsigned int chipIndex, unsigned char channel, float *waveform, bool responseCalib, int triggerCell=-1, int wsr=-1, bool adjustToClock=false, float threshold=0, bool offsetCalib=true)
int GetWave (unsigned int chipIndex, unsigned char channel, float *waveform)
int GetRawWave (unsigned int chipIndex, unsigned char channel, unsigned short *waveform, bool adjustToClock=false)
int GetRawWave (unsigned char *waveforms, unsigned int chipIndex, unsigned char channel, unsigned short *waveform, bool adjustToClock=false)
bool IsTimingCalibrationValid (void)
bool IsVoltageCalibrationValid (void)
int GetTime (unsigned int chipIndex, int channelIndex, double freq, int tc, float *time, bool tcalibrated=true, bool rotated=true)
int GetTime (unsigned int chipIndex, int channelIndex, int tc, float *time, bool tcalibrated=true, bool rotated=true)
int GetTimeCalibration (unsigned int chipIndex, int channelIndex, int mode, float *time, bool force=false)
int GetTriggerCell (unsigned int chipIndex)
int GetStopCell (unsigned int chipIndex)
unsigned char GetStopWSR (unsigned int chipIndex)
int GetTriggerCell (unsigned char *waveforms, unsigned int chipIndex)
void TestDAC (int channel)
void MeasureSpeed ()
void InteractSpeed ()
void MonitorFrequency ()
int TestShift (int n)
int EnableAcal (int mode, double voltage)
int GetAcalMode ()
double GetAcalVolt ()
int EnableTcal (int freq, int level=0, int phase=0)
int SelectClockSource (int source)
int SetRefclk (int source)
int GetRefclk ()
int GetTcalFreq ()
int GetTcalLevel ()
int GetTcalPhase ()
int GetTcalSource ()
int SetCalibVoltage (double value)
int SetCalibTiming (int t1, int t2)
double GetTemperature ()
int Is2048ModeCapable ()
int GetTriggerBus ()
unsigned int GetScaler (int channel)
int ReadEEPROM (unsigned short page, void *buffer, int size)
int WriteEEPROM (unsigned short page, void *buffer, int size)
bool HasCorrectFirmware ()
int ConfigureLMK (double sampFreq, bool freqChange, int calFreq, int calPhase)
bool InitTimeCalibration (unsigned int chipIndex)
void SetCalibrationDirectory (const char *calibrationDirectoryPath)
void GetCalibrationDirectory (char *calibrationDirectoryPath)
ResponseCalibration * GetResponseCalibration () const
double GetPrecision () const
int CalibrateWaveform (unsigned int chipIndex, unsigned char channel, unsigned short *adcWaveform, short *waveform, bool responseCalib, int triggerCell, bool adjustToClock, float threshold, bool offsetCalib)
void ReadSingleWaveform (int nChips, int nChan, unsigned short wfu[kNumberOfChipsMax][kNumberOfChannelsMax][kNumberOfBins], bool rotated)
int AverageWaveforms (DRSCallback *pcb, int chipIndex, int nChan, int prog1, int prog2, unsigned short *awf, int n, bool rotated)
int RobustAverageWaveforms (DRSCallback *pcb, int chipIndex, int nChan, int prog1, int prog2, unsigned short *awf, int n, bool rotated)
int CalibrateVolt (DRSCallback *pcb)
int AnalyzePeriod (Averager *ave, int iIter, int nIter, int channel, float wf[kNumberOfBins], int tCell, double cellDV[kNumberOfBins], double cellDT[kNumberOfBins])
int AnalyzeSlope (Averager *ave, int iIter, int nIter, int channel, float wf[kNumberOfBins], int tCell, double cellDV[kNumberOfBins], double cellDT[kNumberOfBins])
int CalibrateTiming (DRSCallback *pcb)
Static Public Member Functions
static void LinearRegression (double *x, double *y, int n, double *a, double *b)
static void RemoveSymmetricSpikes (short **wf, int nwf, short diffThreshold, int spikeWidth, short maxPeakToPeak, short spikeVoltage, int nTimeRegionThreshold)
Public Attributes
unsigned int fDAC_COFSA
unsigned int fDAC_COFSB
unsigned int fDAC_DRA
unsigned int fDAC_DSA
unsigned int fDAC_TLEVEL
unsigned int fDAC_ACALIB
unsigned int fDAC_DSB
unsigned int fDAC_DRB
unsigned int fDAC_COFS
unsigned int fDAC_ADCOFS
unsigned int fDAC_CLKOFS
unsigned int fDAC_ROFS_1
unsigned int fDAC_ROFS_2
unsigned int fDAC_INOFS
unsigned int fDAC_BIAS
unsigned int fDAC_CMOFS
unsigned int fDAC_CALN
unsigned int fDAC_CALP
unsigned int fDAC_ONOFS
unsigned int fDAC_CMOFSP
unsigned int fDAC_CMOFSN
unsigned int fDAC_TLEVEL1
unsigned int fDAC_TLEVEL2
unsigned int fDAC_TLEVEL3
unsigned int fDAC_TLEVEL4
Protected Member Functions
void ConstructBoard ()
void ReadSerialNumber ()
void ReadCalibration (void)
TimeData * GetTimeCalibration (unsigned int chipIndex, bool reinit=false)
int GetStretchedTime (float *time, float *measurement, int numberOfMeasurements, float period)
Protected Attributes
int fDRSType
int fBoardType
int fNumberOfChips
int fNumberOfChannels
int fRequiredFirmwareVersion
int fFirmwareVersion
int fBoardSerialNumber
int fHasMultiBuffer
unsigned int fTransport
unsigned int fCtrlBits
int fNumberOfReadoutChannels
int fReadoutChannelConfig
int fADCClkPhase
bool fADCClkInvert
double fExternalClockFrequency
int fSlotNumber
double fNominalFrequency
double fTrueFrequency
double fTCALFrequency
double fRefClock
int fMultiBuffer
int fDominoMode
int fDominoActive
int fADCActive
int fChannelConfig
int fChannelCascading
int fChannelDepth
int fWSRLoop
int fReadoutMode
unsigned short fReadPointer
int fNMultiBuffer
int fTriggerEnable1
int fTriggerEnable2
int fTriggerSource
int fTriggerDelay
double fTriggerDelayNs
int fSyncDelay
int fDelayedStart
int fTranspMode
int fDecimation
unsigned short fStopCell [4]
unsigned char fStopWSR [4]
unsigned short fTriggerBus
double fROFS
double fRange
double fCommonMode
int fAcalMode
int fbkAcalMode
double fAcalVolt
double fbkAcalVolt
int fTcalFreq
int fbkTcalFreq
int fTcalLevel
int fbkTcalLevel
int fTcalPhase
int fTcalSource
int fRefclk
unsigned char fWaveforms [kNumberOfChipsMax *kNumberOfChannelsMax *2 *kNumberOfBins]
int fMaxChips
char fCalibDirectory [1000]
ResponseCalibration * fResponseCalibration
bool fVoltageCalibrationValid
double fCellCalibratedRange
double fCellCalibratedTemperature
unsigned short fCellOffset [kNumberOfChipsMax *kNumberOfChannelsMax][kNumberOfBins]
unsigned short fCellOffset2 [kNumberOfChipsMax *kNumberOfChannelsMax][kNumberOfBins]
double fCellGain [kNumberOfChipsMax *kNumberOfChannelsMax][kNumberOfBins]
double fTimingCalibratedFrequency
double fCellDT [kNumberOfChipsMax][kNumberOfChannelsMax][kNumberOfBins]
TimeData ** fTimeData
int fNumberOfTimeData
int fDebug
bool fWaveTransferred [kNumberOfChipsMax *kNumberOfChannelsMax]
int fTriggerStartBin
Constructor & Destructor Documentation
DRSBoard::~DRSBoard ()
References musb_close(), NULL, TR_USB, and TR_USB2.
Member Function Documentation
int DRSBoard::AnalyzePeriod (Averager * ave, int iIter, int nIter, int channel, float wf[kNumberOfBins], int tCell, double cellDV[kNumberOfBins], double cellDT[kNumberOfBins])
int DRSBoard::AnalyzeSlope (Averager * ave, int iIter, int nIter, int channel, float wf[kNumberOfBins], int tCell, double cellDV[kNumberOfBins], double cellDT[kNumberOfBins])
References Averager::Add(), kNumberOfBins, Averager::Median(), and Averager::RobustAverage().
int DRSBoard::AverageWaveforms (DRSCallback * pcb, int chipIndex, int nChan, int prog1, int prog2, unsigned short * awf, int n, bool rotated)
References center, kNumberOfBins, NULL, DRSCallback::Progress(), and swf.
int DRSBoard::CalibrateTiming (DRSCallback * pcb)
References BIT_REFCLK_SOURCE, BIT_TCAL_EN, kNumberOfBins, kNumberOfChannelsMax, kNumberOfChipsMax, NULL, DRSCallback::Progress(), TCALIB_METHOD, TCALIB_METHOD_V4, and TR_VME.
Referenced by main().
int DRSBoard::CalibrateVolt (DRSCallback * pcb)
References BIT_REFCLK_SOURCE, BIT_TCAL_EN, F1, idx, kNumberOfBins, NULL, DRSCallback::Progress(), Sleep(), TR_USB2, TR_VME, VCALIB_METHOD, VCALIB_METHOD_V4, wf1, wf2, wf3, and wft.
Referenced by main().
int DRSBoard::CalibrateWaveform (unsigned int chipIndex, unsigned char channel, unsigned short * adcWaveform, short * waveform, bool responseCalib, int triggerCell, bool adjustToClock, float threshold, bool offsetCalib)
References kNumberOfBins, kSuccess, and kZeroSuppression.
Referenced by ResponseCalibration::OffsetCalibrationV3().
int DRSBoard::Channel2Input (int channel) const inline
int DRSBoard::Channel2ReadoutChannel (int channel) const inline
int DRSBoard::ChipTest ()
References BIT_PLL_LOCKED0, and Sleep().
int DRSBoard::ConfigureLMK (double sampFreq, bool freqChange, int calFreq, int calPhase)
References BIT_REFCLK_SOURCE, BIT_SERIAL_BUSY, REG_LMK_LSB, REG_LMK_MSB, REG_STATUS, T_CTRL, T_STATUS, and TR_USB2.
void DRSBoard::ConstructBoard () protected
References BIT_ADCCLK_INVERT, BIT_CONFIG_DMODE, BIT_DACTIVE, BIT_DMODE, BIT_ENABLE_TRIGGER1, BIT_ENABLE_TRIGGER2, BIT_MULTI_BUFFER, BIT_READOUT_MODE, BIT_TR_SOURCE1, BIT_TR_SOURCE2, kNumberOfChipsMax, REG_CHANNEL_MODE, REG_MAGIC, REG_READ_POINTER, T_CTRL, and T_STATUS.
int DRSBoard::Debug () inline
Referenced by ResponseCalibration::FitCalibrationPointsV4(), ResponseCalibration::OffsetCalibrationV4(), and ResponseCalibration::RecordCalibrationPointsV4().
int DRSBoard::DecodeWave (unsigned char * waveforms, unsigned int chipIndex, unsigned char channel, unsigned short * waveform)
References kInvalidTransport, kNumberOfBins, kSuccess, TR_USB, TR_USB2, and TR_VME.
int DRSBoard::DecodeWave (unsigned int chipIndex, unsigned char channel, unsigned short * waveform)
int DRSBoard::EnableAcal (int mode, double voltage)
References BIT_ACAL_EN, REG_CTRL, and T_CTRL.
Referenced by ResponseCalibration::CalibrationStart(), ResponseCalibration::CalibrationTrigger(), ResponseCalibration::OffsetCalibrationV3(), ResponseCalibration::OffsetCalibrationV4(), ResponseCalibration::RecordCalibrationPointsV3(), and ResponseCalibration::RecordCalibrationPointsV4().
int DRSBoard::EnableTcal (int freq, int level = 0, int phase = 0)
References BIT_ACAL_EN, BIT_NEG_TRIGGER, BIT_TCAL_EN, BIT_TCAL_SOURCE, REG_CTRL, and T_CTRL.
Referenced by main(), and xml_readsettings().
int DRSBoard::EnableTrigger (int flag1, int flag2)
References BIT_ENABLE_TRIGGER1, BIT_ENABLE_TRIGGER2, REG_CTRL, and T_CTRL.
Referenced by main(), and xml_readsettings().
int DRSBoard::FinishClearCycle ()
double DRSBoard::FreqToVolt (double freq)
int DRSBoard::GetAcalMode () inline
double DRSBoard::GetAcalVolt () inline
int DRSBoard::GetBoardSerialNumber () const inline
Referenced by main(), ResponseCalibration::ReadCalibrationV3(), ResponseCalibration::ReadCalibrationV4(), ResponseCalibration::WriteCalibrationV3(), and ResponseCalibration::WriteCalibrationV4().
int DRSBoard::GetBoardType () const inline
Referenced by main(), and xml_readsettings().
double DRSBoard::GetCalibratedFrequency (void) inline
References kNumberOfChannelsMax, and kNumberOfChipsMax.
double DRSBoard::GetCalibratedInputRange (void) inline
double DRSBoard::GetCalibratedTemperature (void) inline
void DRSBoard::GetCalibrationDirectory (char * calibrationDirectoryPath)
Referenced by ResponseCalibration::ReadCalibrationV3(), ResponseCalibration::ReadCalibrationV4(), ResponseCalibration::WriteCalibrationV3(), and ResponseCalibration::WriteCalibrationV4().
int DRSBoard::GetChannelCascading () const inline
int DRSBoard::GetChannelDepth () const inline
int DRSBoard::GetClockChannel () const inline
int DRSBoard::GetClockInput () const inline
unsigned short DRSBoard::GetConfigReg (void)
References REG_CONFIG, and T_CTRL.
unsigned int DRSBoard::GetCtrlReg (void)
References REG_CTRL, and T_CTRL.
int DRSBoard::GetDecimation () inline
int DRSBoard::GetDRSType () const inline
Referenced by ResponseCalibration::Calibrate(), ResponseCalibration::FitCalibrationPoints(), ResponseCalibration::OffsetCalibration(), ResponseCalibration::ReadCalibration(), ResponseCalibration::ReadCalibrationV3(), ResponseCalibration::ReadCalibrationV4(), ResponseCalibration::RecordCalibrationPoints(), ResponseCalibration::SubtractADCOffset(), and ResponseCalibration::WriteCalibration().
double DRSBoard::GetExternalClockFrequency ()
int DRSBoard::GetFirmwareVersion () const inline
Referenced by main().
double DRSBoard::GetInputRange (void) inline
int DRSBoard::GetMultiBufferRP (void)
int DRSBoard::GetMultiBufferWP (void)
References REG_WRITE_POINTER, and T_STATUS.
double DRSBoard::GetNominalFrequency () const inline
Referenced by ResponseCalibration::ReadCalibrationV3(), ResponseCalibration::ReadCalibrationV4(), ResponseCalibration::WriteCalibrationV3(), and ResponseCalibration::WriteCalibrationV4().
int DRSBoard::GetNumberOfCalibInputs () const inline
int DRSBoard::GetNumberOfChannels () const inline
int DRSBoard::GetNumberOfChips () const inline
int DRSBoard::GetNumberOfInputs () const inline
int DRSBoard::GetNumberOfReadoutChannels () const inline
double DRSBoard::GetPrecision () const inline
References ResponseCalibration::GetPrecision(), kNumberOfBins, and kNumberOfChipsMax.
int DRSBoard::GetRawWave (unsigned int chipIndex, unsigned char channel, unsigned short * waveform, bool adjustToClock = false)
Referenced by ResponseCalibration::OffsetCalibrationV3(), ResponseCalibration::OffsetCalibrationV4(), ResponseCalibration::RecordCalibrationPointsV3(), and ResponseCalibration::RecordCalibrationPointsV4().
int DRSBoard::GetRawWave (unsigned char * waveforms, unsigned int chipIndex, unsigned char channel, unsigned short * waveform, bool adjustToClock = false)
References kNumberOfBins.
int DRSBoard::GetReadoutChannelConfig () inline
int DRSBoard::GetRefclk () inline
int DRSBoard::GetRegulationDAC (double * value)
References REG_RDAC1, REG_RDAC3, and T_STATUS.
int DRSBoard::GetRequiredFirmwareVersion () const inline
ResponseCalibration* DRSBoard::GetResponseCalibration () const inline
unsigned int DRSBoard::GetScaler (int channel)
References REG_SCALER0, REG_SCALER1, REG_SCALER2, REG_SCALER3, REG_SCALER4, REG_SCALER5, T_STATUS, and TR_USB2.
int DRSBoard::GetSlotNumber () const inline
unsigned int DRSBoard::GetStatusReg (void)
References REG_STATUS, and T_STATUS.
int DRSBoard::GetStopCell (unsigned int chipIndex)
unsigned char DRSBoard::GetStopWSR (unsigned int chipIndex)
int DRSBoard::GetStretchedTime (float * time, float * measurement, int numberOfMeasurements, float period) protected
int DRSBoard::GetTcalFreq () inline
int DRSBoard::GetTcalLevel () inline
int DRSBoard::GetTcalPhase () inline
int DRSBoard::GetTcalSource () inline
double DRSBoard::GetTemperature ()
References REG_TEMPERATURE, and T_STATUS.
Referenced by main(), ResponseCalibration::RecordCalibrationPointsV3(), and ResponseCalibration::RecordCalibrationPointsV4().
int DRSBoard::GetTime (unsigned int chipIndex, int channelIndex, double freq, int tc, float * time, bool tcalibrated = true, bool rotated = true)
References DRSBoard::TimeData::FrequencyData::fBin, DRSBoard::TimeData::FrequencyData::fFrequency, DRSBoard::TimeData::fFrequency, DRSBoard::TimeData::fNumberOfFrequencies, kNumberOfBins, and NULL.
Referenced by main().
int DRSBoard::GetTime (unsigned int chipIndex, int channelIndex, int tc, float * time, bool tcalibrated = true, bool rotated = true)
References kNumberOfADCBins, and kNumberOfBins.
int DRSBoard::GetTimeCalibration (unsigned int chipIndex, int channelIndex, int mode, float * time, bool force = false)
References kNumberOfBins.
DRSBoard::TimeData * DRSBoard::GetTimeCalibration (unsigned int chipIndex, bool reinit = false) protected
References DRSBoard::TimeData::FrequencyData::fBin, DRSBoard::TimeData::fChip, DRSBoard::TimeData::FrequencyData::fFrequency, DRSBoard::TimeData::fFrequency, DRSBoard::TimeData::fNumberOfFrequencies, DRSBoard::TimeData::kMaxNumberOfFrequencies, kNumberOfBins, mxml_find_node(), mxml_free_tree(), mxml_get_value(), mxml_parse_file(), mxml_subnode(), and NULL.
int DRSBoard::GetTransport () const inline
int DRSBoard::GetTriggerBus ()
References kNumberOfBins, REG_TRIGGER_BUS, T_RAM, T_STATUS, and TR_VME.
int DRSBoard::GetTriggerCell (unsigned int chipIndex)
Referenced by main().
int DRSBoard::GetTriggerCell (unsigned char * waveforms, unsigned int chipIndex)
References kInvalidTriggerSignal, and kNumberOfBins.
int DRSBoard::GetTriggerChannel () const inline
int DRSBoard::GetTriggerDelay () inline
double DRSBoard::GetTriggerDelayNs () inline
int DRSBoard::GetTriggerEnable (int i) inline
int DRSBoard::GetTriggerInput () const inline
int DRSBoard::GetTriggerSource () inline
double DRSBoard::GetTrueFrequency ()
int DRSBoard::GetWave (unsigned char * waveforms, unsigned int chipIndex, unsigned char channel, short * waveform, bool responseCalib = false, int triggerCell = -1, int wsr = -1, bool adjustToClock = false, float threshold = 0, bool offsetCalib = true)
References kNumberOfBins, kSuccess, wf1, and wf2.
Referenced by main().
int DRSBoard::GetWave (unsigned char * waveforms, unsigned int chipIndex, unsigned char channel, float * waveform, bool responseCalib = false, int triggerCell = -1, int wsr = -1, bool adjustToClock = false, float threshold = 0, bool offsetCalib = true)
References kNumberOfBins.
int DRSBoard::GetWave (unsigned int chipIndex, unsigned char channel, short * waveform, bool responseCalib = false, int triggerCell = -1, int wsr = -1, bool adjustToClock = false, float threshold = 0, bool offsetCalib = true)
int DRSBoard::GetWave (unsigned int chipIndex, unsigned char channel, float * waveform, bool responseCalib, int triggerCell = -1, int wsr = -1, bool adjustToClock = false, float threshold = 0, bool offsetCalib = true)
int DRSBoard::GetWave (unsigned int chipIndex, unsigned char channel, float * waveform)
int DRSBoard::GetWaveformBufferSize () const inline
References kNumberOfBins.
bool DRSBoard::HasCorrectFirmware ()
int DRSBoard::HasMultiBuffer () const inline
void DRSBoard::IncrementMultiBufferRP (void)
int DRSBoard::Init ()
References BIT_FREQ_AUTO_ADJ, BIT_REINIT_TRIG, REG_CTRL, T_CTRL, and TR_USB2.
Referenced by main().
int DRSBoard::InitFPGA (void)
References BIT_SERIAL_BUSY, musb_write(), REG_STATUS, Sleep(), T_STATUS, and TR_USB2.
bool DRSBoard::InitTimeCalibration (unsigned int chipIndex)
References NULL.
int DRSBoard::Input2Channel (int input, int ind = 0) const inline
int DRSBoard::Input2ReadoutChannel (int input, int ind = 0) const inline
void DRSBoard::InteractSpeed ()
References Sleep().
int DRSBoard::Is2048ModeCapable ()
References BIT_2048_MODE, REG_STATUS, and T_STATUS.
int DRSBoard::IsBusy (void)
References BIT_RUNNING, REG_STATUS, and T_STATUS.
Referenced by ResponseCalibration::CalibrationStart(), ResponseCalibration::CalibrationTrigger(), main(), ResponseCalibration::OffsetCalibrationV3(), ResponseCalibration::OffsetCalibrationV4(), and ResponseCalibration::RecordCalibrationPointsV4().
bool DRSBoard::IsCalibChannel (int ch) const inline
bool DRSBoard::IsCalibInput (int input) const inline
int DRSBoard::IsEventAvailable (void)
int DRSBoard::IsLMKLocked (void)
References BIT_LMK_LOCKED, REG_STATUS, and T_STATUS.
int DRSBoard::IsMultiBuffer () inline
References center.
int DRSBoard::IsNewFreq (unsigned char chipIndex)
References BIT_NEW_FREQ1, BIT_NEW_FREQ2, REG_STATUS, and T_STATUS.
int DRSBoard::IsPLLLocked (void)
References BIT_PLL_LOCKED0, REG_STATUS, and T_STATUS.
bool DRSBoard::IsTimingCalibrationValid (void)
bool DRSBoard::IsVoltageCalibrationValid (void) inline
void DRSBoard::LinearRegression (double * x, double * y, int n, double * a, double * b) static
Referenced by ResponseCalibration::FitCalibrationPointsV4().
void DRSBoard::MeasureSpeed ()
References Sleep().
void DRSBoard::MonitorFrequency ()
References drs_kbhit(), REG_RDAC1, REG_RDAC3, Sleep(), and T_STATUS.
int DRSBoard::RAMTest (int flag)
References drs_kbhit(), getch(), MAX_N_BYTES, NULL, T_RAM, and TR_VME.
int DRSBoard::Read (int type, void * data, unsigned int addr, int size)
References musb_read(), musb_write(), T_CTRL, T_FIFO, T_RAM, T_STATUS, TR_USB, TR_USB2, TR_VME, and USB_TIMEOUT.
void DRSBoard::ReadCalibration (void) protected
References TCALIB_METHOD, TCALIB_METHOD_V4, VCALIB_METHOD, and VCALIB_METHOD_V4.
int DRSBoard::ReadDAC (unsigned char channel, double * value)
References REG_DAC_OFS, and T_CTRL.
int DRSBoard::ReadEEPROM (unsigned short page, void * buffer, int size)
References BIT_EEPROM_READ_TRIG, BIT_SERIAL_BUSY, REG_CTRL, REG_EEPROM_PAGE_EVAL, REG_EEPROM_PAGE_MEZZ, REG_STATUS, Sleep(), T_CTRL, T_RAM, and T_STATUS.
int DRSBoard::ReadFrequency (unsigned char chipIndex, double * f)
References REG_FREQ1, REG_FREQ2, REG_FREQ_SET, T_CTRL, and T_STATUS.
int DRSBoard::ReadoutChannel2Channel (int readout) const inline
int DRSBoard::ReadoutChannel2Input (int readout) const inline
void DRSBoard::ReadSerialNumber () protected
References REG_BOARD_TYPE, REG_MAGIC, REG_SERIAL_BOARD, REG_VERSION_FW, REQUIRED_FIRMWARE_VERSION_DRS2, REQUIRED_FIRMWARE_VERSION_DRS3, REQUIRED_FIRMWARE_VERSION_DRS4, T_STATUS, and TR_VME.
void DRSBoard::ReadSingleWaveform (int nChips, int nChan, unsigned short wfu[kNumberOfChipsMax][kNumberOfChannelsMax][kNumberOfBins], bool rotated)
References kNumberOfBins.
void DRSBoard::RegisterTest (void)
References N_REG, and T_CTRL.
int DRSBoard::RegulateFrequency (double freq)
References BIT_FREQ_AUTO_ADJ, REG_CTRL, REG_FREQ1, REG_FREQ_SET_HI, REG_FREQ_SET_LO, REG_RDAC1, REG_RDAC3, Sleep(), T_CTRL, and T_STATUS.
int DRSBoard::Reinit ()
References BIT_REINIT_TRIG, REG_CTRL, and T_CTRL.
Referenced by ResponseCalibration::CalibrationTrigger().
void DRSBoard::RemoveSymmetricSpikes (short ** wf, int nwf, short diffThreshold, int spikeWidth, short maxPeakToPeak, short spikeVoltage, int nTimeRegionThreshold) static
References kNumberOfBins, and kNumberOfChannelsMax.
void DRSBoard::ResetMultiBuffer (void)
int DRSBoard::RobustAverageWaveforms (DRSCallback * pcb, int chipIndex, int nChan, int prog1, int prog2, unsigned short * awf, int n, bool rotated)
References Averager::Add(), kNumberOfBins, NULL, DRSCallback::Progress(), Averager::RobustAverage(), Averager::SaveNormalizedDistribution(), and swf.
int DRSBoard::SelectClockSource (int source)
References BIT_TCAL_SOURCE, REG_CTRL, and T_CTRL.
void DRSBoard::SetADCClkPhase (int phase, bool invert)
References BIT_ADCCLK_INVERT, REG_ADCCLK_PHASE, REG_CTRL, and T_CTRL.
int DRSBoard::SetBoardSerialNumber (unsigned short serialNumber)
References BIT_EEPROM_WRITE_TRIG, REG_CTRL, REG_DAC0, Sleep(), T_CTRL, and T_RAM.
void DRSBoard::SetCalibrationDirectory (const char * calibrationDirectoryPath)
int DRSBoard::SetCalibTiming (int t1, int t2)
References REG_CALIB_TIMING, and T_CTRL.
int DRSBoard::SetCalibVoltage (double value)
Referenced by ResponseCalibration::OffsetCalibrationV3(), ResponseCalibration::OffsetCalibrationV4(), ResponseCalibration::RecordCalibrationPointsV3(), and ResponseCalibration::RecordCalibrationPointsV4().
int DRSBoard::SetChannelConfig (int firstChannel, int lastChannel, int nConfigChannels)
References kNumberOfBins, REG_CHANNEL_CONFIG, REG_CHANNEL_MODE, and T_CTRL.
void DRSBoard::SetCooldown (unsigned int ticks)
References REG_COOLDOWN, and T_CTRL.
int DRSBoard::SetDAC (unsigned char channel, double value)
References REG_DAC_OFS, and T_CTRL.
Referenced by ResponseCalibration::RecordCalibrationPointsV3().
void DRSBoard::SetDebug (int debug) inline
int DRSBoard::SetDecimation (int flag)
References BIT_DECIMATION, kNumberOfBins, REG_CTRL, and T_CTRL.
int DRSBoard::SetDelayedStart (int flag)
References BIT_DELAYED_START, REG_CTRL, and T_CTRL.
int DRSBoard::SetDelayedTrigger (int flag)
References BIT_TRIGGER_DELAYED, REG_CTRL, and T_CTRL.
int DRSBoard::SetDominoActive (unsigned char mode)
References BIT_DACTIVE, REG_CTRL, and T_CTRL.
int DRSBoard::SetDominoMode (unsigned char mode)
References BIT_DMODE, REG_CONFIG, REG_CTRL, and T_CTRL.
Referenced by ResponseCalibration::CalibrationStart(), and ResponseCalibration::RecordCalibrationPointsV4().
int DRSBoard::SetExternalClockFrequency (double frequencyMHz)
int DRSBoard::SetFrequency (double freq, bool wait)
References BIT_ENABLE_TRIGGER1, BIT_ENABLE_TRIGGER2, BIT_FREQ_AUTO_ADJ, BIT_LONG_START_PULSE, BIT_PLL_LOCKED0, REG_CTRL, REG_FREQ_SET, Sleep(), and T_CTRL.
Referenced by main(), and xml_readsettings().
int DRSBoard::SetIndividualTriggerLevel (int channel, double voltage)
Referenced by xml_readsettings().
int DRSBoard::SetInputRange (double center)
References center.
Referenced by main(), and xml_readsettings().
void DRSBoard::SetLED (int state)
References BIT_LED, REG_CTRL, and T_CTRL.
int DRSBoard::SetMultiBuffer (int flag)
References BIT_MULTI_BUFFER, REG_CTRL, and T_CTRL.
int DRSBoard::SetMultiBufferRP (unsigned short rp)
References REG_READ_POINTER, and T_CTRL.
void DRSBoard::SetNumberOfChannels (int nChannels)
int DRSBoard::SetReadoutMode (unsigned char mode)
References BIT_READOUT_MODE, REG_CTRL, and T_CTRL.
int DRSBoard::SetRefclk (int source)
References BIT_REFCLK_EXT, BIT_REFCLK_SOURCE, REG_CTRL, and T_CTRL.
int DRSBoard::SetStandbyMode (int flag)
References BIT_STANDBY_MODE, REG_CTRL, and T_CTRL.
int DRSBoard::SetSyncDelay (int ticks)
References REG_TRG_DELAY, and T_CTRL.
int DRSBoard::SetTranspMode (int flag)
References BIT_TRANSP_MODE, REG_CTRL, and T_CTRL.
Referenced by main(), and xml_readsettings().
int DRSBoard::SetTriggerDelayNs (int delay)
References REG_TRG_DELAY, and T_CTRL.
Referenced by main(), and xml_readsettings().
int DRSBoard::SetTriggerDelayPercent (int delay)
References REG_TRG_DELAY, and T_CTRL.
int DRSBoard::SetTriggerLevel (double value)
Referenced by main(), and xml_readsettings().
int DRSBoard::SetTriggerPolarity (bool negative)
References BIT_NEG_TRIGGER, REG_CTRL, and T_CTRL.
Referenced by main(), and xml_readsettings().
int DRSBoard::SetTriggerSource (int source)
References BIT_TR_SOURCE1, BIT_TR_SOURCE2, REG_CTRL, REG_TRG_CONFIG, and T_CTRL.
Referenced by main(), and xml_readsettings().
void DRSBoard::SetVoltageOffset (double offset1, double offset2)
References Sleep().
void DRSBoard::SetWarmup (unsigned int ticks)
References REG_WARMUP, and T_CTRL.
int DRSBoard::SoftTrigger (void)
References BIT_SOFT_TRIG, REG_CTRL, and T_CTRL.
Referenced by ResponseCalibration::CalibrationTrigger(), main(), ResponseCalibration::OffsetCalibrationV3(), ResponseCalibration::OffsetCalibrationV4(), and ResponseCalibration::RecordCalibrationPointsV4().
int DRSBoard::StartClearCycle ()
int DRSBoard::StartDomino ()
References BIT_START_TRIG, REG_CTRL, and T_CTRL.
Referenced by ResponseCalibration::CalibrationStart(), ResponseCalibration::CalibrationTrigger(), main(), ResponseCalibration::OffsetCalibrationV3(), ResponseCalibration::OffsetCalibrationV4(), and ResponseCalibration::RecordCalibrationPointsV4().
void DRSBoard::TestDAC (int channel)
References Sleep().
int DRSBoard::TestShift (int n)
int DRSBoard::TransferWaves (int numberOfChannels = kNumberOfChipsMax * kNumberOfChannelsMax)
Referenced by main(), ResponseCalibration::OffsetCalibrationV3(), ResponseCalibration::OffsetCalibrationV4(), ResponseCalibration::RecordCalibrationPointsV3(), and ResponseCalibration::RecordCalibrationPointsV4().
int DRSBoard::TransferWaves (unsigned char * p, int numberOfChannels = kNumberOfChipsMax * kNumberOfChannelsMax)
int DRSBoard::TransferWaves (int firstChannel, int lastChannel)
References kNumberOfBins, and TR_USB.
int DRSBoard::TransferWaves (unsigned char * p, int firstChannel, int lastChannel)
References kNumberOfBins, REG_STOP_CELL0, REG_STOP_CELL2, REG_STOP_WSR0, REG_TRIGGER_BUS, T_RAM, T_STATUS, TR_USB, TR_USB2, and TR_VME.
double DRSBoard::VoltToFreq (double volt)
int DRSBoard::Write (int type, unsigned int addr, void * data, int size)
References musb_read(), musb_write(), NULL, T_CTRL, T_FIFO, T_RAM, T_STATUS, TR_USB, TR_USB2, TR_VME, and USB_TIMEOUT.
int DRSBoard::WriteEEPROM (unsigned short page, void * buffer, int size)
References BIT_EEPROM_WRITE_TRIG, BIT_SERIAL_BUSY, REG_CTRL, REG_EEPROM_PAGE_EVAL, REG_EEPROM_PAGE_MEZZ, REG_STATUS, Sleep(), T_CTRL, T_RAM, and T_STATUS.
Member Data Documentation
int DRSBoard::fAcalMode protected
double DRSBoard::fAcalVolt protected
int DRSBoard::fADCActive protected
bool DRSBoard::fADCClkInvert protected
int DRSBoard::fADCClkPhase protected
int DRSBoard::fbkAcalMode protected
double DRSBoard::fbkAcalVolt protected
int DRSBoard::fbkTcalFreq protected
int DRSBoard::fbkTcalLevel protected
int DRSBoard::fBoardSerialNumber protected
int DRSBoard::fBoardType protected
char DRSBoard::fCalibDirectory[1000] protected
double DRSBoard::fCellCalibratedRange protected
double DRSBoard::fCellCalibratedTemperature protected
double DRSBoard::fCellDT[kNumberOfChipsMax][kNumberOfChannelsMax][kNumberOfBins] protected
double DRSBoard::fCellGain[kNumberOfChipsMax *kNumberOfChannelsMax][kNumberOfBins] protected
unsigned short DRSBoard::fCellOffset[kNumberOfChipsMax *kNumberOfChannelsMax][kNumberOfBins] protected
unsigned short DRSBoard::fCellOffset2[kNumberOfChipsMax *kNumberOfChannelsMax][kNumberOfBins] protected
int DRSBoard::fChannelCascading protected
int DRSBoard::fChannelConfig protected
int DRSBoard::fChannelDepth protected
double DRSBoard::fCommonMode protected
unsigned int DRSBoard::fCtrlBits protected
unsigned int DRSBoard::fDAC_ACALIB
unsigned int DRSBoard::fDAC_ADCOFS
unsigned int DRSBoard::fDAC_BIAS
unsigned int DRSBoard::fDAC_CALN
unsigned int DRSBoard::fDAC_CALP
unsigned int DRSBoard::fDAC_CLKOFS
Referenced by ResponseCalibration::RecordCalibrationPointsV3().
unsigned int DRSBoard::fDAC_CMOFS
unsigned int DRSBoard::fDAC_CMOFSN
unsigned int DRSBoard::fDAC_CMOFSP
unsigned int DRSBoard::fDAC_COFS
unsigned int DRSBoard::fDAC_COFSA
unsigned int DRSBoard::fDAC_COFSB
unsigned int DRSBoard::fDAC_DRA
unsigned int DRSBoard::fDAC_DRB
unsigned int DRSBoard::fDAC_DSA
unsigned int DRSBoard::fDAC_DSB
unsigned int DRSBoard::fDAC_INOFS
unsigned int DRSBoard::fDAC_ONOFS
unsigned int DRSBoard::fDAC_ROFS_1
unsigned int DRSBoard::fDAC_ROFS_2
unsigned int DRSBoard::fDAC_TLEVEL
unsigned int DRSBoard::fDAC_TLEVEL1
unsigned int DRSBoard::fDAC_TLEVEL2
unsigned int DRSBoard::fDAC_TLEVEL3
unsigned int DRSBoard::fDAC_TLEVEL4
int DRSBoard::fDebug protected
int DRSBoard::fDecimation protected
int DRSBoard::fDelayedStart protected
int DRSBoard::fDominoActive protected
int DRSBoard::fDominoMode protected
int DRSBoard::fDRSType protected
double DRSBoard::fExternalClockFrequency protected
int DRSBoard::fFirmwareVersion protected
int DRSBoard::fHasMultiBuffer protected
int DRSBoard::fMaxChips protected
int DRSBoard::fMultiBuffer protected
int DRSBoard::fNMultiBuffer protected
double DRSBoard::fNominalFrequency protected
int DRSBoard::fNumberOfChannels protected
int DRSBoard::fNumberOfChips protected
int DRSBoard::fNumberOfReadoutChannels protected
int DRSBoard::fNumberOfTimeData protected
double DRSBoard::fRange protected
int DRSBoard::fReadoutChannelConfig protected
int DRSBoard::fReadoutMode protected
unsigned short DRSBoard::fReadPointer protected
int DRSBoard::fRefclk protected
double DRSBoard::fRefClock protected
int DRSBoard::fRequiredFirmwareVersion protected
ResponseCalibration* DRSBoard::fResponseCalibration protected
double DRSBoard::fROFS protected
int DRSBoard::fSlotNumber protected
unsigned short DRSBoard::fStopCell[4] protected
unsigned char DRSBoard::fStopWSR[4] protected
int DRSBoard::fSyncDelay protected
int DRSBoard::fTcalFreq protected
double DRSBoard::fTCALFrequency protected
int DRSBoard::fTcalLevel protected
int DRSBoard::fTcalPhase protected
int DRSBoard::fTcalSource protected
TimeData** DRSBoard::fTimeData protected
double DRSBoard::fTimingCalibratedFrequency protected
int DRSBoard::fTranspMode protected
unsigned int DRSBoard::fTransport protected
unsigned short DRSBoard::fTriggerBus protected
int DRSBoard::fTriggerDelay protected
double DRSBoard::fTriggerDelayNs protected
int DRSBoard::fTriggerEnable1 protected
int DRSBoard::fTriggerEnable2 protected
int DRSBoard::fTriggerSource protected
int DRSBoard::fTriggerStartBin protected
double DRSBoard::fTrueFrequency protected
bool DRSBoard::fVoltageCalibrationValid protected
unsigned char DRSBoard::fWaveforms[kNumberOfChipsMax *kNumberOfChannelsMax *2 *kNumberOfBins] protected
bool DRSBoard::fWaveTransferred[kNumberOfChipsMax *kNumberOfChannelsMax] protected
int DRSBoard::fWSRLoop protected
The documentation for this class was generated from the following files:
/data/Software/DAQ/PDAQ/Core/Include/DRS.h
/data/Software/DAQ/PDAQ/Core/Source/DRS.cpp