ScalerManager Class Reference
ScalerManager Class Reference
#include <ScalerManager.h>
Public Member Functions
ScalerManager ()
virtual ~ScalerManager ()
int Init ()
void SetDiscAddress (string address)
void SetCrateHandle (int handle)
void SetCycles (int cycles)
void SetRate (int rate)
void SetScalerActive (int active)
void SetActive (int active)
int GetActive ()
void SetPath (string path)
int ReadMultipleCycles ()
Public Member Functions inherited from Common
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
int error (char *node)
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
Common ()
string GetTime ()
int GetUnixTime ()
string GetDayYear ()
string GetDay ()
Additional Inherited Members
Protected Attributes inherited from Common
string Message
Constructor & Destructor Documentation
ScalerManager::ScalerManager ()
ScalerManager::~ScalerManager () virtual
Member Function Documentation
int ScalerManager::GetActive () inline
Referenced by main().
int ScalerManager::Init ()
References KRED, and RESET.
Referenced by main().
int ScalerManager::ReadMultipleCycles ()
References IOManager::FillContainer(), Common::get_time(), getch(), KGRN, KRED, RESET, and IOManager::SaveContainer().
Referenced by main().
void ScalerManager::SetActive (int active)
Referenced by xml_readsettings().
void ScalerManager::SetCrateHandle (int handle) inline
Referenced by main().
void ScalerManager::SetCycles (int cycles) inline
Referenced by xml_readsettings().
void ScalerManager::SetDiscAddress (string address)
Referenced by xml_readsettings().
void ScalerManager::SetPath (string path) inline
Referenced by xml_readsettings().
void ScalerManager::SetRate (int rate) inline
Referenced by xml_readsettings().
void ScalerManager::SetScalerActive (int active) inline
Referenced by xml_readsettings().
The documentation for this class was generated from the following files:
/data/Software/DAQ/Scaler/Core/Include/ScalerManager.h
/data/Software/DAQ/Scaler/Core/Source/ScalerManager.cpp