DiscriminatorManager Class Reference
DiscriminatorManager Class Reference
#include <DiscriminatorManager.h>
Public Member Functions
DiscriminatorManager ()
virtual ~DiscriminatorManager ()
int Init ()
void SetTreshold (u_int32_t tresh)
int FillThresholds (string tresholdFile)
int SetThresholdsDisc (int Nthr)
void SetDiscAddress (string address)
void SetCrateHandle (int handle)
int GetNthresholds ()
Constructor & Destructor Documentation
DiscriminatorManager::DiscriminatorManager ()
DiscriminatorManager::~DiscriminatorManager () virtual
Member Function Documentation
int DiscriminatorManager::FillThresholds (string tresholdFile)
References KRED, and RESET.
Referenced by xml_readsettings().
int DiscriminatorManager::GetNthresholds () inline
Referenced by main().
int DiscriminatorManager::Init ()
References KRED, and RESET.
Referenced by main().
void DiscriminatorManager::SetCrateHandle (int handle) inline
Referenced by main().
void DiscriminatorManager::SetDiscAddress (string address)
Referenced by xml_readsettings().
int DiscriminatorManager::SetThresholdsDisc (int Nthr)
References KGRN, KRED, and RESET.
Referenced by main().
void DiscriminatorManager::SetTreshold (u_int32_t tresh)
Referenced by xml_readsettings().
The documentation for this class was generated from the following files:
/data/Software/DAQ/Scaler/Core/Include/DiscriminatorManager.h
/data/Software/DAQ/Scaler/Core/Source/DiscriminatorManager.cpp