Common Class Reference
Common Class Reference
#include <common.h>
Public Member Functions
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
int error (char *node)
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
Common ()
string GetTime ()
int GetUnixTime ()
string GetDayYear ()
string GetDay ()
Protected Attributes
string Message
Constructor & Destructor Documentation
Common::Common ()
Common::~Common () virtual
Common::Common ()
virtual Common::~Common () virtual
Common::Common ()
Member Function Documentation
int Common::error (char * node)
References KRED, and RESET.
Referenced by ADCManager1720::Init(), ADCManager1724::Init(), ADCManager1730::Init(), StorageManager::SaveContainer(), ScopeManager::ShowEvent(), and SlowcontrolManager::ShowStatus().
int32_t Common::get_time ()
Referenced by ScalerManager::ReadMultipleCycles().
int32_t Common::get_time ()
string Common::GetDay ()
string Common::GetDayYear ()
string Common::GetTime ()
void Common::gettimestring (char * buffer)
void Common::gettimestring (char * buffer)
References NULL.
Referenced by IOManager::IOManager(), SlowcontrolManager::ProcessInput(), and SlowcontrolManager::SlowcontrolManager().
int Common::GetUnixTime ()
int Common::GetUnixTime ()
int Common::GetUnixTime ()
References NULL.
Referenced by IOManager::FillContainer(), and StorageManager::FillContainer().
Member Data Documentation
string Common::Message protected
The documentation for this class was generated from the following files:
/data/Software/DAQ/CDAQ/Plugins/Include/common.h
/data/Software/DAQ/CDAQ/Plugins/Source/common.cpp