IOManager Class Reference
IOManager Class Reference
#include <IOManager.h>
Public Member Functions
IOManager ()
IOManager (string path)
virtual ~IOManager ()
void FillContainer (vector< int > &channel, vector< double > &rates)
void SaveContainer ()
Public Member Functions inherited from Common
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
int error (char *node)
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
Common ()
string GetTime ()
int GetUnixTime ()
string GetDayYear ()
string GetDay ()
Additional Inherited Members
Protected Attributes inherited from Common
string Message
Constructor & Destructor Documentation
IOManager::IOManager ()
IOManager::IOManager (string path)
References Common::gettimestring(), KGRN, and RESET.
IOManager::~IOManager () virtual
Member Function Documentation
void IOManager::FillContainer (vector< int > & channel, vector< double > & rates)
References Common::GetUnixTime(), KCYN, and RESET.
Referenced by ScalerManager::ReadMultipleCycles().
void IOManager::SaveContainer ()
Referenced by ScalerManager::ReadMultipleCycles().
The documentation for this class was generated from the following files:
/data/Software/DAQ/Scaler/IO/Include/IOManager.h
/data/Software/DAQ/Scaler/IO/Source/IOManager.cpp