StorageManager Class Reference
StorageManager Class Reference
#include <StorageManager.h>
Public Member Functions
StorageManager ()
virtual ~StorageManager ()
int Init ()
int InitROOT ()
void SetBuffer (u_int32_t *adcBuffer)
void SetEventLength (int length)
void SetTransferedBytes (int bytes)
void SetXMLFile (char *file)
void SetFolderName (char *file)
int GetNumberEvents ()
int GetEventsPerFile ()
int FillContainer ()
int SaveContainer ()
int NewFile ()
Public Member Functions inherited from Common
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
int error (char *node)
Common ()
virtual ~Common ()
int32_t get_time ()
int GetUnixTime ()
void gettimestring (char *buffer)
Common ()
string GetTime ()
int GetUnixTime ()
string GetDayYear ()
string GetDay ()
Additional Inherited Members
Protected Attributes inherited from Common
string Message
Constructor & Destructor Documentation
StorageManager::StorageManager ()
StorageManager::~StorageManager () virtual
Member Function Documentation
int StorageManager::FillContainer ()
References CORRECTION, and Common::GetUnixTime().
Referenced by main().
int StorageManager::GetEventsPerFile () inline
References wf1, wf2, and wf3.
Referenced by main().
int StorageManager::GetNumberEvents () inline
Referenced by main().
int StorageManager::Init ()
References InitROOT(), KGRN, KYEL, and RESET.
Referenced by main().
int StorageManager::InitROOT ()
Referenced by Init().
int StorageManager::NewFile ()
Referenced by main().
int StorageManager::SaveContainer ()
References Common::error(), XMLNode::getChildNode(), XMLNode::getText(), and XMLNode::openFileHelper().
Referenced by main().
void StorageManager::SetBuffer (u_int32_t * adcBuffer) inline
Referenced by main().
void StorageManager::SetEventLength (int length) inline
Referenced by main().
void StorageManager::SetFolderName (char * file) inline
Referenced by main().
void StorageManager::SetTransferedBytes (int bytes) inline
void StorageManager::SetXMLFile (char * file) inline
Referenced by main().
The documentation for this class was generated from the following files:
/data/Software/DAQ/CDAQ/Core/Include/StorageManager.h
/data/Software/DAQ/CDAQ/Core/Source/StorageManager.cpp