DAQContainer Class Reference
DAQContainer Class Reference
#include <DAQContainer.h>
Public Member Functions
DAQContainer ()
~DAQContainer ()
void SetGraphicMode ()
void SetCalibrationMode ()
bool GetGraphicMode ()
bool GetCalibrationMode ()
void SetOutputDir (const char *input)
std::string GetOutputDir ()
void SetNumberOfEvents (const int number)
int GetNumberOfEvens ()
void SetSaveType (const int type)
int GetSaveType ()
void SetNumberPerFile (const int numberfile)
int GetNumberPerFile ()
void SetTriggerRate (const int rate)
int GetTriggerRate ()
void SetGraphicModeType (const int gmode)
int GetGraphicModeType ()
void SetGraphicYHigh (const int yhigh)
int GetGraphicYHigh ()
void SetGraphicYLow (const int ylow)
int GetGraphicYLow ()
void SetTriggerType (const int Trigger)
int GetTriggerType ()
void SetChannel0 (const int Chn0)
void SetChannel1 (const int Chn1)
void SetChannel2 (const int Chn2)
void SetChannel3 (const int Chn3)
int GetChannel0 ()
int GetChannel1 ()
int GetChannel2 ()
int GetChannel3 ()
Constructor & Destructor Documentation
DAQContainer::DAQContainer ()
DAQContainer::~DAQContainer () inline
Member Function Documentation
bool DAQContainer::GetCalibrationMode () inline
Referenced by main().
int DAQContainer::GetChannel0 () inline
Referenced by main().
int DAQContainer::GetChannel1 () inline
Referenced by main().
int DAQContainer::GetChannel2 () inline
Referenced by main().
int DAQContainer::GetChannel3 () inline
Referenced by main().
bool DAQContainer::GetGraphicMode () inline
Referenced by main().
int DAQContainer::GetGraphicModeType () inline
int DAQContainer::GetGraphicYHigh () inline
Referenced by main().
int DAQContainer::GetGraphicYLow () inline
Referenced by main().
int DAQContainer::GetNumberOfEvens () inline
Referenced by main().
int DAQContainer::GetNumberPerFile () inline
std::string DAQContainer::GetOutputDir () inline
Referenced by main().
int DAQContainer::GetSaveType () inline
Referenced by main().
int DAQContainer::GetTriggerRate () inline
Referenced by main().
int DAQContainer::GetTriggerType () inline
Referenced by main().
void DAQContainer::SetCalibrationMode () inline
Referenced by main().
void DAQContainer::SetChannel0 (const int Chn0) inline
Referenced by xml_readsettings().
void DAQContainer::SetChannel1 (const int Chn1) inline
Referenced by xml_readsettings().
void DAQContainer::SetChannel2 (const int Chn2) inline
Referenced by xml_readsettings().
void DAQContainer::SetChannel3 (const int Chn3) inline
Referenced by xml_readsettings().
void DAQContainer::SetGraphicMode () inline
Referenced by main().
void DAQContainer::SetGraphicModeType (const int gmode) inline
Referenced by xml_readsettings().
void DAQContainer::SetGraphicYHigh (const int yhigh) inline
Referenced by xml_readsettings().
void DAQContainer::SetGraphicYLow (const int ylow) inline
Referenced by xml_readsettings().
void DAQContainer::SetNumberOfEvents (const int number) inline
Referenced by xml_readsettings().
void DAQContainer::SetNumberPerFile (const int numberfile) inline
Referenced by xml_readsettings().
void DAQContainer::SetOutputDir (const char * input) inline
Referenced by xml_readsettings().
void DAQContainer::SetSaveType (const int type) inline
Referenced by xml_readsettings().
void DAQContainer::SetTriggerRate (const int rate) inline
Referenced by xml_readsettings().
void DAQContainer::SetTriggerType (const int Trigger) inline
Referenced by xml_readsettings().
The documentation for this class was generated from the following files:
/data/Software/DAQ/PDAQ/Core/Include/DAQContainer.h
/data/Software/DAQ/PDAQ/Core/Source/DAQContainer.cpp