ResponseCalibration Class Reference
ResponseCalibration Class Reference
#include <DRS.h>
Classes
class CalibrationData
Public Member Functions
ResponseCalibration (DRSBoard *board)
~ResponseCalibration ()
void SetCalibrationParameters (int numberOfPointsLowVolt, int numberOfPoints, int numberOfMode2Bins, int numberOfSamples, int numberOfGridPoints, int numberOfXConstPoints, int numberOfXConstGridPoints, double triggerFrequency, int showStatistics=0)
void ResetCalibration ()
bool RecordCalibrationPoints (int chipNumber)
bool RecordCalibrationPointsV3 (int chipNumber)
bool RecordCalibrationPointsV4 (int chipNumber)
bool FitCalibrationPoints (int chipNumber)
bool FitCalibrationPointsV3 (int chipNumber)
bool FitCalibrationPointsV4 (int chipNumber)
bool OffsetCalibration (int chipNumber)
bool OffsetCalibrationV3 (int chipNumber)
bool OffsetCalibrationV4 (int chipNumber)
double GetTemperature (unsigned int chipIndex)
bool WriteCalibration (unsigned int chipIndex)
bool WriteCalibrationV3 (unsigned int chipIndex)
bool WriteCalibrationV4 (unsigned int chipIndex)
bool ReadCalibration (unsigned int chipIndex)
bool ReadCalibrationV3 (unsigned int chipIndex)
bool ReadCalibrationV4 (unsigned int chipIndex)
bool Calibrate (unsigned int chipIndex, unsigned int channel, unsigned short *adcWaveform, short *uWaveform, int triggerCell, float threshold, bool offsetCalib)
bool SubtractADCOffset (unsigned int chipIndex, unsigned int channel, unsigned short *adcWaveform, unsigned short *adcCalibratedWaveform, unsigned short newBaseLevel)
bool IsRead (int chipIndex) const
double GetPrecision () const
double GetOffsetAt (int chip, int chn, int bin) const
double GetGainAt (int chip, int chn, int bin) const
double GetMeasPointXAt (int ip) const
double GetMeasPointYAt (int ip) const
Protected Member Functions
void InitFields (int numberOfPointsLowVolt, int numberOfPoints, int numberOfMode2Bins, int numberOfSamples, int numberOfGridPoints, int numberOfXConstPoints, int numberOfXConstGridPoints, double triggerFrequency, int showStatistics)
void DeleteFields ()
void CalibrationTrigger (int mode, double voltage)
void CalibrationStart (double voltage)
Static Protected Member Functions
static float GetValue (float *coefficients, float u, int n)
static int Approx (float *p, float *uu, int np, int nu, float *coef)
static void LeastSquaresAccumulation (float **matrix, int nb, int *ip, int *ir, int mt, int jt)
static int LeastSquaresSolving (float **matrix, int nb, int ip, int ir, float *x, int n)
static void Housholder (int lpivot, int l1, int m, float **u, int iU1, int iU2, float *up, float **c, int iC1, int iC2, int ice, int ncv)
static int MakeDir (const char *path)
static void Average (int method, float *samples, int numberOfSamples, float &mean, float &error, float sigmaBoundary)
Protected Attributes
DRSBoard * fBoard
double fPrecision
bool fInitialized
bool fRecorded
bool fFitted
bool fOffset
bool fCalibrationValid [2]
int fNumberOfPointsLowVolt
int fNumberOfPoints
int fNumberOfMode2Bins
int fNumberOfSamples
int fNumberOfGridPoints
int fNumberOfXConstPoints
int fNumberOfXConstGridPoints
double fTriggerFrequency
int fShowStatistics
FILE * fCalibFile
int fCurrentLowVoltPoint
int fCurrentPoint
int fCurrentSample
int fCurrentFitChannel
int fCurrentFitBin
float * fResponseX [10][kNumberOfBins]
float * fResponseY
unsigned short ** fWaveFormMode3 [10]
unsigned short ** fWaveFormMode2 [10]
short ** fWaveFormOffset [10]
unsigned short ** fWaveFormOffsetADC [10]
unsigned short * fSamples
int * fSampleUsed
float * fPntX [2]
float * fPntY [2]
float * fUValues [2]
float * fRes [kNumberOfBins]
float * fResX [kNumberOfBins]
double * fXXFit
double * fYYFit
double * fWWFit
double * fYYFitRes
double * fYYSave
double * fXXSave
double fGainMin
double fGainMax
float ** fStatisticsApprox
float ** fStatisticsApproxExt
CalibrationData * fCalibrationData [kNumberOfChipsMax]
Constructor & Destructor Documentation
ResponseCalibration::ResponseCalibration (DRSBoard * board)
References fCalibrationData, fCalibrationValid, ResponseCalibration::CalibrationData::fIntRevers, kBSplineOrder, kNumberOfChipsMax, and NULL.
ResponseCalibration::~ResponseCalibration ()
References DeleteFields(), fCalibrationData, ResponseCalibration::CalibrationData::fIntRevers, kBSplineOrder, and kNumberOfChipsMax.
Member Function Documentation
int ResponseCalibration::Approx (float * p, float * uu, int np, int nu, float * coef) static protected
References kBSplineOrder.
void ResponseCalibration::Average (int method, float * samples, int numberOfSamples, float & mean, float & error, float sigmaBoundary) static protected
bool ResponseCalibration::Calibrate (unsigned int chipIndex, unsigned int channel, unsigned short * adcWaveform, short * uWaveform, int triggerCell, float threshold, bool offsetCalib)
References DRS::fBoard, ResponseCalibration::CalibrationData::fBSplineLookUp, ResponseCalibration::CalibrationData::fBSplineOffsetLookUp, ResponseCalibration::CalibrationData::fChannel, ResponseCalibration::CalibrationData::CalibrationDataChannel::fData, ResponseCalibration::CalibrationData::CalibrationDataChannel::fGain, ResponseCalibration::CalibrationData::fHasOffsetCalibration, ResponseCalibration::CalibrationData::CalibrationDataChannel::fLimitGroup, ResponseCalibration::CalibrationData::CalibrationDataChannel::fLookUp, ResponseCalibration::CalibrationData::CalibrationDataChannel::fLookUpOffset, ResponseCalibration::CalibrationData::CalibrationDataChannel::fNumberOfLookUpPoints, ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffset, ResponseCalibration::CalibrationData::fRead, DRSBoard::GetDRSType(), kBSplineOrder, kNumberOfBins, kNumberOfCalibChannelsV3, kNumberOfCalibChannelsV4, and NULL.
void ResponseCalibration::CalibrationStart (double voltage) protected
References DRSBoard::EnableAcal(), DRS::fBoard, DRSBoard::IsBusy(), DRSBoard::SetDominoMode(), and DRSBoard::StartDomino().
void ResponseCalibration::CalibrationTrigger (int mode, double voltage) protected
References DRSBoard::EnableAcal(), DRS::fBoard, DRSBoard::IsBusy(), DRSBoard::Reinit(), DRSBoard::SoftTrigger(), and DRSBoard::StartDomino().
void ResponseCalibration::DeleteFields () protected
References kNumberOfBins, kNumberOfCalibChannelsV3, kNumberOfChipsMax, and NULL.
Referenced by ~ResponseCalibration().
bool ResponseCalibration::FitCalibrationPoints (int chipNumber)
References DRS::fBoard, and DRSBoard::GetDRSType().
bool ResponseCalibration::FitCalibrationPointsV3 (int chipNumber)
References ResponseCalibration::CalibrationData::DeletePreCalculatedBSpline(), ResponseCalibration::CalibrationData::fChannel, ResponseCalibration::CalibrationData::CalibrationDataChannel::fData, ResponseCalibration::CalibrationData::CalibrationDataChannel::fLimitGroup, ResponseCalibration::CalibrationData::CalibrationDataChannel::fLookUp, ResponseCalibration::CalibrationData::CalibrationDataChannel::fLookUpOffset, ResponseCalibration::CalibrationData::fMax, ResponseCalibration::CalibrationData::fMin, ResponseCalibration::CalibrationData::fNumberOfLimitGroups, ResponseCalibration::CalibrationData::CalibrationDataChannel::fNumberOfLookUpPoints, ResponseCalibration::CalibrationData::CalibrationDataChannel::fTempData, kBSplineXMinOffset, kNumberOfBins, kNumberOfCalibChannelsV3, and ResponseCalibration::CalibrationData::PreCalculateBSpline().
bool ResponseCalibration::FitCalibrationPointsV4 (int chipNumber)
References DRSBoard::Debug(), DRS::fBoard, ResponseCalibration::CalibrationData::fChannel, ResponseCalibration::CalibrationData::CalibrationDataChannel::fGain, ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffset, kNumberOfBins, kNumberOfCalibChannelsV4, and DRSBoard::LinearRegression().
double ResponseCalibration::GetGainAt (int chip, int chn, int bin) const inline
References ResponseCalibration::CalibrationData::fChannel, and ResponseCalibration::CalibrationData::CalibrationDataChannel::fGain.
double ResponseCalibration::GetMeasPointXAt (int ip) const inline
double ResponseCalibration::GetMeasPointYAt (int ip) const inline
double ResponseCalibration::GetOffsetAt (int chip, int chn, int bin) const inline
References ResponseCalibration::CalibrationData::fChannel, and ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffset.
double ResponseCalibration::GetPrecision () const inline
Referenced by DRSBoard::GetPrecision().
double ResponseCalibration::GetTemperature (unsigned int chipIndex)
References NULL.
float ResponseCalibration::GetValue (float * coefficients, float u, int n) static protected
References kBSplineOrder.
void ResponseCalibration::Housholder (int lpivot, int l1, int m, float ** u, int iU1, int iU2, float * up, float ** c, int iC1, int iC2, int ice, int ncv) static protected
void ResponseCalibration::InitFields (int numberOfPointsLowVolt, int numberOfPoints, int numberOfMode2Bins, int numberOfSamples, int numberOfGridPoints, int numberOfXConstPoints, int numberOfXConstGridPoints, double triggerFrequency, int showStatistics) protected
References kNumberOfBins, kNumberOfCalibChannelsV3, and kNumberOfChipsMax.
bool ResponseCalibration::IsRead (int chipIndex) const inline
void ResponseCalibration::LeastSquaresAccumulation (float ** matrix, int nb, int * ip, int * ir, int mt, int jt) static protected
int ResponseCalibration::LeastSquaresSolving (float ** matrix, int nb, int ip, int ir, float * x, int n) static protected
int ResponseCalibration::MakeDir (const char * path) static protected
bool ResponseCalibration::OffsetCalibration (int chipNumber)
References DRS::fBoard, and DRSBoard::GetDRSType().
bool ResponseCalibration::OffsetCalibrationV3 (int chipNumber)
References DRSBoard::CalibrateWaveform(), DRSBoard::EnableAcal(), DRS::fBoard, ResponseCalibration::CalibrationData::fChannel, ResponseCalibration::CalibrationData::fHasOffsetCalibration, ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffset, ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffsetADC, DRSBoard::GetRawWave(), DRSBoard::IsBusy(), kNumberOfBins, kNumberOfCalibChannelsV3, millitime(), DRSBoard::SetCalibVoltage(), DRSBoard::SoftTrigger(), DRSBoard::StartDomino(), and DRSBoard::TransferWaves().
bool ResponseCalibration::OffsetCalibrationV4 (int chipNumber)
References DRSBoard::Debug(), DRSBoard::EnableAcal(), DRS::fBoard, ResponseCalibration::CalibrationData::fChannel, ResponseCalibration::CalibrationData::fHasOffsetCalibration, ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffset, DRSBoard::GetRawWave(), DRSBoard::IsBusy(), kNumberOfBins, kNumberOfCalibChannelsV3, kNumberOfCalibChannelsV4, DRSBoard::SetCalibVoltage(), Sleep(), DRSBoard::SoftTrigger(), DRSBoard::StartDomino(), and DRSBoard::TransferWaves().
bool ResponseCalibration::ReadCalibration (unsigned int chipIndex)
References DRS::fBoard, and DRSBoard::GetDRSType().
bool ResponseCalibration::ReadCalibrationV3 (unsigned int chipIndex)
References ResponseCalibration::CalibrationData::DeletePreCalculatedBSpline(), DRS::fBoard, ResponseCalibration::CalibrationData::fChannel, ResponseCalibration::CalibrationData::CalibrationDataChannel::fData, ResponseCalibration::CalibrationData::fEndTemperature, ResponseCalibration::CalibrationData::CalibrationDataChannel::fGain, ResponseCalibration::CalibrationData::fHasOffsetCalibration, ResponseCalibration::CalibrationData::CalibrationDataChannel::fLimitGroup, ResponseCalibration::CalibrationData::CalibrationDataChannel::fLookUp, ResponseCalibration::CalibrationData::CalibrationDataChannel::fLookUpOffset, ResponseCalibration::CalibrationData::fMax, ResponseCalibration::CalibrationData::fMin, ResponseCalibration::CalibrationData::fNumberOfGridPoints, ResponseCalibration::CalibrationData::fNumberOfLimitGroups, ResponseCalibration::CalibrationData::CalibrationDataChannel::fNumberOfLookUpPoints, ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffset, ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffsetADC, ResponseCalibration::CalibrationData::fRead, ResponseCalibration::CalibrationData::fStartTemperature, DRSBoard::GetBoardSerialNumber(), DRSBoard::GetCalibrationDirectory(), DRSBoard::GetDRSType(), DRSBoard::GetNominalFrequency(), kNumberOfBins, kNumberOfCalibChannelsV3, NULL, and ResponseCalibration::CalibrationData::PreCalculateBSpline().
bool ResponseCalibration::ReadCalibrationV4 (unsigned int chipIndex)
References DRS::fBoard, ResponseCalibration::CalibrationData::fChannel, ResponseCalibration::CalibrationData::fEndTemperature, ResponseCalibration::CalibrationData::CalibrationDataChannel::fGain, ResponseCalibration::CalibrationData::fHasOffsetCalibration, ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffset, ResponseCalibration::CalibrationData::fRead, ResponseCalibration::CalibrationData::fStartTemperature, DRSBoard::GetBoardSerialNumber(), DRSBoard::GetCalibrationDirectory(), DRSBoard::GetDRSType(), DRSBoard::GetNominalFrequency(), kNumberOfBins, kNumberOfCalibChannelsV4, and NULL.
bool ResponseCalibration::RecordCalibrationPoints (int chipNumber)
References DRS::fBoard, and DRSBoard::GetDRSType().
bool ResponseCalibration::RecordCalibrationPointsV3 (int chipNumber)
References DRSBoard::EnableAcal(), DRS::fBoard, DRSBoard::fDAC_CLKOFS, DRSBoard::GetRawWave(), DRSBoard::GetTemperature(), kNumberOfBins, kNumberOfCalibChannelsV3, DRSBoard::SetCalibVoltage(), DRSBoard::SetDAC(), and DRSBoard::TransferWaves().
bool ResponseCalibration::RecordCalibrationPointsV4 (int chipNumber)
References DRSBoard::Debug(), DRSBoard::EnableAcal(), DRS::fBoard, DRSBoard::GetRawWave(), DRSBoard::GetTemperature(), DRSBoard::IsBusy(), kNumberOfBins, kNumberOfCalibChannelsV4, DRSBoard::SetCalibVoltage(), DRSBoard::SetDominoMode(), Sleep(), DRSBoard::SoftTrigger(), DRSBoard::StartDomino(), and DRSBoard::TransferWaves().
void ResponseCalibration::ResetCalibration ()
References kNumberOfChipsMax.
void ResponseCalibration::SetCalibrationParameters (int numberOfPointsLowVolt, int numberOfPoints, int numberOfMode2Bins, int numberOfSamples, int numberOfGridPoints, int numberOfXConstPoints, int numberOfXConstGridPoints, double triggerFrequency, int showStatistics = 0)
bool ResponseCalibration::SubtractADCOffset (unsigned int chipIndex, unsigned int channel, unsigned short * adcWaveform, unsigned short * adcCalibratedWaveform, unsigned short newBaseLevel)
References DRS::fBoard, ResponseCalibration::CalibrationData::fChannel, ResponseCalibration::CalibrationData::fHasOffsetCalibration, ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffsetADC, ResponseCalibration::CalibrationData::fRead, DRSBoard::GetDRSType(), kNumberOfBins, kNumberOfCalibChannelsV3, kNumberOfCalibChannelsV4, and NULL.
bool ResponseCalibration::WriteCalibration (unsigned int chipIndex)
References DRS::fBoard, and DRSBoard::GetDRSType().
bool ResponseCalibration::WriteCalibrationV3 (unsigned int chipIndex)
References DRS::fBoard, ResponseCalibration::CalibrationData::fChannel, ResponseCalibration::CalibrationData::CalibrationDataChannel::fData, ResponseCalibration::CalibrationData::fEndTemperature, ResponseCalibration::CalibrationData::CalibrationDataChannel::fLimitGroup, ResponseCalibration::CalibrationData::CalibrationDataChannel::fLookUp, ResponseCalibration::CalibrationData::CalibrationDataChannel::fLookUpOffset, ResponseCalibration::CalibrationData::fMax, ResponseCalibration::CalibrationData::fMin, ResponseCalibration::CalibrationData::fNumberOfGridPoints, ResponseCalibration::CalibrationData::fNumberOfLimitGroups, ResponseCalibration::CalibrationData::CalibrationDataChannel::fNumberOfLookUpPoints, ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffset, ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffsetADC, ResponseCalibration::CalibrationData::fStartTemperature, DRSBoard::GetBoardSerialNumber(), DRSBoard::GetCalibrationDirectory(), DRSBoard::GetNominalFrequency(), kNumberOfBins, kNumberOfCalibChannelsV3, and NULL.
bool ResponseCalibration::WriteCalibrationV4 (unsigned int chipIndex)
References DRS::fBoard, ResponseCalibration::CalibrationData::fChannel, ResponseCalibration::CalibrationData::CalibrationDataChannel::fGain, ResponseCalibration::CalibrationData::CalibrationDataChannel::fOffset, DRSBoard::GetBoardSerialNumber(), DRSBoard::GetCalibrationDirectory(), DRSBoard::GetNominalFrequency(), kNumberOfBins, kNumberOfCalibChannelsV4, and NULL.
Member Data Documentation
DRSBoard* ResponseCalibration::fBoard protected
FILE* ResponseCalibration::fCalibFile protected
CalibrationData* ResponseCalibration::fCalibrationData[kNumberOfChipsMax] protected
Referenced by ResponseCalibration(), and ~ResponseCalibration().
bool ResponseCalibration::fCalibrationValid[2] protected
Referenced by ResponseCalibration().
int ResponseCalibration::fCurrentFitBin protected
int ResponseCalibration::fCurrentFitChannel protected
int ResponseCalibration::fCurrentLowVoltPoint protected
int ResponseCalibration::fCurrentPoint protected
int ResponseCalibration::fCurrentSample protected
bool ResponseCalibration::fFitted protected
double ResponseCalibration::fGainMax protected
double ResponseCalibration::fGainMin protected
bool ResponseCalibration::fInitialized protected
int ResponseCalibration::fNumberOfGridPoints protected
int ResponseCalibration::fNumberOfMode2Bins protected
int ResponseCalibration::fNumberOfPoints protected
int ResponseCalibration::fNumberOfPointsLowVolt protected
int ResponseCalibration::fNumberOfSamples protected
int ResponseCalibration::fNumberOfXConstGridPoints protected
int ResponseCalibration::fNumberOfXConstPoints protected
bool ResponseCalibration::fOffset protected
float* ResponseCalibration::fPntX[2] protected
float* ResponseCalibration::fPntY[2] protected
double ResponseCalibration::fPrecision protected
bool ResponseCalibration::fRecorded protected
float* ResponseCalibration::fRes[kNumberOfBins] protected
float* ResponseCalibration::fResponseX[10][kNumberOfBins] protected
float* ResponseCalibration::fResponseY protected
float* ResponseCalibration::fResX[kNumberOfBins] protected
unsigned short* ResponseCalibration::fSamples protected
int* ResponseCalibration::fSampleUsed protected
int ResponseCalibration::fShowStatistics protected
float** ResponseCalibration::fStatisticsApprox protected
float** ResponseCalibration::fStatisticsApproxExt protected
double ResponseCalibration::fTriggerFrequency protected
float* ResponseCalibration::fUValues[2] protected
unsigned short** ResponseCalibration::fWaveFormMode2[10] protected
unsigned short** ResponseCalibration::fWaveFormMode3[10] protected
short** ResponseCalibration::fWaveFormOffset[10] protected
unsigned short** ResponseCalibration::fWaveFormOffsetADC[10] protected
double* ResponseCalibration::fWWFit protected
double* ResponseCalibration::fXXFit protected
double* ResponseCalibration::fXXSave protected
double* ResponseCalibration::fYYFit protected
double* ResponseCalibration::fYYFitRes protected
double* ResponseCalibration::fYYSave protected
The documentation for this class was generated from the following files:
/data/Software/DAQ/PDAQ/Core/Include/DRS.h
/data/Software/DAQ/PDAQ/Core/Source/DRS.cpp