/data/Software/DAQ/XDAQ/Core/Source/control.cpp File Reference
control.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <sys/stat.h>
#include <unistd.h>
#include <sys/time.h>
#include "global.h"
#include "CAENVMElib.h"
#include "adc.h"
#include <TH1D.h>
#include <Riostream.h>
#include <TTree.h>
#include <TBranch.h>
#include <TROOT.h>
#include <TSystem.h>
#include <TFile.h>
#include <TCanvas.h>
Macros
#define KNRM "\x1B[0m"
#define KRED "\x1B[31m"
#define KGRN "\x1B[32m"
#define KYEL "\x1B[33m"
#define KBLU "\x1B[34m"
#define KMAG "\x1B[35m"
#define KCYN "\x1B[36m"
#define KWHT "\x1B[37m"
#define RESET "\033[0m"
Functions
int control_printlog (FILE *logfile, int time, char *text)
int32_t get_time ()
void col (char *str)
int control_log (FILE *file, int mode, char *s)
int errormsg (int flag, char *s)
int control_printtitle (char *SwRelease)
int control_scopehelp ()
int control_gettimestring (char *timestr, char format)
int control_openlog (FILE **logfile, char *FileName, char *SwRelease)
int control_cnts2log (FILE *logfile, scaler &s)
int control_cmdline (int argc, char *argv[], char *envp[], int &time, u_int32_t &NoE, var_graphics &graphics, int &baseline, digitizer &adc, char *OutFileName, char *XmlFileName)
int power (int base, int exponent)
int control_configfile (char *ConfigFileName, crate &crt, digitizer &adc, scaler &s, multipurposemodule &mp, int &WriteToFile)
int control_configbaseline (crate &crt, digitizer &adc)
int control_openfile (FILE **ofile, char *FileName, int &FileCounter, int WriteToFile, digitizer &adc, FILE *logfile)
int control_openrawrootfile (TFile **orootfile, TTree **t1, char *FileName, int &FileCounter, int WriteToFile, digitizer &adc, FILE *logfile, int wf0[], int wf1[], int wf2[], int wf3[], int wf4[], int wf5[], int wf6[], int wf7[], double &freq)
int control_scfile (int time, float average, int stopped)
int control_calcrate (timeandtrigger &t, scaler &s, int FileEvtCounter, double &freq)
int control_writedata (digitizer &adc, int i, FILE *ofile, int WriteToFile, int blt_bytes, u_int32_t *buff)
int control_writerootrawdata (digitizer &adc, int i, TFile *orootfile, TTree *t1, int WriteToFile, int blt_bytes, u_int32_t *buff, int wf0[], int wf1[], int wf2[], int wf3[], int wf4[], int wf5[], int wf6[], int wf7[], double &freq)
int control_generatefilename (char *OutFileName, char *path, int baseline)
int control_calctime (timeandtrigger &t, int32_t ms, char *text)
int control_setdefault (digitizer &adc, scaler &s, timeandtrigger &t, crate &crt, multipurposemodule &mp, var_graphics &g)
int control_getadc (digitizer &adc, int pmt, int &module, int &channel)
Variables
int sand =-1
int jul =1
char OutPutFolder [100] =""
Macro Definition Documentation
#define KBLU "\x1B[34m"
#define KCYN "\x1B[36m"
Referenced by control_calcrate(), and control_calctime().
#define KGRN "\x1B[32m"
Referenced by control_printtitle().
#define KMAG "\x1B[35m"
#define KNRM "\x1B[0m"
#define KRED "\x1B[31m"
Referenced by control_cmdline(), and errormsg().
#define KWHT "\x1B[37m"
#define KYEL "\x1B[33m"
Referenced by control_scopehelp().
#define RESET "\033[0m"
Referenced by control_calcrate(), control_calctime(), control_cmdline(), control_printtitle(), control_scopehelp(), and errormsg().
Function Documentation
void col (char * str)
References NULL.
Referenced by adc_analyzebaseline(), adc_getbaseline(), adc_mblt(), control_scopehelp(), graph_checkkey(), and main().
int control_calcrate (timeandtrigger & t, scaler & s, int FileEvtCounter, double & freq)
References control_scfile(), timeandtrigger::CurrentTime, timeandtrigger::DisplayTime, errormsg(), scaler::events, get_time(), KCYN, timeandtrigger::last_ave, timeandtrigger::last_totnb, timeandtrigger::last_tottrg, timeandtrigger::MeasSeconds, NO_DATA_TIME, timeandtrigger::PreviousTime, RESET, timeandtrigger::store10, scaler::timecnt, timeandtrigger::totnb, and timeandtrigger::tottrg.
Referenced by main().
int control_calctime (timeandtrigger & t, int32_t ms, char * text)
References KCYN, timeandtrigger::MeasSeconds, and RESET.
Referenced by main().
int control_cmdline (int argc, char * argv[], char * envp[], int & time, u_int32_t & NoE, var_graphics & graphics, int & baseline, digitizer & adc, char * OutFileName, char * XmlFileName)
References digitizer::BoardInfo, var_graphics::channel, control_gettimestring(), control_scopehelp(), errormsg(), jul, KRED, var_graphics::module, var_graphics::on, OutPutFolder, var_graphics::pmtNb, RESET, and sand.
Referenced by main().
int control_cnts2log (FILE * logfile, scaler & s)
References scaler::cnt, control_gettimestring(), control_printlog(), scaler::deadcnt, scaler::deadtime, scaler::lifecnt, scaler::lifetime, scaler::old, scaler::stop, scaler::totalcnt, and scaler::totaltime.
int control_configbaseline (crate & crt, digitizer & adc)
References adc_writereg(), BlockOrganizationReg, ChannelConfigReg, and digitizer::NumberOfADCs.
Referenced by main().
int control_configfile (char * ConfigFileName, crate & crt, digitizer & adc, scaler & s, multipurposemodule & mp, int & WriteToFile)
References ADC_MAX, adc_writereg(), digitizer::Address, digitizer::BltSize, digitizer::BoardInfo, digitizer::Crate, CRATE_MAX, errormsg(), crate::handle, digitizer::Id, digitizer::mask, NULL, digitizer::NumberOfADCs, crate::NumberOfCrates, digitizer::pmt, digitizer::pmtmax, power(), and digitizer::TriggerLatency.
Referenced by main().
int control_generatefilename (char * OutFileName, char * path, int baseline)
References control_gettimestring(), errormsg(), FILE_ID, jul, and OutPutFolder.
Referenced by main().
int control_getadc (digitizer & adc, int pmt, int & module, int & channel)
References ADC_MAX, and digitizer::pmt.
Referenced by adc_analyzebaseline(), graph_checkkey(), main(), and xml_readsettings().
int control_gettimestring (char * timestr, char format)
References NULL, and sand.
Referenced by adc_analyzebaseline(), adc_getbaseline(), control_cmdline(), control_cnts2log(), control_generatefilename(), control_openlog(), control_printlog(), and control_scfile().
int control_log (FILE * file, int mode, char * s)
References control_printlog().
Referenced by errormsg(), and main().
int control_openfile (FILE ** ofile, char * FileName, int & FileCounter, int WriteToFile, digitizer & adc, FILE * logfile)
References control_printlog(), errormsg(), digitizer::NbSamplesEvt, NULL, digitizer::NumberOfADCs, and digitizer::ZLE.
Referenced by main().
int control_openlog (FILE ** logfile, char * FileName, char * SwRelease)
References control_gettimestring(), errormsg(), and NULL.
Referenced by main().
int control_openrawrootfile (TFile ** orootfile, TTree ** t1, char * FileName, int & FileCounter, int WriteToFile, digitizer & adc, FILE * logfile, int wf0[], int wf1[], int wf2[], int wf3[], int wf4[], int wf5[], int wf6[], int wf7[], double & freq)
References digitizer::channel, control_printlog(), errormsg(), digitizer::EventLength, and NULL.
int control_printlog (FILE * logfile, int time, char * text)
References control_gettimestring().
Referenced by control_cnts2log(), control_log(), control_openfile(), control_openrawrootfile(), and main().
int control_printtitle (char * SwRelease)
References KGRN, and RESET.
Referenced by main().
int control_scfile (int time, float average, int stopped)
References control_gettimestring(), errormsg(), NULL, and SC_FILENAME.
Referenced by control_calcrate(), and main().
int control_scopehelp ()
References col(), KYEL, and RESET.
Referenced by control_cmdline(), and graph_checkkey().
int control_setdefault (digitizer & adc, scaler & s, timeandtrigger & t, crate & crt, multipurposemodule & mp, var_graphics & g)
References ADC_MAX, digitizer::baseline, digitizer::BltSize, digitizer::busy, scaler::deadcnt, scaler::deadtime, timeandtrigger::DisplayTime, multipurposemodule::HEVeto, scaler::lifecnt, scaler::lifetime, digitizer::mask, digitizer::NumberOfADCs, crate::NumberOfCrates, digitizer::pmt, digitizer::pmtmax, scaler::scalertime, scaler::totalcnt, scaler::totaltime, digitizer::TriggerLatency, var_graphics::x_autorange, var_graphics::x_display, var_graphics::x_high, var_graphics::x_low, var_graphics::y_display, var_graphics::y_high, and var_graphics::y_low.
Referenced by main().
int control_writedata (digitizer & adc, int i, FILE * ofile, int WriteToFile, int blt_bytes, u_int32_t * buff)
References FILLER, and digitizer::Id.
Referenced by main().
int control_writerootrawdata (digitizer & adc, int i, TFile * orootfile, TTree * t1, int WriteToFile, int blt_bytes, u_int32_t * buff, int wf0[], int wf1[], int wf2[], int wf3[], int wf4[], int wf5[], int wf6[], int wf7[], double & freq)
References digitizer::channel, and digitizer::EventLength.
int errormsg (int flag, char * s)
References control_log(), KRED, and RESET.
Referenced by adc_analyzebaseline(), adc_closecrates(), adc_getbaseline(), adc_mblt(), adc_readreg(), adc_writereg(), control_calcrate(), control_cmdline(), control_configfile(), control_generatefilename(), control_openfile(), control_openlog(), control_openrawrootfile(), control_scfile(), graph_checkkey(), graph_display(), main(), sigproc(), xml_error(), xml_readsettings(), and xml_storefile().
int32_t get_time ()
Referenced by control_calcrate(), and main().
int power (int base, int exponent)
Referenced by control_configfile().
Variable Documentation
int jul =1
Referenced by control_cmdline(), and control_generatefilename().
char OutPutFolder[100] =""
Referenced by control_cmdline(), and control_generatefilename().
int sand =-1
Referenced by control_cmdline(), and control_gettimestring().