/data/Software/DAQ/XDAQ/GUI/Source/graph.cpp File Reference
graph.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <sys/stat.h>
#include <unistd.h>
#include <sys/time.h>
#include "global.h"
#include "control.h"
#include <Riostream.h>
#include <TH1D.h>
#include <TApplication.h>
#include <TCanvas.h>
#include <TStyle.h>
#include <TFile.h>
#include <TLatex.h>
Functions
int graph_init (TApplication *theApp, TCanvas *win, TH1D *g, var_graphics &graphics)
int graph_display (TH1D *g, u_int32_t *buff, int channel)
int graph_displayNoZLE (TH1D *g, u_int32_t *buff, int channel)
int graph_edit (TH1D *g, var_graphics &graphics, digitizer &adc)
int graph_checkkey (var_graphics &graphics, digitizer &adc, char c, TH1D *g, char *OutFileName)
Function Documentation
int graph_checkkey (var_graphics & graphics, digitizer & adc, char c, TH1D * g, char * OutFileName)
References var_graphics::channel, col(), control_getadc(), control_scopehelp(), errormsg(), var_graphics::module, digitizer::NbSamplesEvt, NULL, digitizer::NumberOfADCs, digitizer::pmt, digitizer::pmtmax, var_graphics::pmtNb, var_graphics::x_display, var_graphics::x_high, var_graphics::x_low, var_graphics::y_display, var_graphics::y_high, and var_graphics::y_low.
Referenced by main(), and ScopeManager::SetChannelTresh().
int graph_display (TH1D * g, u_int32_t * buff, int channel)
References errormsg().
Referenced by main().
int graph_displayNoZLE (TH1D * g, u_int32_t * buff, int channel)
Referenced by main().
int graph_edit (TH1D * g, var_graphics & graphics, digitizer & adc)
References digitizer::EventLength, var_graphics::x_autorange, var_graphics::x_display, var_graphics::x_high, var_graphics::x_low, var_graphics::y_display, var_graphics::y_high, and var_graphics::y_low.
Referenced by main(), and ScopeManager::SetChannelNumber().
int graph_init (TApplication * theApp, TCanvas * win, TH1D * g, var_graphics & graphics)
References var_graphics::channel, var_graphics::module, and var_graphics::pmtNb.
Referenced by main().