var hierarchy =
[
    [ "ADCManager", "class_a_d_c_manager.xhtml", [
      [ "ADCManager1720", "class_a_d_c_manager1720.xhtml", null ],
      [ "ADCManager1724", "class_a_d_c_manager1724.xhtml", null ],
      [ "ADCManager1730", "class_a_d_c_manager1730.xhtml", null ]
    ] ],
    [ "ALLXMLClearTag", "struct_a_l_l_x_m_l_clear_tag.xhtml", null ],
    [ "Averager", "class_averager.xhtml", null ],
    [ "ResponseCalibration::CalibrationData", "class_response_calibration_1_1_calibration_data.xhtml", null ],
    [ "ResponseCalibration::CalibrationData::CalibrationDataChannel", "class_response_calibration_1_1_calibration_data_1_1_calibration_data_channel.xhtml", null ],
    [ "Common", "class_common.xhtml", [
      [ "ADCManager1720", "class_a_d_c_manager1720.xhtml", null ],
      [ "ADCManager1724", "class_a_d_c_manager1724.xhtml", null ],
      [ "ADCManager1730", "class_a_d_c_manager1730.xhtml", null ],
      [ "IOManager", "class_i_o_manager.xhtml", null ],
      [ "ScalerManager", "class_scaler_manager.xhtml", null ],
      [ "ScopeManager", "class_scope_manager.xhtml", null ],
      [ "SlowcontrolManager", "class_slowcontrol_manager.xhtml", null ],
      [ "StorageManager", "class_storage_manager.xhtml", null ]
    ] ],
    [ "crate", "structcrate.xhtml", null ],
    [ "DAQContainer", "class_d_a_q_container.xhtml", null ],
    [ "digitizer", "structdigitizer.xhtml", null ],
    [ "DiscriminatorManager", "class_discriminator_manager.xhtml", null ],
    [ "DRS", "class_d_r_s.xhtml", null ],
    [ "DRSBoard", "class_d_r_s_board.xhtml", null ],
    [ "DRSCallback", "class_d_r_s_callback.xhtml", null ],
    [ "DRSBoard::TimeData::FrequencyData", "class_d_r_s_board_1_1_time_data_1_1_frequency_data.xhtml", null ],
    [ "multipurposemodule", "structmultipurposemodule.xhtml", null ],
    [ "mxml_struct", "structmxml__struct.xhtml", null ],
    [ "MXML_WRITER", "struct_m_x_m_l___w_r_i_t_e_r.xhtml", null ],
    [ "NextToken", "struct_next_token.xhtml", null ],
    [ "ResponseCalibration", "class_response_calibration.xhtml", null ],
    [ "scaler", "structscaler.xhtml", null ],
    [ "timeandtrigger", "structtimeandtrigger.xhtml", null ],
    [ "DRSBoard::TimeData", "class_d_r_s_board_1_1_time_data.xhtml", null ],
    [ "ToXMLStringTool", "struct_to_x_m_l_string_tool.xhtml", null ],
    [ "var_graphics", "structvar__graphics.xhtml", null ],
    [ "VMEManager", "class_v_m_e_manager.xhtml", null ],
    [ "XML", "struct_x_m_l.xhtml", null ],
    [ "XMLAttribute", "struct_x_m_l_attribute.xhtml", null ],
    [ "XMLCharacterEntity", "struct_x_m_l_character_entity.xhtml", null ],
    [ "XMLClear", "struct_x_m_l_clear.xhtml", null ],
    [ "XMLNode", "struct_x_m_l_node.xhtml", null ],
    [ "XMLNodeContents", "struct_x_m_l_node_contents.xhtml", null ],
    [ "XMLParserBase64Tool", "struct_x_m_l_parser_base64_tool.xhtml", null ],
    [ "XMLResults", "struct_x_m_l_results.xhtml", null ]
];