/data/Software/DAQ/XDAQ/Application/miniDAX.cpp File Reference
miniDAX.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <math.h>
#include <sys/stat.h>
#include <sys/types.h>
#include "global.h"
#include "keyb.h"
#include "CAENVMElib.h"
#include "control.h"
#include "adc.h"
#include "xml.h"
#include "graph.h"
#include <signal.h>
#include <sstream>
#include <iostream>
#include <TApplication.h>
#include <TCanvas.h>
#include <TH1D.h>
#include <TStyle.h>
#include <TGraph.h>
#include <TTree.h>
#include <TBranch.h>
#include <TFile.h>
Macros
#define KNRM "\x1B[0m"
#define KRED "\x1B[31m"
#define KGRN "\x1B[32m"
#define KYEL "\x1B[33m"
#define KBLU "\x1B[34m"
#define KMAG "\x1B[35m"
#define KCYN "\x1B[36m"
#define KWHT "\x1B[37m"
#define RESET "\033[0m"
Functions
void sigproc (int sig)
int main (int argc, char *argv[], char *envp[])
Macro Definition Documentation
#define KBLU "\x1B[34m"
#define KCYN "\x1B[36m"
#define KGRN "\x1B[32m"
Referenced by main().
#define KMAG "\x1B[35m"
#define KNRM "\x1B[0m"
#define KRED "\x1B[31m"
#define KWHT "\x1B[37m"
#define KYEL "\x1B[33m"
Referenced by main().
#define RESET "\033[0m"
Referenced by main().
Function Documentation
int main (int argc, char * argv[], char * envp[])
References adc_analyzebaseline(), adc_closecrates(), adc_enable(), adc_getbaseline(), adc_init(), ADC_MAX, adc_mblt(), digitizer::BltSize, digitizer::BoardInfo, digitizer::BufferSize, var_graphics::channel, col(), control_calcrate(), control_calctime(), control_cmdline(), control_configbaseline(), control_configfile(), control_generatefilename(), control_getadc(), control_log(), control_openfile(), control_openlog(), control_openrawrootfile(), control_printlog(), control_printtitle(), control_scfile(), control_setdefault(), control_writedata(), control_writerootrawdata(), errormsg(), digitizer::EventLength, digitizer::ExpectedEvSize, get_time(), getch(), graph_checkkey(), graph_display(), graph_displayNoZLE(), graph_edit(), graph_init(), crate::handle, KGRN, KYEL, timeandtrigger::last_ave, timeandtrigger::last_totnb, timeandtrigger::last_tottrg, timeandtrigger::MeasSeconds, var_graphics::module, NULL, digitizer::NumberOfADCs, var_graphics::on, var_graphics::pmtNb, timeandtrigger::PreviousTime, RESET, sigproc(), timeandtrigger::store10, timeandtrigger::totnb, timeandtrigger::tottrg, wf1, wf2, wf3, xml_readsettings(), xml_storefile(), and digitizer::ZLE.
void sigproc (int sig)
References errormsg().
Referenced by main().