/data/Software/DAQ/PDAQ/Core/Source/musbstd.c File Reference
musbstd.c File Reference
#include <stdio.h>
#include <assert.h>
#include <musbstd.h>
Functions
int musb_open (MUSB_INTERFACE **musb_interface, int vendor, int product, int instance, int configuration, int usbinterface)
int musb_set_altinterface (MUSB_INTERFACE *musb_interface, int index)
int musb_close (MUSB_INTERFACE *musb_interface)
int musb_write (MUSB_INTERFACE *musb_interface, int endpoint, const void *buf, int count, int timeout)
int musb_read (MUSB_INTERFACE *musb_interface, int endpoint, void *buf, int count, int timeout)
int musb_reset (MUSB_INTERFACE *musb_interface)
int musb_get_device (MUSB_INTERFACE *usb_interface)
Function Documentation
int musb_close (MUSB_INTERFACE * musb_interface)
References musb_reset().
Referenced by DRS::DRS(), and DRSBoard::~DRSBoard().
int musb_get_device (MUSB_INTERFACE * usb_interface)
Referenced by DRS::DRS().
int musb_open (MUSB_INTERFACE ** musb_interface, int vendor, int product, int instance, int configuration, int usbinterface)
References FALSE, MUSB_ACCESS_ERROR, MUSB_NOT_FOUND, MUSB_SUCCESS, NULL, and TRUE.
Referenced by DRS::DRS().
int musb_read (MUSB_INTERFACE * musb_interface, int endpoint, void * buf, int count, int timeout)
References FALSE, and NULL.
Referenced by DRS::DRS(), DRSBoard::Read(), and DRSBoard::Write().
int musb_reset (MUSB_INTERFACE * musb_interface)
References NULL.
Referenced by musb_close().
int musb_set_altinterface (MUSB_INTERFACE * musb_interface, int index)
int musb_write (MUSB_INTERFACE * musb_interface, int endpoint, const void * buf, int count, int timeout)
References NULL.
Referenced by DRS::DRS(), DRSBoard::InitFPGA(), DRSBoard::Read(), and DRSBoard::Write().