/data/Software/DAQ/PDAQ/Core/Include/musbstd.h File Reference
musbstd.h File Reference
Macros
#define MUSB_SUCCESS 1
#define MUSB_NOT_FOUND 2
#define MUSB_INVALID_PARAM 3
#define MUSB_NO_MEM 4
#define MUSB_ACCESS_ERROR 5
#define EXPRT
Functions
int EXPRT musb_open (MUSB_INTERFACE **musb_interface, int vendor, int product, int instance, int configuration, int usbinterface)
int EXPRT musb_close (MUSB_INTERFACE *musb_interface)
int EXPRT musb_write (MUSB_INTERFACE *musb_interface, int endpoint, const void *buf, int count, int timeout_ms)
int EXPRT musb_read (MUSB_INTERFACE *musb_interface, int endpoint, void *buf, int count, int timeout_ms)
int EXPRT musb_reset (MUSB_INTERFACE *musb_interface)
int EXPRT musb_set_altinterface (MUSB_INTERFACE *musb_interface, int index)
int EXPRT musb_get_device (MUSB_INTERFACE *musb_interface)
Macro Definition Documentation
#define EXPRT
#define MUSB_ACCESS_ERROR 5
Referenced by musb_open().
#define MUSB_INVALID_PARAM 3
#define MUSB_NO_MEM 4
#define MUSB_NOT_FOUND 2
Referenced by musb_open().
#define MUSB_SUCCESS 1
Referenced by DRS::DRS(), and musb_open().
Function Documentation
int EXPRT musb_close (MUSB_INTERFACE * musb_interface)
References musb_reset().
Referenced by DRS::DRS(), and DRSBoard::~DRSBoard().
int EXPRT musb_get_device (MUSB_INTERFACE * musb_interface)
Referenced by DRS::DRS().
int EXPRT musb_open (MUSB_INTERFACE ** musb_interface, int vendor, int product, int instance, int configuration, int usbinterface)
References FALSE, MUSB_ACCESS_ERROR, MUSB_NOT_FOUND, MUSB_SUCCESS, NULL, and TRUE.
Referenced by DRS::DRS().
int EXPRT musb_read (MUSB_INTERFACE * musb_interface, int endpoint, void * buf, int count, int timeout_ms)
References FALSE, and NULL.
Referenced by DRS::DRS(), DRSBoard::Read(), and DRSBoard::Write().
int EXPRT musb_reset (MUSB_INTERFACE * musb_interface)
References NULL.
Referenced by musb_close().
int EXPRT musb_set_altinterface (MUSB_INTERFACE * musb_interface, int index)
int EXPRT musb_write (MUSB_INTERFACE * musb_interface, int endpoint, const void * buf, int count, int timeout_ms)
References NULL.
Referenced by DRS::DRS(), DRSBoard::InitFPGA(), DRSBoard::Read(), and DRSBoard::Write().