/data/Software/DAQ/PDAQ/Core/Include/mxml.h File Reference
mxml.h File Reference
Classes
struct MXML_WRITER
struct mxml_struct
Macros
#define MXML_NAME_LENGTH 64
#define ELEMENT_NODE 1
#define TEXT_NODE 2
#define PROCESSING_INSTRUCTION_NODE 3
#define COMMENT_NODE 4
#define DOCUMENT_NODE 5
#define INTERNAL_ENTITY 0
#define EXTERNAL_ENTITY 1
#define MXML_MAX_ENTITY 500
#define MXML_MAX_CONDITION 10
#define DIR_SEPARATOR '/'
#define EXPRT
Typedefs
typedef struct mxml_struct * PMXML_NODE
typedef struct mxml_struct MXML_NODE
Functions
void mxml_suppress_date (int suppress)
MXML_WRITER * mxml_open_file (const char *file_name)
MXML_WRITER * mxml_open_buffer (void)
int mxml_set_translate (MXML_WRITER *writer, int flag)
int mxml_start_element (MXML_WRITER *writer, const char *name)
int mxml_start_element_noindent (MXML_WRITER *writer, const char *name)
int mxml_end_element (MXML_WRITER *writer)
int mxml_write_comment (MXML_WRITER *writer, const char *string)
int mxml_write_element (MXML_WRITER *writer, const char *name, const char *value)
int mxml_write_attribute (MXML_WRITER *writer, const char *name, const char *value)
int mxml_write_value (MXML_WRITER *writer, const char *value)
int mxml_write_empty_line (MXML_WRITER *writer)
char * mxml_close_buffer (MXML_WRITER *writer)
int mxml_close_file (MXML_WRITER *writer)
int mxml_get_number_of_children (PMXML_NODE pnode)
PMXML_NODE mxml_get_parent (PMXML_NODE pnode)
PMXML_NODE mxml_subnode (PMXML_NODE pnode, int idx)
PMXML_NODE mxml_find_node (PMXML_NODE tree, const char *xml_path)
int mxml_find_nodes (PMXML_NODE tree, const char *xml_path, PMXML_NODE **nodelist)
char * mxml_get_name (PMXML_NODE pnode)
char * mxml_get_value (PMXML_NODE pnode)
int mxml_get_line_number_start (PMXML_NODE pnode)
int mxml_get_line_number_end (PMXML_NODE pnode)
PMXML_NODE mxml_get_node_at_line (PMXML_NODE tree, int linenumber)
char * mxml_get_attribute (PMXML_NODE pnode, const char *name)
int mxml_add_attribute (PMXML_NODE pnode, const char *attrib_name, const char *attrib_value)
PMXML_NODE mxml_add_special_node (PMXML_NODE parent, int node_type, const char *node_name, const char *value)
PMXML_NODE mxml_add_special_node_at (PMXML_NODE parent, int node_type, const char *node_name, const char *value, int idx)
PMXML_NODE mxml_add_node (PMXML_NODE parent, const char *node_name, const char *value)
PMXML_NODE mxml_add_node_at (PMXML_NODE parent, const char *node_name, const char *value, int idx)
PMXML_NODE mxml_clone_tree (PMXML_NODE tree)
int mxml_add_tree (PMXML_NODE parent, PMXML_NODE tree)
int mxml_add_tree_at (PMXML_NODE parent, PMXML_NODE tree, int idx)
int mxml_replace_node_name (PMXML_NODE pnode, const char *new_name)
int mxml_replace_node_value (PMXML_NODE pnode, const char *value)
int mxml_replace_subvalue (PMXML_NODE pnode, const char *name, const char *value)
int mxml_replace_attribute_name (PMXML_NODE pnode, const char *old_name, const char *new_name)
int mxml_replace_attribute_value (PMXML_NODE pnode, const char *attrib_name, const char *attrib_value)
int mxml_delete_node (PMXML_NODE pnode)
int mxml_delete_attribute (PMXML_NODE, const char *attrib_name)
PMXML_NODE mxml_create_root_node (void)
PMXML_NODE mxml_parse_file (const char *file_name, char *error, int error_size, int *error_line)
PMXML_NODE mxml_parse_buffer (const char *buffer, char *error, int error_size, int *error_line)
int mxml_parse_entity (char **buf, const char *file_name, char *error, int error_size, int *error_line)
int mxml_write_tree (const char *file_name, PMXML_NODE tree)
void mxml_debug_tree (PMXML_NODE tree, int level)
void mxml_free_tree (PMXML_NODE tree)
void mxml_dirname (char *path)
void mxml_basename (char *path)
Macro Definition Documentation
#define COMMENT_NODE 4
Referenced by mxml_parse_buffer().
#define DIR_SEPARATOR '/'
Referenced by mxml_parse_entity().
#define DOCUMENT_NODE 5
Referenced by mxml_create_root_node().
#define ELEMENT_NODE 1
Referenced by mxml_add_node(), mxml_add_node_at(), and mxml_write_tree().
#define EXPRT
#define EXTERNAL_ENTITY 1
Referenced by mxml_parse_entity().
#define INTERNAL_ENTITY 0
Referenced by mxml_parse_entity().
#define MXML_MAX_CONDITION 10
Referenced by mxml_find_nodes1().
#define MXML_MAX_ENTITY 500
Referenced by mxml_parse_entity().
#define MXML_NAME_LENGTH 64
Referenced by mxml_add_attribute(), mxml_clone_tree(), mxml_debug_tree(), mxml_delete_attribute(), mxml_get_attribute(), mxml_replace_attribute_name(), mxml_replace_attribute_value(), and mxml_write_subtree().
#define PROCESSING_INSTRUCTION_NODE 3
Referenced by mxml_parse_buffer().
#define TEXT_NODE 2
Typedef Documentation
typedef struct mxml_struct MXML_NODE
typedef struct mxml_struct* PMXML_NODE
Function Documentation
int mxml_add_attribute (PMXML_NODE pnode, const char * attrib_name, const char * attrib_value)
add an attribute to an existing node
References mxml_struct::attribute_name, mxml_struct::attribute_value, mxml_malloc(), MXML_NAME_LENGTH, mxml_realloc(), mxml_struct::n_attributes, strlcpy(), and TRUE.
Referenced by mxml_clone_tree(), and mxml_parse_buffer().
PMXML_NODE mxml_add_node (PMXML_NODE parent, const char * node_name, const char * value)
write value of an XML element, like <[name]>[value]</[name]>
References ELEMENT_NODE, mxml_add_special_node_at(), and mxml_struct::n_children.
Referenced by mxml_parse_buffer().
PMXML_NODE mxml_add_node_at (PMXML_NODE parent, const char * node_name, const char * value, int idx)
add a subnode (child) to an existing parent node at the end
References ELEMENT_NODE, and mxml_add_special_node_at().
PMXML_NODE mxml_add_special_node (PMXML_NODE parent, int node_type, const char * node_name, const char * value)
add a subnode (child) to an existing parent node at the end
References mxml_add_special_node_at(), and mxml_struct::n_children.
Referenced by mxml_parse_buffer().
PMXML_NODE mxml_add_special_node_at (PMXML_NODE parent, int node_type, const char * node_name, const char * value, int idx)
add a subnode (child) to an existing parent node as a specific position
References mxml_struct::child, idx, mxml_malloc(), mxml_realloc(), mxml_struct::n_children, mxml_struct::name, mxml_struct::node_type, mxml_struct::parent, strlcpy(), and mxml_struct::value.
Referenced by mxml_add_node(), mxml_add_node_at(), and mxml_add_special_node().
int mxml_add_tree (PMXML_NODE parent, PMXML_NODE tree)
add a whole node tree to an existing parent node at the end
References mxml_add_tree_at(), and mxml_struct::n_children.
Referenced by mxml_clone_tree().
int mxml_add_tree_at (PMXML_NODE parent, PMXML_NODE tree, int idx)
add a whole node tree to an existing parent node at a specific position
References mxml_struct::child, idx, mxml_malloc(), mxml_realloc(), mxml_struct::n_children, mxml_struct::parent, and TRUE.
Referenced by mxml_add_tree().
void mxml_basename (char * path)
mxml_basename deletes any prefix ending with the last slash '/' character present in path. mxml_dirname deletes the filename portion, beginning with the last slash '/' character to the end of path. Followings are examples from these functions
path dirname basename "/" "/" "" "." "." "." "" "" "" "/test.txt" "/" "test.txt" "path/to/test.txt" "path/to" "test.txt" "test.txt "." "test.txt"
Under Windows, '\' and ':' are recognized ad separator too.
PMXML_NODE mxml_clone_tree (PMXML_NODE tree)
References mxml_struct::attribute_name, mxml_struct::attribute_value, mxml_struct::child, mxml_add_attribute(), mxml_add_tree(), MXML_NAME_LENGTH, mxml_replace_node_value(), mxml_subnode(), mxml_struct::n_attributes, mxml_struct::n_children, NULL, and mxml_struct::value.
char* mxml_close_buffer (MXML_WRITER * writer)
close a file opened with mxml_open_writer
References MXML_WRITER::buffer, MXML_WRITER::element_is_open, FALSE, MXML_WRITER::level, mxml_end_element(), mxml_free(), mxml_write_line(), and NULL.
int mxml_close_file (MXML_WRITER * writer)
close a file opened with mxml_open_writer
References MXML_WRITER::element_is_open, FALSE, MXML_WRITER::fh, MXML_WRITER::level, mxml_end_element(), mxml_free(), and mxml_write_line().
Referenced by mxml_write_tree().
PMXML_NODE mxml_create_root_node (void)
create root node of an XML tree
References DOCUMENT_NODE, mxml_struct::name, and mxml_struct::node_type.
Referenced by mxml_parse_buffer(), and mxml_parse_entity().
void mxml_debug_tree (PMXML_NODE tree, int level)
print XML tree for debugging
References mxml_struct::attribute_name, mxml_struct::attribute_value, mxml_struct::line_number_end, mxml_struct::line_number_start, MXML_NAME_LENGTH, mxml_struct::n_attributes, mxml_struct::name, mxml_struct::node_type, and mxml_struct::value.
int mxml_delete_attribute (PMXML_NODE , const char * attrib_name)
References mxml_struct::attribute_name, mxml_struct::attribute_value, FALSE, mxml_free(), MXML_NAME_LENGTH, mxml_realloc(), mxml_struct::n_attributes, and TRUE.
int mxml_delete_node (PMXML_NODE pnode)
free memory of a node and remove it from the parent's child list
References mxml_struct::child, mxml_free(), mxml_free_tree(), mxml_realloc(), mxml_struct::n_children, mxml_struct::parent, and TRUE.
void mxml_dirname (char * path)
Referenced by mxml_parse_entity().
int mxml_end_element (MXML_WRITER * writer)
close an open XML element
References MXML_WRITER::data_was_written, MXML_WRITER::element_is_open, FALSE, MXML_WRITER::level, mxml_free(), mxml_write_line(), MXML_WRITER::stack, strlcat(), and XML_INDENT.
Referenced by mxml_close_buffer(), mxml_close_file(), mxml_write_element(), and mxml_write_subtree().
PMXML_NODE mxml_find_node (PMXML_NODE tree, const char * xml_path)
Search for a specific XML node with a subset of XPATH specifications. Return first found node. For syntax see mxml_find_nodes()
References mxml_find_nodes(), mxml_free(), and NULL.
Referenced by DRSBoard::GetTimeCalibration().
int mxml_find_nodes (PMXML_NODE tree, const char * xml_path, PMXML_NODE ** nodelist)
References mxml_find_nodes1().
Referenced by mxml_find_node().
void mxml_free_tree (PMXML_NODE tree)
free memory of XML tree, must be called after any mxml_create_root_node() or mxml_parse_file()
References mxml_struct::attribute_name, mxml_struct::attribute_value, mxml_struct::child, mxml_free(), mxml_struct::n_attributes, mxml_struct::n_children, NULL, mxml_struct::parent, and mxml_struct::value.
Referenced by DRSBoard::GetTimeCalibration(), mxml_delete_node(), and read_error().
char* mxml_get_attribute (PMXML_NODE pnode, const char * name)
References mxml_struct::attribute_name, mxml_struct::attribute_value, MXML_NAME_LENGTH, mxml_struct::n_attributes, and NULL.
Referenced by mxml_find_nodes1().
int mxml_get_line_number_end (PMXML_NODE pnode)
References mxml_struct::line_number_end.
int mxml_get_line_number_start (PMXML_NODE pnode)
References mxml_struct::line_number_start.
char* mxml_get_name (PMXML_NODE pnode)
References mxml_struct::name.
PMXML_NODE mxml_get_node_at_line (PMXML_NODE tree, int line_number)
Retieve node at a certain line number
References mxml_struct::child, mxml_struct::line_number_start, mxml_struct::n_children, and NULL.
int mxml_get_number_of_children (PMXML_NODE pnode)
return number of subnodes (children) of a node
References mxml_struct::n_children.
PMXML_NODE mxml_get_parent (PMXML_NODE pnode)
References mxml_struct::parent.
char* mxml_get_value (PMXML_NODE pnode)
References mxml_struct::value.
Referenced by DRSBoard::GetTimeCalibration().
MXML_WRITER* mxml_open_buffer (void)
open a memory buffer and write XML header
References MXML_WRITER::buffer, MXML_WRITER::buffer_len, MXML_WRITER::buffer_size, MXML_WRITER::element_is_open, MXML_WRITER::level, mxml_malloc(), mxml_suppress_date_flag, mxml_write_line(), and MXML_WRITER::translate.
MXML_WRITER* mxml_open_file (const char * file_name)
open a file and write XML header
References MXML_WRITER::element_is_open, MXML_WRITER::fh, MXML_WRITER::level, mxml_free(), mxml_malloc(), mxml_suppress_date_flag, mxml_write_line(), NULL, O_TEXT, and MXML_WRITER::translate.
Referenced by mxml_write_tree().
PMXML_NODE mxml_parse_buffer (const char * buf, char * error, int error_size, int * error_line)
Parse a XML buffer and convert it into a tree of MXML_NODE's. Return NULL in case of an error, return error description. Optional file_name is used for error reporting if called from mxml_parse_file()
References COMMENT_NODE, FALSE, HERE, mxml_struct::line_number_end, mxml_struct::line_number_start, mxml_add_attribute(), mxml_add_node(), mxml_add_special_node(), mxml_create_root_node(), mxml_decode(), mxml_malloc(), mxml_struct::name, NULL, mxml_struct::parent, PROCESSING_INSTRUCTION_NODE, read_error(), TRUE, and mxml_struct::value.
Referenced by mxml_parse_file().
int mxml_parse_entity (char ** buf, const char * file_name, char * error, int error_size, int * error_line)
parse !ENTYTY entries of XML files and replace with references. Return 0 in case of no errors, return error description. Optional file_name is used for error reporting if called from mxml_parse_file()
References DIR_SEPARATOR, EXTERNAL_ENTITY, HERE, INTERNAL_ENTITY, mxml_create_root_node(), mxml_decode(), mxml_dirname(), mxml_free(), mxml_malloc(), MXML_MAX_ENTITY, mxml_realloc(), NULL, O_TEXT, and read_error().
Referenced by mxml_parse_file().
PMXML_NODE mxml_parse_file (const char * file_name, char * error, int error_size, int * error_line)
parse a XML file and convert it into a tree of MXML_NODE's. Return NULL in case of an error, return error description
References mxml_free(), mxml_malloc(), mxml_parse_buffer(), mxml_parse_entity(), NULL, O_TEXT, strlcat(), and strlcpy().
Referenced by DRSBoard::GetTimeCalibration().
int mxml_replace_attribute_name (PMXML_NODE pnode, const char * old_name, const char * new_name)
change the name of an attribute, keep its value
References mxml_struct::attribute_name, FALSE, MXML_NAME_LENGTH, mxml_struct::n_attributes, strlcpy(), and TRUE.
int mxml_replace_attribute_value (PMXML_NODE pnode, const char * attrib_name, const char * attrib_value)
change the value of an attribute
References mxml_struct::attribute_name, mxml_struct::attribute_value, FALSE, MXML_NAME_LENGTH, mxml_realloc(), mxml_struct::n_attributes, and TRUE.
int mxml_replace_node_name (PMXML_NODE pnode, const char * new_name)
References mxml_struct::name, strlcpy(), and TRUE.
int mxml_replace_node_value (PMXML_NODE pnode, const char * value)
References mxml_malloc(), mxml_realloc(), NULL, TRUE, and mxml_struct::value.
Referenced by mxml_clone_tree(), and mxml_replace_subvalue().
int mxml_replace_subvalue (PMXML_NODE pnode, const char * name, const char * value)
replace value os a subnode, like
<parent> <child>value</child> </parent>
if pnode=parent, and "name"="child", then "value" gets replaced
References mxml_struct::child, FALSE, mxml_replace_node_value(), mxml_struct::n_children, and mxml_struct::name.
int mxml_set_translate (MXML_WRITER * writer, int flag)
set translation of <,>,",',&, on/off in writer
References MXML_WRITER::translate.
int mxml_start_element (MXML_WRITER * writer, const char * name)
References mxml_start_element1(), and TRUE.
Referenced by mxml_write_element().
int mxml_start_element_noindent (MXML_WRITER * writer, const char * name)
References FALSE, and mxml_start_element1().
PMXML_NODE mxml_subnode (PMXML_NODE pnode, int idx)
return number of subnodes (children) of a node
References mxml_struct::child, idx, mxml_find_nodes1(), and NULL.
Referenced by DRSBoard::GetTimeCalibration(), and mxml_clone_tree().
void mxml_suppress_date (int suppress)
suppress writing date at the top of file.
References mxml_suppress_date_flag.
int mxml_write_attribute (MXML_WRITER * writer, const char * name, const char * value)
write an attribute to the currently open XML element
References MXML_WRITER::element_is_open, FALSE, mxml_encode(), mxml_write_line(), and MXML_WRITER::translate.
Referenced by mxml_write_subtree().
int mxml_write_comment (MXML_WRITER * writer, const char * string)
write a comment to an XML file, enclosed in "<!--" and "-->"
References MXML_WRITER::element_is_open, FALSE, MXML_WRITER::level, mxml_write_line(), strlcat(), TRUE, and XML_INDENT.
int mxml_write_element (MXML_WRITER * writer, const char * name, const char * value)
shortcut to write an element with a value but without attribute
References mxml_end_element(), mxml_start_element(), and mxml_write_value().
int mxml_write_empty_line (MXML_WRITER * writer)
write empty line
References MXML_WRITER::element_is_open, FALSE, mxml_write_line(), and TRUE.
int mxml_write_tree (const char * file_name, PMXML_NODE tree)
write a complete XML tree to a file
References mxml_struct::child, ELEMENT_NODE, FALSE, mxml_close_file(), mxml_open_file(), mxml_write_subtree(), mxml_struct::n_children, mxml_struct::node_type, and TRUE.
int mxml_write_value (MXML_WRITER * writer, const char * data)
write value of an XML element, like <[name]>[value]</[name]>
References _data_enc, MXML_WRITER::data_was_written, MXML_WRITER::element_is_open, FALSE, mxml_encode(), mxml_malloc(), mxml_realloc(), mxml_write_line(), MXML_WRITER::translate, and TRUE.
Referenced by mxml_write_element(), and mxml_write_subtree().