XMLNode Struct Reference
XMLNode Struct Reference
#include <xmlParser.h>
Public Types
enum XMLCharEncoding {
encoding_UTF8 =1, encoding_ascii =2, encoding_ShiftJIS =3, encoding_UTF8 =1,
encoding_ascii =2, encoding_ShiftJIS =3, encoding_UTF8 =1, encoding_ascii =2,
encoding_ShiftJIS =3, encoding_UTF8 =1, encoding_ascii =2, encoding_ShiftJIS =3
}
enum XMLCharEncoding {
encoding_UTF8 =1, encoding_ascii =2, encoding_ShiftJIS =3, encoding_UTF8 =1,
encoding_ascii =2, encoding_ShiftJIS =3, encoding_UTF8 =1, encoding_ascii =2,
encoding_ShiftJIS =3, encoding_UTF8 =1, encoding_ascii =2, encoding_ShiftJIS =3
}
enum XMLCharEncoding {
encoding_UTF8 =1, encoding_ascii =2, encoding_ShiftJIS =3, encoding_UTF8 =1,
encoding_ascii =2, encoding_ShiftJIS =3, encoding_UTF8 =1, encoding_ascii =2,
encoding_ShiftJIS =3, encoding_UTF8 =1, encoding_ascii =2, encoding_ShiftJIS =3
}
enum XMLCharEncoding {
encoding_UTF8 =1, encoding_ascii =2, encoding_ShiftJIS =3, encoding_UTF8 =1,
encoding_ascii =2, encoding_ShiftJIS =3, encoding_UTF8 =1, encoding_ascii =2,
encoding_ShiftJIS =3, encoding_UTF8 =1, encoding_ascii =2, encoding_ShiftJIS =3
}
typedef enum XMLNode::XMLCharEncoding XMLCharEncoding
typedef enum XMLNode::XMLCharEncoding XMLCharEncoding
typedef enum XMLNode::XMLCharEncoding XMLCharEncoding
typedef enum XMLNode::XMLCharEncoding XMLCharEncoding
Public Member Functions
XMLCSTR getName () const
XMLCSTR getText (int i=0) const
int nText () const
XMLNode getParentNode () const
XMLNode getChildNode (int i=0) const
XMLNode getChildNode (XMLCSTR name, int i) const
XMLNode getChildNode (XMLCSTR name, int *i=NULL) const
XMLNode getChildNodeWithAttribute (XMLCSTR tagName, XMLCSTR attributeName, XMLCSTR attributeValue=NULL, int *i=NULL) const
int nChildNode (XMLCSTR name) const
int nChildNode () const
XMLAttribute getAttribute (int i=0) const
XMLCSTR getAttributeName (int i=0) const
XMLCSTR getAttributeValue (int i=0) const
char isAttributeSet (XMLCSTR name) const
XMLCSTR getAttribute (XMLCSTR name, int i) const
XMLCSTR getAttribute (XMLCSTR name, int *i=NULL) const
int nAttribute () const
XMLClear getClear (int i=0) const
int nClear () const
XMLSTR createXMLString (int nFormat=1, int *pnSize=NULL) const
XMLError writeToFile (XMLCSTR filename, const char *encoding=NULL, char nFormat=1) const
XMLNodeContents enumContents (XMLElementPosition i) const
int nElement () const
char isEmpty () const
char isDeclaration () const
XMLNode deepCopy () const
~XMLNode ()
XMLNode (const XMLNode &A)
XMLNode & operator= (const XMLNode &A)
XMLNode ()
XMLNode addChild (XMLCSTR lpszName, char isDeclaration=FALSE, XMLElementPosition pos=-1)
XMLAttribute * addAttribute (XMLCSTR lpszName, XMLCSTR lpszValuev)
XMLCSTR addText (XMLCSTR lpszValue, XMLElementPosition pos=-1)
XMLClear * addClear (XMLCSTR lpszValue, XMLCSTR lpszOpen=NULL, XMLCSTR lpszClose=NULL, XMLElementPosition pos=-1)
XMLNode addChild (XMLNode nodeToAdd, XMLElementPosition pos=-1)
XMLCSTR updateName (XMLCSTR lpszName)
XMLAttribute * updateAttribute (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
XMLAttribute * updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName=NULL, int i=0)
XMLAttribute * updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName, XMLCSTR lpszOldName)
XMLCSTR updateText (XMLCSTR lpszNewValue, int i=0)
XMLCSTR updateText (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear * updateClear (XMLCSTR lpszNewContent, int i=0)
XMLClear * updateClear (XMLClear *newP, XMLClear *oldP)
XMLClear * updateClear (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
void deleteNodeContent ()
void deleteAttribute (XMLCSTR lpszName)
void deleteAttribute (int i=0)
void deleteAttribute (XMLAttribute *anAttribute)
void deleteText (int i=0)
void deleteText (XMLCSTR lpszValue)
void deleteClear (int i=0)
void deleteClear (XMLClear *p)
void deleteClear (XMLCSTR lpszValue)
XMLNode addChild_WOSD (XMLSTR lpszName, char isDeclaration=FALSE, XMLElementPosition pos=-1)
XMLAttribute * addAttribute_WOSD (XMLSTR lpszName, XMLSTR lpszValue)
XMLCSTR addText_WOSD (XMLSTR lpszValue, XMLElementPosition pos=-1)
XMLClear * addClear_WOSD (XMLSTR lpszValue, XMLCSTR lpszOpen=NULL, XMLCSTR lpszClose=NULL, XMLElementPosition pos=-1)
XMLCSTR updateName_WOSD (XMLSTR lpszName)
XMLAttribute * updateAttribute_WOSD (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
XMLAttribute * updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName=NULL, int i=0)
XMLAttribute * updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName, XMLCSTR lpszOldName)
XMLCSTR updateText_WOSD (XMLSTR lpszNewValue, int i=0)
XMLCSTR updateText_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear * updateClear_WOSD (XMLSTR lpszNewContent, int i=0)
XMLClear * updateClear_WOSD (XMLClear *newP, XMLClear *oldP)
XMLClear * updateClear_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLElementPosition positionOfText (int i=0) const
XMLElementPosition positionOfText (XMLCSTR lpszValue) const
XMLElementPosition positionOfClear (int i=0) const
XMLElementPosition positionOfClear (XMLCSTR lpszValue) const
XMLElementPosition positionOfClear (XMLClear *a) const
XMLElementPosition positionOfChildNode (int i=0) const
XMLElementPosition positionOfChildNode (XMLNode x) const
XMLElementPosition positionOfChildNode (XMLCSTR name, int i=0) const
XMLCSTR getName () const
XMLCSTR getText (int i=0) const
int nText () const
XMLNode getParentNode () const
XMLNode getChildNode (int i=0) const
XMLNode getChildNode (XMLCSTR name, int i) const
XMLNode getChildNode (XMLCSTR name, int *i=NULL) const
XMLNode getChildNodeWithAttribute (XMLCSTR tagName, XMLCSTR attributeName, XMLCSTR attributeValue=NULL, int *i=NULL) const
int nChildNode (XMLCSTR name) const
int nChildNode () const
XMLAttribute getAttribute (int i=0) const
XMLCSTR getAttributeName (int i=0) const
XMLCSTR getAttributeValue (int i=0) const
char isAttributeSet (XMLCSTR name) const
XMLCSTR getAttribute (XMLCSTR name, int i) const
XMLCSTR getAttribute (XMLCSTR name, int *i=NULL) const
int nAttribute () const
XMLClear getClear (int i=0) const
int nClear () const
XMLSTR createXMLString (int nFormat=1, int *pnSize=NULL) const
XMLError writeToFile (XMLCSTR filename, const char *encoding=NULL, char nFormat=1) const
XMLNodeContents enumContents (XMLElementPosition i) const
int nElement () const
char isEmpty () const
char isDeclaration () const
XMLNode deepCopy () const
~XMLNode ()
XMLNode (const XMLNode &A)
XMLNode & operator= (const XMLNode &A)
XMLNode ()
XMLNode addChild (XMLCSTR lpszName, char isDeclaration=FALSE, XMLElementPosition pos=-1)
XMLAttribute * addAttribute (XMLCSTR lpszName, XMLCSTR lpszValuev)
XMLCSTR addText (XMLCSTR lpszValue, XMLElementPosition pos=-1)
XMLClear * addClear (XMLCSTR lpszValue, XMLCSTR lpszOpen=NULL, XMLCSTR lpszClose=NULL, XMLElementPosition pos=-1)
XMLNode addChild (XMLNode nodeToAdd, XMLElementPosition pos=-1)
XMLCSTR updateName (XMLCSTR lpszName)
XMLAttribute * updateAttribute (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
XMLAttribute * updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName=NULL, int i=0)
XMLAttribute * updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName, XMLCSTR lpszOldName)
XMLCSTR updateText (XMLCSTR lpszNewValue, int i=0)
XMLCSTR updateText (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear * updateClear (XMLCSTR lpszNewContent, int i=0)
XMLClear * updateClear (XMLClear *newP, XMLClear *oldP)
XMLClear * updateClear (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
void deleteNodeContent ()
void deleteAttribute (XMLCSTR lpszName)
void deleteAttribute (int i=0)
void deleteAttribute (XMLAttribute *anAttribute)
void deleteText (int i=0)
void deleteText (XMLCSTR lpszValue)
void deleteClear (int i=0)
void deleteClear (XMLClear *p)
void deleteClear (XMLCSTR lpszValue)
XMLNode addChild_WOSD (XMLSTR lpszName, char isDeclaration=FALSE, XMLElementPosition pos=-1)
XMLAttribute * addAttribute_WOSD (XMLSTR lpszName, XMLSTR lpszValue)
XMLCSTR addText_WOSD (XMLSTR lpszValue, XMLElementPosition pos=-1)
XMLClear * addClear_WOSD (XMLSTR lpszValue, XMLCSTR lpszOpen=NULL, XMLCSTR lpszClose=NULL, XMLElementPosition pos=-1)
XMLCSTR updateName_WOSD (XMLSTR lpszName)
XMLAttribute * updateAttribute_WOSD (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
XMLAttribute * updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName=NULL, int i=0)
XMLAttribute * updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName, XMLCSTR lpszOldName)
XMLCSTR updateText_WOSD (XMLSTR lpszNewValue, int i=0)
XMLCSTR updateText_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear * updateClear_WOSD (XMLSTR lpszNewContent, int i=0)
XMLClear * updateClear_WOSD (XMLClear *newP, XMLClear *oldP)
XMLClear * updateClear_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLElementPosition positionOfText (int i=0) const
XMLElementPosition positionOfText (XMLCSTR lpszValue) const
XMLElementPosition positionOfClear (int i=0) const
XMLElementPosition positionOfClear (XMLCSTR lpszValue) const
XMLElementPosition positionOfClear (XMLClear *a) const
XMLElementPosition positionOfChildNode (int i=0) const
XMLElementPosition positionOfChildNode (XMLNode x) const
XMLElementPosition positionOfChildNode (XMLCSTR name, int i=0) const
XMLCSTR getName () const
XMLCSTR getText (int i=0) const
int nText () const
XMLNode getParentNode () const
XMLNode getChildNode (int i=0) const
XMLNode getChildNode (XMLCSTR name, int i) const
XMLNode getChildNode (XMLCSTR name, int *i=NULL) const
XMLNode getChildNodeWithAttribute (XMLCSTR tagName, XMLCSTR attributeName, XMLCSTR attributeValue=NULL, int *i=NULL) const
int nChildNode (XMLCSTR name) const
int nChildNode () const
XMLAttribute getAttribute (int i=0) const
XMLCSTR getAttributeName (int i=0) const
XMLCSTR getAttributeValue (int i=0) const
char isAttributeSet (XMLCSTR name) const
XMLCSTR getAttribute (XMLCSTR name, int i) const
XMLCSTR getAttribute (XMLCSTR name, int *i=NULL) const
int nAttribute () const
XMLClear getClear (int i=0) const
int nClear () const
XMLSTR createXMLString (int nFormat=1, int *pnSize=NULL) const
XMLError writeToFile (XMLCSTR filename, const char *encoding=NULL, char nFormat=1) const
XMLNodeContents enumContents (XMLElementPosition i) const
int nElement () const
char isEmpty () const
char isDeclaration () const
XMLNode deepCopy () const
~XMLNode ()
XMLNode (const XMLNode &A)
XMLNode & operator= (const XMLNode &A)
XMLNode ()
XMLNode addChild (XMLCSTR lpszName, char isDeclaration=FALSE, XMLElementPosition pos=-1)
XMLAttribute * addAttribute (XMLCSTR lpszName, XMLCSTR lpszValuev)
XMLCSTR addText (XMLCSTR lpszValue, XMLElementPosition pos=-1)
XMLClear * addClear (XMLCSTR lpszValue, XMLCSTR lpszOpen=NULL, XMLCSTR lpszClose=NULL, XMLElementPosition pos=-1)
XMLNode addChild (XMLNode nodeToAdd, XMLElementPosition pos=-1)
XMLCSTR updateName (XMLCSTR lpszName)
XMLAttribute * updateAttribute (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
XMLAttribute * updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName=NULL, int i=0)
XMLAttribute * updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName, XMLCSTR lpszOldName)
XMLCSTR updateText (XMLCSTR lpszNewValue, int i=0)
XMLCSTR updateText (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear * updateClear (XMLCSTR lpszNewContent, int i=0)
XMLClear * updateClear (XMLClear *newP, XMLClear *oldP)
XMLClear * updateClear (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
void deleteNodeContent ()
void deleteAttribute (XMLCSTR lpszName)
void deleteAttribute (int i=0)
void deleteAttribute (XMLAttribute *anAttribute)
void deleteText (int i=0)
void deleteText (XMLCSTR lpszValue)
void deleteClear (int i=0)
void deleteClear (XMLClear *p)
void deleteClear (XMLCSTR lpszValue)
XMLNode addChild_WOSD (XMLSTR lpszName, char isDeclaration=FALSE, XMLElementPosition pos=-1)
XMLAttribute * addAttribute_WOSD (XMLSTR lpszName, XMLSTR lpszValue)
XMLCSTR addText_WOSD (XMLSTR lpszValue, XMLElementPosition pos=-1)
XMLClear * addClear_WOSD (XMLSTR lpszValue, XMLCSTR lpszOpen=NULL, XMLCSTR lpszClose=NULL, XMLElementPosition pos=-1)
XMLCSTR updateName_WOSD (XMLSTR lpszName)
XMLAttribute * updateAttribute_WOSD (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
XMLAttribute * updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName=NULL, int i=0)
XMLAttribute * updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName, XMLCSTR lpszOldName)
XMLCSTR updateText_WOSD (XMLSTR lpszNewValue, int i=0)
XMLCSTR updateText_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear * updateClear_WOSD (XMLSTR lpszNewContent, int i=0)
XMLClear * updateClear_WOSD (XMLClear *newP, XMLClear *oldP)
XMLClear * updateClear_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLElementPosition positionOfText (int i=0) const
XMLElementPosition positionOfText (XMLCSTR lpszValue) const
XMLElementPosition positionOfClear (int i=0) const
XMLElementPosition positionOfClear (XMLCSTR lpszValue) const
XMLElementPosition positionOfClear (XMLClear *a) const
XMLElementPosition positionOfChildNode (int i=0) const
XMLElementPosition positionOfChildNode (XMLNode x) const
XMLElementPosition positionOfChildNode (XMLCSTR name, int i=0) const
XMLCSTR getName () const
XMLCSTR getText (int i=0) const
int nText () const
XMLNode getParentNode () const
XMLNode getChildNode (int i=0) const
XMLNode getChildNode (XMLCSTR name, int i) const
XMLNode getChildNode (XMLCSTR name, int *i=NULL) const
XMLNode getChildNodeWithAttribute (XMLCSTR tagName, XMLCSTR attributeName, XMLCSTR attributeValue=NULL, int *i=NULL) const
int nChildNode (XMLCSTR name) const
int nChildNode () const
XMLAttribute getAttribute (int i=0) const
XMLCSTR getAttributeName (int i=0) const
XMLCSTR getAttributeValue (int i=0) const
char isAttributeSet (XMLCSTR name) const
XMLCSTR getAttribute (XMLCSTR name, int i) const
XMLCSTR getAttribute (XMLCSTR name, int *i=NULL) const
int nAttribute () const
XMLClear getClear (int i=0) const
int nClear () const
XMLSTR createXMLString (int nFormat=1, int *pnSize=NULL) const
XMLError writeToFile (XMLCSTR filename, const char *encoding=NULL, char nFormat=1) const
XMLNodeContents enumContents (XMLElementPosition i) const
int nElement () const
char isEmpty () const
char isDeclaration () const
XMLNode deepCopy () const
~XMLNode ()
XMLNode (const XMLNode &A)
XMLNode & operator= (const XMLNode &A)
XMLNode ()
XMLNode addChild (XMLCSTR lpszName, char isDeclaration=FALSE, XMLElementPosition pos=-1)
XMLAttribute * addAttribute (XMLCSTR lpszName, XMLCSTR lpszValuev)
XMLCSTR addText (XMLCSTR lpszValue, XMLElementPosition pos=-1)
XMLClear * addClear (XMLCSTR lpszValue, XMLCSTR lpszOpen=NULL, XMLCSTR lpszClose=NULL, XMLElementPosition pos=-1)
XMLNode addChild (XMLNode nodeToAdd, XMLElementPosition pos=-1)
XMLCSTR updateName (XMLCSTR lpszName)
XMLAttribute * updateAttribute (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
XMLAttribute * updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName=NULL, int i=0)
XMLAttribute * updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName, XMLCSTR lpszOldName)
XMLCSTR updateText (XMLCSTR lpszNewValue, int i=0)
XMLCSTR updateText (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear * updateClear (XMLCSTR lpszNewContent, int i=0)
XMLClear * updateClear (XMLClear *newP, XMLClear *oldP)
XMLClear * updateClear (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
void deleteNodeContent ()
void deleteAttribute (XMLCSTR lpszName)
void deleteAttribute (int i=0)
void deleteAttribute (XMLAttribute *anAttribute)
void deleteText (int i=0)
void deleteText (XMLCSTR lpszValue)
void deleteClear (int i=0)
void deleteClear (XMLClear *p)
void deleteClear (XMLCSTR lpszValue)
XMLNode addChild_WOSD (XMLSTR lpszName, char isDeclaration=FALSE, XMLElementPosition pos=-1)
XMLAttribute * addAttribute_WOSD (XMLSTR lpszName, XMLSTR lpszValue)
XMLCSTR addText_WOSD (XMLSTR lpszValue, XMLElementPosition pos=-1)
XMLClear * addClear_WOSD (XMLSTR lpszValue, XMLCSTR lpszOpen=NULL, XMLCSTR lpszClose=NULL, XMLElementPosition pos=-1)
XMLCSTR updateName_WOSD (XMLSTR lpszName)
XMLAttribute * updateAttribute_WOSD (XMLAttribute *newAttribute, XMLAttribute *oldAttribute)
XMLAttribute * updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName=NULL, int i=0)
XMLAttribute * updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName, XMLCSTR lpszOldName)
XMLCSTR updateText_WOSD (XMLSTR lpszNewValue, int i=0)
XMLCSTR updateText_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear * updateClear_WOSD (XMLSTR lpszNewContent, int i=0)
XMLClear * updateClear_WOSD (XMLClear *newP, XMLClear *oldP)
XMLClear * updateClear_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLElementPosition positionOfText (int i=0) const
XMLElementPosition positionOfText (XMLCSTR lpszValue) const
XMLElementPosition positionOfClear (int i=0) const
XMLElementPosition positionOfClear (XMLCSTR lpszValue) const
XMLElementPosition positionOfClear (XMLClear *a) const
XMLElementPosition positionOfChildNode (int i=0) const
XMLElementPosition positionOfChildNode (XMLNode x) const
XMLElementPosition positionOfChildNode (XMLCSTR name, int i=0) const
Static Public Member Functions
static XMLNode createXMLTopNode (XMLCSTR lpszName, char isDeclaration=FALSE)
static XMLNode parseString (XMLCSTR lpXMLString, XMLCSTR tag=NULL, XMLResults *pResults=NULL)
static XMLNode parseFile (XMLCSTR filename, XMLCSTR tag=NULL, XMLResults *pResults=NULL)
static XMLNode openFileHelper (XMLCSTR filename, XMLCSTR tag=NULL)
static XMLCSTR getError (XMLError error)
static XMLCSTR getVersion ()
static XMLNode emptyNode ()
static XMLNode createXMLTopNode_WOSD (XMLSTR lpszName, char isDeclaration=FALSE)
static char setGlobalOptions (XMLCharEncoding characterEncoding=XMLNode::encoding_UTF8, char guessWideCharChars=1, char dropWhiteSpace=1)
static XMLCharEncoding guessCharEncoding (void *buffer, int bufLen, char useXMLEncodingAttribute=1)
static XMLNode createXMLTopNode (XMLCSTR lpszName, char isDeclaration=FALSE)
static XMLNode parseString (XMLCSTR lpXMLString, XMLCSTR tag=NULL, XMLResults *pResults=NULL)
static XMLNode parseFile (XMLCSTR filename, XMLCSTR tag=NULL, XMLResults *pResults=NULL)
static XMLNode openFileHelper (XMLCSTR filename, XMLCSTR tag=NULL)
static XMLCSTR getError (XMLError error)
static XMLCSTR getVersion ()
static XMLNode emptyNode ()
static XMLNode createXMLTopNode_WOSD (XMLSTR lpszName, char isDeclaration=FALSE)
static char setGlobalOptions (XMLCharEncoding characterEncoding=XMLNode::encoding_UTF8, char guessWideCharChars=1, char dropWhiteSpace=1)
static XMLCharEncoding guessCharEncoding (void *buffer, int bufLen, char useXMLEncodingAttribute=1)
static XMLNode createXMLTopNode (XMLCSTR lpszName, char isDeclaration=FALSE)
static XMLNode parseString (XMLCSTR lpXMLString, XMLCSTR tag=NULL, XMLResults *pResults=NULL)
static XMLNode parseFile (XMLCSTR filename, XMLCSTR tag=NULL, XMLResults *pResults=NULL)
static XMLNode openFileHelper (XMLCSTR filename, XMLCSTR tag=NULL)
static XMLCSTR getError (XMLError error)
static XMLCSTR getVersion ()
static XMLNode emptyNode ()
static XMLNode createXMLTopNode_WOSD (XMLSTR lpszName, char isDeclaration=FALSE)
static char setGlobalOptions (XMLCharEncoding characterEncoding=XMLNode::encoding_UTF8, char guessWideCharChars=1, char dropWhiteSpace=1)
static XMLCharEncoding guessCharEncoding (void *buffer, int bufLen, char useXMLEncodingAttribute=1)
static XMLNode createXMLTopNode (XMLCSTR lpszName, char isDeclaration=FALSE)
static XMLNode parseString (XMLCSTR lpXMLString, XMLCSTR tag=NULL, XMLResults *pResults=NULL)
static XMLNode parseFile (XMLCSTR filename, XMLCSTR tag=NULL, XMLResults *pResults=NULL)
static XMLNode openFileHelper (XMLCSTR filename, XMLCSTR tag=NULL)
static XMLCSTR getError (XMLError error)
static XMLCSTR getVersion ()
static XMLNode emptyNode ()
static XMLNode createXMLTopNode_WOSD (XMLSTR lpszName, char isDeclaration=FALSE)
static char setGlobalOptions (XMLCharEncoding characterEncoding=XMLNode::encoding_UTF8, char guessWideCharChars=1, char dropWhiteSpace=1)
static XMLCharEncoding guessCharEncoding (void *buffer, int bufLen, char useXMLEncodingAttribute=1)
Static Public Attributes
static XMLNode emptyXMLNode
static XMLClear emptyXMLClear ={ NULL, NULL, NULL}
static XMLAttribute emptyXMLAttribute ={ NULL, NULL}
Member Typedef Documentation
typedef enum XMLNode::XMLCharEncoding XMLNode::XMLCharEncoding
typedef enum XMLNode::XMLCharEncoding XMLNode::XMLCharEncoding
typedef enum XMLNode::XMLCharEncoding XMLNode::XMLCharEncoding
typedef enum XMLNode::XMLCharEncoding XMLNode::XMLCharEncoding
Member Enumeration Documentation
enum XMLNode::XMLCharEncoding
Enumerator
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
enum XMLNode::XMLCharEncoding
Enumerator
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
enum XMLNode::XMLCharEncoding
Enumerator
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
enum XMLNode::XMLCharEncoding
Enumerator
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
encoding_UTF8
encoding_ascii
encoding_ShiftJIS
Constructor & Destructor Documentation
XMLNode::~XMLNode ()
Referenced by charmemset().
XMLNode::XMLNode (const XMLNode & A)
XMLNode::XMLNode () inline
Referenced by charmemset(), createXMLTopNode(), createXMLTopNode_WOSD(), GetNextToken(), getParentNode(), myRealloc(), and updateName_WOSD().
XMLNode::~XMLNode ()
XMLNode::XMLNode (const XMLNode & A)
XMLNode::XMLNode () inline
References FALSE, NULL, XMLCSTR, and XMLSTR.
XMLNode::~XMLNode ()
XMLNode::XMLNode (const XMLNode & A)
XMLNode::XMLNode () inline
References FALSE, NULL, XMLCSTR, and XMLSTR.
XMLNode::~XMLNode ()
XMLNode::XMLNode (const XMLNode & A)
XMLNode::XMLNode () inline
References FALSE, NULL, XMLCSTR, and XMLSTR.
Member Function Documentation
XMLAttribute * XMLNode::addAttribute (XMLCSTR lpszName, XMLCSTR lpszValuev)
References stringDup().
Referenced by charmemset().
XMLAttribute* XMLNode::addAttribute (XMLCSTR lpszName, XMLCSTR lpszValuev)
XMLAttribute* XMLNode::addAttribute (XMLCSTR lpszName, XMLCSTR lpszValuev)
XMLAttribute* XMLNode::addAttribute (XMLCSTR lpszName, XMLCSTR lpszValuev)
XMLAttribute* XMLNode::addAttribute_WOSD (XMLSTR lpszName, XMLSTR lpszValue)
XMLAttribute* XMLNode::addAttribute_WOSD (XMLSTR lpszName, XMLSTR lpszValue)
XMLAttribute* XMLNode::addAttribute_WOSD (XMLSTR lpszName, XMLSTR lpszValue)
XMLAttribute * XMLNode::addAttribute_WOSD (XMLSTR lpszName, XMLSTR lpszValue)
Referenced by charmemset(), and updateAttribute_WOSD().
XMLNode XMLNode::addChild (XMLCSTR lpszName, char isDeclaration = FALSE, XMLElementPosition pos = -1)
References stringDup().
Referenced by charmemset().
XMLNode XMLNode::addChild (XMLCSTR lpszName, char isDeclaration = FALSE, XMLElementPosition pos = -1)
XMLNode XMLNode::addChild (XMLCSTR lpszName, char isDeclaration = FALSE, XMLElementPosition pos = -1)
XMLNode XMLNode::addChild (XMLCSTR lpszName, char isDeclaration = FALSE, XMLElementPosition pos = -1)
XMLNode XMLNode::addChild (XMLNode nodeToAdd, XMLElementPosition pos = -1)
References eNodeChild.
XMLNode XMLNode::addChild (XMLNode nodeToAdd, XMLElementPosition pos = -1)
XMLNode XMLNode::addChild (XMLNode nodeToAdd, XMLElementPosition pos = -1)
XMLNode XMLNode::addChild (XMLNode nodeToAdd, XMLElementPosition pos = -1)
XMLNode XMLNode::addChild_WOSD (XMLSTR lpszName, char isDeclaration = FALSE, XMLElementPosition pos = -1)
XMLNode XMLNode::addChild_WOSD (XMLSTR lpszName, char isDeclaration = FALSE, XMLElementPosition pos = -1)
XMLNode XMLNode::addChild_WOSD (XMLSTR lpszName, char isDeclaration = FALSE, XMLElementPosition pos = -1)
XMLNode XMLNode::addChild_WOSD (XMLSTR lpszName, char isDeclaration = FALSE, XMLElementPosition pos = -1)
Referenced by charmemset().
XMLClear* XMLNode::addClear (XMLCSTR lpszValue, XMLCSTR lpszOpen = NULL, XMLCSTR lpszClose = NULL, XMLElementPosition pos = -1)
XMLClear * XMLNode::addClear (XMLCSTR lpszValue, XMLCSTR lpszOpen = NULL, XMLCSTR lpszClose = NULL, XMLElementPosition pos = -1)
References stringDup().
Referenced by charmemset().
XMLClear* XMLNode::addClear (XMLCSTR lpszValue, XMLCSTR lpszOpen = NULL, XMLCSTR lpszClose = NULL, XMLElementPosition pos = -1)
XMLClear* XMLNode::addClear (XMLCSTR lpszValue, XMLCSTR lpszOpen = NULL, XMLCSTR lpszClose = NULL, XMLElementPosition pos = -1)
XMLClear* XMLNode::addClear_WOSD (XMLSTR lpszValue, XMLCSTR lpszOpen = NULL, XMLCSTR lpszClose = NULL, XMLElementPosition pos = -1)
XMLClear* XMLNode::addClear_WOSD (XMLSTR lpszValue, XMLCSTR lpszOpen = NULL, XMLCSTR lpszClose = NULL, XMLElementPosition pos = -1)
XMLClear* XMLNode::addClear_WOSD (XMLSTR lpszValue, XMLCSTR lpszOpen = NULL, XMLCSTR lpszClose = NULL, XMLElementPosition pos = -1)
XMLClear * XMLNode::addClear_WOSD (XMLSTR lpszValue, XMLCSTR lpszOpen = NULL, XMLCSTR lpszClose = NULL, XMLElementPosition pos = -1)
Referenced by charmemset(), and updateClear_WOSD().
XMLCSTR XMLNode::addText (XMLCSTR lpszValue, XMLElementPosition pos = -1)
XMLCSTR XMLNode::addText (XMLCSTR lpszValue, XMLElementPosition pos = -1)
References stringDup().
Referenced by charmemset().
XMLCSTR XMLNode::addText (XMLCSTR lpszValue, XMLElementPosition pos = -1)
XMLCSTR XMLNode::addText (XMLCSTR lpszValue, XMLElementPosition pos = -1)
XMLCSTR XMLNode::addText_WOSD (XMLSTR lpszValue, XMLElementPosition pos = -1)
XMLCSTR XMLNode::addText_WOSD (XMLSTR lpszValue, XMLElementPosition pos = -1)
XMLCSTR XMLNode::addText_WOSD (XMLSTR lpszValue, XMLElementPosition pos = -1)
XMLCSTR XMLNode::addText_WOSD (XMLSTR lpszValue, XMLElementPosition pos = -1)
Referenced by charmemset(), and updateText_WOSD().
XMLSTR XMLNode::createXMLString (int nFormat = 1, int * pnSize = NULL) const
XMLSTR XMLNode::createXMLString (int nFormat = 1, int * pnSize = NULL) const
References dropWhiteSpace, eNodeChild, NULL, XMLCHAR, and XMLSTR.
Referenced by charmemset(), and writeToFile().
XMLSTR XMLNode::createXMLString (int nFormat = 1, int * pnSize = NULL) const
XMLSTR XMLNode::createXMLString (int nFormat = 1, int * pnSize = NULL) const
static XMLNode XMLNode::createXMLTopNode (XMLCSTR lpszName, char isDeclaration = FALSE) static
static XMLNode XMLNode::createXMLTopNode (XMLCSTR lpszName, char isDeclaration = FALSE) static
XMLNode XMLNode::createXMLTopNode (XMLCSTR lpszName, char isDeclaration = FALSE) static
References NULL, stringDup(), and XMLNode().
Referenced by GetNextToken().
static XMLNode XMLNode::createXMLTopNode (XMLCSTR lpszName, char isDeclaration = FALSE) static
static XMLNode XMLNode::createXMLTopNode_WOSD (XMLSTR lpszName, char isDeclaration = FALSE) static
static XMLNode XMLNode::createXMLTopNode_WOSD (XMLSTR lpszName, char isDeclaration = FALSE) static
static XMLNode XMLNode::createXMLTopNode_WOSD (XMLSTR lpszName, char isDeclaration = FALSE) static
XMLNode XMLNode::createXMLTopNode_WOSD (XMLSTR lpszName, char isDeclaration = FALSE) static
References NULL, and XMLNode().
Referenced by GetNextToken().
XMLNode XMLNode::deepCopy () const
XMLNode XMLNode::deepCopy () const
References emptyXMLNode, NULL, stringDup(), and XMLCSTR.
Referenced by charmemset().
XMLNode XMLNode::deepCopy () const
XMLNode XMLNode::deepCopy () const
void XMLNode::deleteAttribute (XMLCSTR lpszName)
void XMLNode::deleteAttribute (XMLCSTR lpszName)
void XMLNode::deleteAttribute (XMLCSTR lpszName)
void XMLNode::deleteAttribute (XMLCSTR lpszName)
References getAttribute().
Referenced by charmemset(), and deleteAttribute().
void XMLNode::deleteAttribute (int i = 0)
void XMLNode::deleteAttribute (int i = 0)
void XMLNode::deleteAttribute (int i = 0)
References XMLAttribute::lpszName, XMLAttribute::lpszValue, and NULL.
void XMLNode::deleteAttribute (int i = 0)
void XMLNode::deleteAttribute (XMLAttribute * anAttribute)
void XMLNode::deleteAttribute (XMLAttribute * anAttribute)
void XMLNode::deleteAttribute (XMLAttribute * anAttribute)
References deleteAttribute(), and XMLAttribute::lpszName.
void XMLNode::deleteAttribute (XMLAttribute * anAttribute)
void XMLNode::deleteClear (int i = 0)
void XMLNode::deleteClear (int i = 0)
void XMLNode::deleteClear (int i = 0)
void XMLNode::deleteClear (int i = 0)
References eNodeClear, XMLClear::lpszValue, NULL, and XMLCSTR.
Referenced by charmemset(), and deleteClear().
void XMLNode::deleteClear (XMLClear * p)
void XMLNode::deleteClear (XMLClear * p)
void XMLNode::deleteClear (XMLClear * p)
void XMLNode::deleteClear (XMLClear * p)
References deleteClear(), and XMLClear::lpszValue.
void XMLNode::deleteClear (XMLCSTR lpszValue)
void XMLNode::deleteClear (XMLCSTR lpszValue)
void XMLNode::deleteClear (XMLCSTR lpszValue)
void XMLNode::deleteClear (XMLCSTR lpszValue)
References deleteClear().
void XMLNode::deleteNodeContent ()
void XMLNode::deleteNodeContent ()
References myFree(), and NULL.
Referenced by charmemset().
void XMLNode::deleteNodeContent ()
void XMLNode::deleteNodeContent ()
void XMLNode::deleteText (int i = 0)
void XMLNode::deleteText (int i = 0)
void XMLNode::deleteText (int i = 0)
References eNodeText, NULL, and XMLCSTR.
Referenced by charmemset(), and deleteText().
void XMLNode::deleteText (int i = 0)
void XMLNode::deleteText (XMLCSTR lpszValue)
void XMLNode::deleteText (XMLCSTR lpszValue)
void XMLNode::deleteText (XMLCSTR lpszValue)
References deleteText().
void XMLNode::deleteText (XMLCSTR lpszValue)
XMLNode XMLNode::emptyNode () static
References emptyXMLNode.
Referenced by charmemset().
static XMLNode XMLNode::emptyNode () static
static XMLNode XMLNode::emptyNode () static
static XMLNode XMLNode::emptyNode () static
XMLNodeContents XMLNode::enumContents (XMLElementPosition i) const
XMLNodeContents XMLNode::enumContents (XMLElementPosition i) const
XMLNodeContents XMLNode::enumContents (XMLElementPosition i) const
XMLNodeContents XMLNode::enumContents (XMLElementPosition i) const
References XMLNodeContents::attrib, XMLNodeContents::child, XMLNodeContents::clear, eNodeAttribute, eNodeChild, eNodeClear, eNodeNULL, eNodeText, XMLNodeContents::etype, nAttribute(), and XMLNodeContents::text.
Referenced by charmemset().
XMLAttribute XMLNode::getAttribute (int i = 0) const
XMLAttribute XMLNode::getAttribute (int i = 0) const
References emptyXMLAttribute.
Referenced by charmemset(), deleteAttribute(), getAttribute(), getChildNodeWithAttribute(), SlowcontrolManager::ShowStatus(), updateAttribute_WOSD(), and xml_readsettings().
XMLAttribute XMLNode::getAttribute (int i = 0) const
XMLAttribute XMLNode::getAttribute (int i = 0) const
XMLCSTR XMLNode::getAttribute (XMLCSTR name, int i) const
XMLCSTR XMLNode::getAttribute (XMLCSTR name, int i) const
References getAttribute(), and NULL.
XMLCSTR XMLNode::getAttribute (XMLCSTR name, int i) const
XMLCSTR XMLNode::getAttribute (XMLCSTR name, int i) const
XMLCSTR XMLNode::getAttribute (XMLCSTR name, int * i = NULL) const
XMLCSTR XMLNode::getAttribute (XMLCSTR name, int * i = NULL) const
References XMLAttribute::lpszName, XMLAttribute::lpszValue, NULL, and xstricmp().
XMLCSTR XMLNode::getAttribute (XMLCSTR name, int * i = NULL) const
XMLCSTR XMLNode::getAttribute (XMLCSTR name, int * i = NULL) const
XMLCSTR XMLNode::getAttributeName (int i = 0) const
References NULL.
Referenced by charmemset().
XMLCSTR XMLNode::getAttributeName (int i = 0) const
XMLCSTR XMLNode::getAttributeName (int i = 0) const
XMLCSTR XMLNode::getAttributeName (int i = 0) const
XMLCSTR XMLNode::getAttributeValue (int i = 0) const
XMLCSTR XMLNode::getAttributeValue (int i = 0) const
References NULL.
Referenced by charmemset().
XMLCSTR XMLNode::getAttributeValue (int i = 0) const
XMLCSTR XMLNode::getAttributeValue (int i = 0) const
XMLNode XMLNode::getChildNode (int i = 0) const
References emptyXMLNode.
Referenced by charmemset(), CountLinesAndColumns(), getChildNode(), getChildNodeWithAttribute(), ADCManager1724::Init(), ADCManager1720::Init(), ADCManager1730::Init(), parseString(), positionOfChildNode(), StorageManager::SaveContainer(), ScopeManager::ShowEvent(), SlowcontrolManager::ShowStatus(), writeToFile(), and xml_readsettings().
XMLNode XMLNode::getChildNode (int i = 0) const
XMLNode XMLNode::getChildNode (int i = 0) const
XMLNode XMLNode::getChildNode (int i = 0) const
XMLNode XMLNode::getChildNode (XMLCSTR name, int i) const
XMLNode XMLNode::getChildNode (XMLCSTR name, int i) const
XMLNode XMLNode::getChildNode (XMLCSTR name, int i) const
References emptyXMLNode, and getChildNode().
XMLNode XMLNode::getChildNode (XMLCSTR name, int i) const
XMLNode XMLNode::getChildNode (XMLCSTR name, int * i = NULL) const
XMLNode XMLNode::getChildNode (XMLCSTR name, int * i = NULL) const
XMLNode XMLNode::getChildNode (XMLCSTR name, int * i = NULL) const
XMLNode XMLNode::getChildNode (XMLCSTR name, int * i = NULL) const
References emptyXMLNode, and xstricmp().
XMLNode XMLNode::getChildNodeWithAttribute (XMLCSTR tagName, XMLCSTR attributeName, XMLCSTR attributeValue = NULL, int * i = NULL) const
XMLNode XMLNode::getChildNodeWithAttribute (XMLCSTR tagName, XMLCSTR attributeName, XMLCSTR attributeValue = NULL, int * i = NULL) const
XMLNode XMLNode::getChildNodeWithAttribute (XMLCSTR tagName, XMLCSTR attributeName, XMLCSTR attributeValue = NULL, int * i = NULL) const
XMLNode XMLNode::getChildNodeWithAttribute (XMLCSTR tagName, XMLCSTR attributeName, XMLCSTR attributeValue = NULL, int * i = NULL) const
References emptyXMLNode, getAttribute(), getChildNode(), isAttributeSet(), isEmpty(), XMLCSTR, and xstricmp().
Referenced by charmemset().
XMLClear XMLNode::getClear (int i = 0) const
XMLClear XMLNode::getClear (int i = 0) const
XMLClear XMLNode::getClear (int i = 0) const
References emptyXMLClear.
Referenced by charmemset().
XMLClear XMLNode::getClear (int i = 0) const
XMLCSTR XMLNode::getError (XMLError error) static
References _X, eXMLErrorBase64DataSizeIsNotMultipleOf4, eXMLErrorBase64DecodeBufferTooSmall, eXMLErrorBase64DecodeIllegalCharacter, eXMLErrorBase64DecodeTruncatedData, eXMLErrorCannotOpenWriteFile, eXMLErrorCannotWriteFile, eXMLErrorCharConversionError, eXMLErrorEmpty, eXMLErrorFileNotFound, eXMLErrorFirstTagNotFound, eXMLErrorMissingEndTag, eXMLErrorMissingEndTagName, eXMLErrorMissingTagName, eXMLErrorNoElements, eXMLErrorNone, eXMLErrorNoXMLTagFound, eXMLErrorUnexpectedToken, eXMLErrorUnknownCharacterEntity, eXMLErrorUnmatchedEndClearTag, eXMLErrorUnmatchedEndTag, FALSE, and myIsTextWideChar().
Referenced by _strnicmp(), and openFileHelper().
static XMLCSTR XMLNode::getError (XMLError error) static
static XMLCSTR XMLNode::getError (XMLError error) static
static XMLCSTR XMLNode::getError (XMLError error) static
XMLCSTR XMLNode::getName () const
XMLCSTR XMLNode::getName () const
XMLCSTR XMLNode::getName () const
References NULL.
Referenced by charmemset(), CountLinesAndColumns(), and parseString().
XMLCSTR XMLNode::getName () const
XMLNode XMLNode::getParentNode () const
XMLNode XMLNode::getParentNode () const
References emptyXMLNode, and XMLNode().
Referenced by charmemset().
XMLNode XMLNode::getParentNode () const
XMLNode XMLNode::getParentNode () const
XMLCSTR XMLNode::getText (int i = 0) const
XMLCSTR XMLNode::getText (int i = 0) const
XMLCSTR XMLNode::getText (int i = 0) const
References NULL.
Referenced by charmemset(), ADCManager1724::Init(), ADCManager1720::Init(), ADCManager1730::Init(), StorageManager::SaveContainer(), ScopeManager::ShowEvent(), SlowcontrolManager::ShowStatus(), and xml_readsettings().
XMLCSTR XMLNode::getText (int i = 0) const
static XMLCSTR XMLNode::getVersion () static
static XMLCSTR XMLNode::getVersion () static
XMLCSTR XMLNode::getVersion () static
References _X.
static XMLCSTR XMLNode::getVersion () static
static XMLCharEncoding XMLNode::guessCharEncoding (void * buffer, int bufLen, char useXMLEncodingAttribute = 1) static
static XMLCharEncoding XMLNode::guessCharEncoding (void * buffer, int bufLen, char useXMLEncodingAttribute = 1) static
XMLNode::XMLCharEncoding XMLNode::guessCharEncoding (void * buffer, int bufLen, char useXMLEncodingAttribute = 1) static
References _strnicmp(), encoding_ascii, encoding_ShiftJIS, encoding_UTF8, guessWideCharChars, mmin(), myIsTextWideChar(), XML_isSPACECHAR, and XML_utf8ByteTable.
Referenced by _strnicmp(), charmemset(), and openFileHelper().
static XMLCharEncoding XMLNode::guessCharEncoding (void * buffer, int bufLen, char useXMLEncodingAttribute = 1) static
char XMLNode::isAttributeSet (XMLCSTR name) const
References FALSE, XMLAttribute::lpszName, TRUE, and xstricmp().
Referenced by charmemset(), and getChildNodeWithAttribute().
char XMLNode::isAttributeSet (XMLCSTR name) const
char XMLNode::isAttributeSet (XMLCSTR name) const
char XMLNode::isAttributeSet (XMLCSTR name) const
char XMLNode::isDeclaration () const
char XMLNode::isDeclaration () const
char XMLNode::isDeclaration () const
char XMLNode::isDeclaration () const
Referenced by charmemset(), CountLinesAndColumns(), GetNextToken(), myRealloc(), parseString(), updateName_WOSD(), and writeToFile().
char XMLNode::isEmpty () const
char XMLNode::isEmpty () const
References NULL.
Referenced by charmemset(), getChildNodeWithAttribute(), and myRealloc().
char XMLNode::isEmpty () const
char XMLNode::isEmpty () const
int XMLNode::nAttribute () const
int XMLNode::nAttribute () const
Referenced by charmemset(), and enumContents().
int XMLNode::nAttribute () const
int XMLNode::nAttribute () const
int XMLNode::nChildNode (XMLCSTR name) const
int XMLNode::nChildNode (XMLCSTR name) const
int XMLNode::nChildNode (XMLCSTR name) const
int XMLNode::nChildNode (XMLCSTR name) const
References xstricmp().
Referenced by CountLinesAndColumns(), parseString(), and xml_readsettings().
int XMLNode::nChildNode () const
Referenced by charmemset().
int XMLNode::nChildNode () const
int XMLNode::nChildNode () const
int XMLNode::nChildNode () const
int XMLNode::nClear () const
int XMLNode::nClear () const
int XMLNode::nClear () const
Referenced by charmemset().
int XMLNode::nClear () const
int XMLNode::nElement () const
int XMLNode::nElement () const
int XMLNode::nElement () const
int XMLNode::nElement () const
Referenced by charmemset(), CountLinesAndColumns(), and parseString().
int XMLNode::nText () const
Referenced by charmemset().
int XMLNode::nText () const
int XMLNode::nText () const
int XMLNode::nText () const
XMLNode XMLNode::openFileHelper (XMLCSTR filename, XMLCSTR tag = NULL) static
References _X, dropWhiteSpace, XMLResults::error, eXMLErrorFirstTagNotFound, eXMLErrorNone, getError(), guessCharEncoding(), guessWideCharChars, XMLResults::nColumn, XMLResults::nLine, NULL, parseFile(), setGlobalOptions(), xfopen(), and XMLCSTR.
Referenced by _strnicmp(), ADCManager1724::Init(), ADCManager1720::Init(), ADCManager1730::Init(), StorageManager::SaveContainer(), ScopeManager::ShowEvent(), SlowcontrolManager::ShowStatus(), and xml_readsettings().
static XMLNode XMLNode::openFileHelper (XMLCSTR filename, XMLCSTR tag = NULL) static
static XMLNode XMLNode::openFileHelper (XMLCSTR filename, XMLCSTR tag = NULL) static
static XMLNode XMLNode::openFileHelper (XMLCSTR filename, XMLCSTR tag = NULL) static
XMLNode& XMLNode::operator= (const XMLNode & A)
XMLNode& XMLNode::operator= (const XMLNode & A)
XMLNode & XMLNode::operator= (const XMLNode & A)
Referenced by charmemset().
XMLNode& XMLNode::operator= (const XMLNode & A)
static XMLNode XMLNode::parseFile (XMLCSTR filename, XMLCSTR tag = NULL, XMLResults * pResults = NULL) static
static XMLNode XMLNode::parseFile (XMLCSTR filename, XMLCSTR tag = NULL, XMLResults * pResults = NULL) static
XMLNode XMLNode::parseFile (XMLCSTR filename, XMLCSTR tag = NULL, XMLResults * pResults = NULL) static
References _X, emptyXMLNode, XMLResults::error, eXMLErrorCharConversionError, eXMLErrorEmpty, eXMLErrorFileNotFound, guessWideCharChars, myIsTextWideChar(), myWideCharToMultiByte(), XMLResults::nColumn, XMLResults::nLine, NULL, parseString(), xfopen(), and XMLSTR.
Referenced by _strnicmp(), CountLinesAndColumns(), and openFileHelper().
static XMLNode XMLNode::parseFile (XMLCSTR filename, XMLCSTR tag = NULL, XMLResults * pResults = NULL) static
static XMLNode XMLNode::parseString (XMLCSTR lpXMLString, XMLCSTR tag = NULL, XMLResults * pResults = NULL) static
static XMLNode XMLNode::parseString (XMLCSTR lpXMLString, XMLCSTR tag = NULL, XMLResults * pResults = NULL) static
XMLNode XMLNode::parseString (XMLCSTR lpXMLString, XMLCSTR tag = NULL, XMLResults * pResults = NULL) static
References CountLinesAndColumns(), emptyXMLNode, XMLResults::error, XML::error, eXMLErrorFirstTagNotFound, eXMLErrorMissingEndTag, eXMLErrorNoElements, eXMLErrorNone, eXMLErrorNoXMLTagFound, FALSE, getChildNode(), getName(), isDeclaration(), XML::lpXML, nChildNode(), XMLResults::nColumn, nElement(), XML::nIndex, XML::nIndexMissigEndTag, XMLResults::nLine, NULL, TRUE, XMLCSTR, xstricmp(), and xstrlen().
Referenced by CountLinesAndColumns(), and parseFile().
static XMLNode XMLNode::parseString (XMLCSTR lpXMLString, XMLCSTR tag = NULL, XMLResults * pResults = NULL) static
XMLElementPosition XMLNode::positionOfChildNode (int i = 0) const
References eNodeChild.
Referenced by charmemset(), and positionOfChildNode().
XMLElementPosition XMLNode::positionOfChildNode (int i = 0) const
XMLElementPosition XMLNode::positionOfChildNode (int i = 0) const
XMLElementPosition XMLNode::positionOfChildNode (int i = 0) const
XMLElementPosition XMLNode::positionOfChildNode (XMLNode x) const
References eNodeChild.
XMLElementPosition XMLNode::positionOfChildNode (XMLNode x) const
XMLElementPosition XMLNode::positionOfChildNode (XMLNode x) const
XMLElementPosition XMLNode::positionOfChildNode (XMLNode x) const
XMLElementPosition XMLNode::positionOfChildNode (XMLCSTR name, int i = 0) const
XMLElementPosition XMLNode::positionOfChildNode (XMLCSTR name, int i = 0) const
XMLElementPosition XMLNode::positionOfChildNode (XMLCSTR name, int i = 0) const
XMLElementPosition XMLNode::positionOfChildNode (XMLCSTR name, int i = 0) const
References eNodeChild, getChildNode(), and positionOfChildNode().
XMLElementPosition XMLNode::positionOfClear (int i = 0) const
References eNodeClear.
Referenced by charmemset(), and positionOfClear().
XMLElementPosition XMLNode::positionOfClear (int i = 0) const
XMLElementPosition XMLNode::positionOfClear (int i = 0) const
XMLElementPosition XMLNode::positionOfClear (int i = 0) const
XMLElementPosition XMLNode::positionOfClear (XMLCSTR lpszValue) const
XMLElementPosition XMLNode::positionOfClear (XMLCSTR lpszValue) const
References positionOfClear().
XMLElementPosition XMLNode::positionOfClear (XMLCSTR lpszValue) const
XMLElementPosition XMLNode::positionOfClear (XMLCSTR lpszValue) const
XMLElementPosition XMLNode::positionOfClear (XMLClear * a) const
XMLElementPosition XMLNode::positionOfClear (XMLClear * a) const
References XMLClear::lpszValue, and positionOfClear().
XMLElementPosition XMLNode::positionOfClear (XMLClear * a) const
XMLElementPosition XMLNode::positionOfClear (XMLClear * a) const
XMLElementPosition XMLNode::positionOfText (int i = 0) const
References eNodeText.
Referenced by charmemset(), and positionOfText().
XMLElementPosition XMLNode::positionOfText (int i = 0) const
XMLElementPosition XMLNode::positionOfText (int i = 0) const
XMLElementPosition XMLNode::positionOfText (int i = 0) const
XMLElementPosition XMLNode::positionOfText (XMLCSTR lpszValue) const
XMLElementPosition XMLNode::positionOfText (XMLCSTR lpszValue) const
XMLElementPosition XMLNode::positionOfText (XMLCSTR lpszValue) const
References positionOfText().
XMLElementPosition XMLNode::positionOfText (XMLCSTR lpszValue) const
static char XMLNode::setGlobalOptions (XMLCharEncoding characterEncoding = XMLNode::encoding_UTF8, char guessWideCharChars = 1, char dropWhiteSpace = 1) static
char XMLNode::setGlobalOptions (XMLCharEncoding characterEncoding = XMLNode::encoding_UTF8, char guessWideCharChars = 1, char dropWhiteSpace = 1) static
References characterEncoding, dropWhiteSpace, encoding_ascii, encoding_ShiftJIS, encoding_UTF8, guessWideCharChars, XML_asciiByteTable, XML_ByteTable, XML_sjisByteTable, and XML_utf8ByteTable.
Referenced by _strnicmp(), charmemset(), and openFileHelper().
static char XMLNode::setGlobalOptions (XMLCharEncoding characterEncoding = XMLNode::encoding_UTF8, char guessWideCharChars = 1, char dropWhiteSpace = 1) static
static char XMLNode::setGlobalOptions (XMLCharEncoding characterEncoding = XMLNode::encoding_UTF8, char guessWideCharChars = 1, char dropWhiteSpace = 1) static
XMLAttribute * XMLNode::updateAttribute (XMLAttribute * newAttribute, XMLAttribute * oldAttribute)
References XMLAttribute::lpszName, XMLAttribute::lpszValue, stringDup(), and updateAttribute_WOSD().
Referenced by charmemset().
XMLAttribute* XMLNode::updateAttribute (XMLAttribute * newAttribute, XMLAttribute * oldAttribute)
XMLAttribute* XMLNode::updateAttribute (XMLAttribute * newAttribute, XMLAttribute * oldAttribute)
XMLAttribute* XMLNode::updateAttribute (XMLAttribute * newAttribute, XMLAttribute * oldAttribute)
XMLAttribute* XMLNode::updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName = NULL, int i = 0)
XMLAttribute * XMLNode::updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName = NULL, int i = 0)
References stringDup(), and updateAttribute_WOSD().
XMLAttribute* XMLNode::updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName = NULL, int i = 0)
XMLAttribute* XMLNode::updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName = NULL, int i = 0)
XMLAttribute * XMLNode::updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName, XMLCSTR lpszOldName)
References stringDup(), and updateAttribute_WOSD().
XMLAttribute* XMLNode::updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName, XMLCSTR lpszOldName)
XMLAttribute* XMLNode::updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName, XMLCSTR lpszOldName)
XMLAttribute* XMLNode::updateAttribute (XMLCSTR lpszNewValue, XMLCSTR lpszNewName, XMLCSTR lpszOldName)
XMLAttribute * XMLNode::updateAttribute_WOSD (XMLAttribute * newAttribute, XMLAttribute * oldAttribute)
References addAttribute_WOSD(), XMLAttribute::lpszName, XMLAttribute::lpszValue, and XMLSTR.
Referenced by charmemset(), updateAttribute(), and updateAttribute_WOSD().
XMLAttribute* XMLNode::updateAttribute_WOSD (XMLAttribute * newAttribute, XMLAttribute * oldAttribute)
XMLAttribute* XMLNode::updateAttribute_WOSD (XMLAttribute * newAttribute, XMLAttribute * oldAttribute)
XMLAttribute* XMLNode::updateAttribute_WOSD (XMLAttribute * newAttribute, XMLAttribute * oldAttribute)
XMLAttribute* XMLNode::updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName = NULL, int i = 0)
XMLAttribute * XMLNode::updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName = NULL, int i = 0)
References addAttribute_WOSD(), XMLAttribute::lpszName, XMLAttribute::lpszValue, and NULL.
XMLAttribute* XMLNode::updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName = NULL, int i = 0)
XMLAttribute* XMLNode::updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName = NULL, int i = 0)
XMLAttribute * XMLNode::updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName, XMLCSTR lpszOldName)
References addAttribute_WOSD(), getAttribute(), stringDup(), updateAttribute_WOSD(), and XMLCSTR.
XMLAttribute* XMLNode::updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName, XMLCSTR lpszOldName)
XMLAttribute* XMLNode::updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName, XMLCSTR lpszOldName)
XMLAttribute* XMLNode::updateAttribute_WOSD (XMLSTR lpszNewValue, XMLSTR lpszNewName, XMLCSTR lpszOldName)
XMLClear* XMLNode::updateClear (XMLCSTR lpszNewContent, int i = 0)
XMLClear* XMLNode::updateClear (XMLCSTR lpszNewContent, int i = 0)
XMLClear * XMLNode::updateClear (XMLCSTR lpszNewContent, int i = 0)
References stringDup(), and updateClear_WOSD().
Referenced by charmemset().
XMLClear* XMLNode::updateClear (XMLCSTR lpszNewContent, int i = 0)
XMLClear* XMLNode::updateClear (XMLClear * newP, XMLClear * oldP)
XMLClear * XMLNode::updateClear (XMLClear * newP, XMLClear * oldP)
References XMLClear::lpszValue, stringDup(), and updateClear_WOSD().
XMLClear* XMLNode::updateClear (XMLClear * newP, XMLClear * oldP)
XMLClear* XMLNode::updateClear (XMLClear * newP, XMLClear * oldP)
XMLClear* XMLNode::updateClear (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear* XMLNode::updateClear (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear * XMLNode::updateClear (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
References stringDup(), and updateClear_WOSD().
XMLClear* XMLNode::updateClear (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear* XMLNode::updateClear_WOSD (XMLSTR lpszNewContent, int i = 0)
XMLClear* XMLNode::updateClear_WOSD (XMLSTR lpszNewContent, int i = 0)
XMLClear * XMLNode::updateClear_WOSD (XMLSTR lpszNewContent, int i = 0)
References addClear_WOSD(), XMLClear::lpszValue, and NULL.
Referenced by charmemset(), updateClear(), and updateClear_WOSD().
XMLClear* XMLNode::updateClear_WOSD (XMLSTR lpszNewContent, int i = 0)
XMLClear* XMLNode::updateClear_WOSD (XMLClear * newP, XMLClear * oldP)
XMLClear * XMLNode::updateClear_WOSD (XMLClear * newP, XMLClear * oldP)
References XMLClear::lpszValue, NULL, updateClear_WOSD(), and XMLSTR.
XMLClear* XMLNode::updateClear_WOSD (XMLClear * newP, XMLClear * oldP)
XMLClear* XMLNode::updateClear_WOSD (XMLClear * newP, XMLClear * oldP)
XMLClear* XMLNode::updateClear_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear* XMLNode::updateClear_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear* XMLNode::updateClear_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLClear * XMLNode::updateClear_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
References addClear_WOSD(), NULL, and updateClear_WOSD().
XMLCSTR XMLNode::updateName (XMLCSTR lpszName)
XMLCSTR XMLNode::updateName (XMLCSTR lpszName)
XMLCSTR XMLNode::updateName (XMLCSTR lpszName)
References stringDup(), and updateName_WOSD().
Referenced by charmemset().
XMLCSTR XMLNode::updateName (XMLCSTR lpszName)
XMLCSTR XMLNode::updateName_WOSD (XMLSTR lpszName)
XMLCSTR XMLNode::updateName_WOSD (XMLSTR lpszName)
XMLCSTR XMLNode::updateName_WOSD (XMLSTR lpszName)
XMLCSTR XMLNode::updateName_WOSD (XMLSTR lpszName)
References isDeclaration(), NULL, XMLNode(), and XMLSTR.
Referenced by charmemset(), GetNextToken(), and updateName().
XMLCSTR XMLNode::updateText (XMLCSTR lpszNewValue, int i = 0)
XMLCSTR XMLNode::updateText (XMLCSTR lpszNewValue, int i = 0)
References stringDup(), and updateText_WOSD().
Referenced by charmemset().
XMLCSTR XMLNode::updateText (XMLCSTR lpszNewValue, int i = 0)
XMLCSTR XMLNode::updateText (XMLCSTR lpszNewValue, int i = 0)
XMLCSTR XMLNode::updateText (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLCSTR XMLNode::updateText (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLCSTR XMLNode::updateText (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLCSTR XMLNode::updateText (XMLCSTR lpszNewValue, XMLCSTR lpszOldValue)
References stringDup(), and updateText_WOSD().
XMLCSTR XMLNode::updateText_WOSD (XMLSTR lpszNewValue, int i = 0)
XMLCSTR XMLNode::updateText_WOSD (XMLSTR lpszNewValue, int i = 0)
References addText_WOSD(), NULL, and XMLCSTR.
Referenced by charmemset(), updateText(), and updateText_WOSD().
XMLCSTR XMLNode::updateText_WOSD (XMLSTR lpszNewValue, int i = 0)
XMLCSTR XMLNode::updateText_WOSD (XMLSTR lpszNewValue, int i = 0)
XMLCSTR XMLNode::updateText_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLCSTR XMLNode::updateText_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLCSTR XMLNode::updateText_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
References addText_WOSD(), NULL, and updateText_WOSD().
XMLCSTR XMLNode::updateText_WOSD (XMLSTR lpszNewValue, XMLCSTR lpszOldValue)
XMLError XMLNode::writeToFile (XMLCSTR filename, const char * encoding = NULL, char nFormat = 1) const
XMLError XMLNode::writeToFile (XMLCSTR filename, const char * encoding = NULL, char nFormat = 1) const
XMLError XMLNode::writeToFile (XMLCSTR filename, const char * encoding = NULL, char nFormat = 1) const
XMLError XMLNode::writeToFile (XMLCSTR filename, const char * encoding = NULL, char nFormat = 1) const
References _X, characterEncoding, createXMLString(), encoding_ShiftJIS, encoding_UTF8, eXMLErrorCannotOpenWriteFile, eXMLErrorCannotWriteFile, eXMLErrorNone, getChildNode(), isDeclaration(), xfopen(), XMLCHAR, and XMLSTR.
Member Data Documentation
XMLAttribute XMLNode::emptyXMLAttribute ={ NULL, NULL} static
Referenced by charmemset(), getAttribute(), and myRealloc().
XMLClear XMLNode::emptyXMLClear ={ NULL, NULL, NULL} static
Referenced by charmemset(), getClear(), and myRealloc().
XMLNode XMLNode::emptyXMLNode static
Referenced by charmemset(), CountLinesAndColumns(), deepCopy(), emptyNode(), getChildNode(), getChildNodeWithAttribute(), getParentNode(), myRealloc(), parseFile(), and parseString().
The documentation for this struct was generated from the following files:
/data/Software/DAQ/CDAQ/Plugins/Include/xmlParser.h
/data/Software/DAQ/CDAQ/Plugins/Source/xmlParser.cpp